### ISSUE TITLE
LINUX -xubuntu Game crashes on startup

### ISSUE THREAD

**Issue by nox-cpp** [ValveSoftware/Dota-2#1002]
After the Dark Rift update I am unable to launch the game. When attempting to launch it, the screen fades to black, then quickly back to whatever was on it previously. I was able to get the following through launching steam from a terminal:

`Game update: AppID 570 "Dota 2", ProcID 6454, IP 0.0.0.0:0
ERROR: ld.so: object '/home/marnix/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/marnix/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 6457 != 6456, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/marnix/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/marnix/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Using breakpad crash handler
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198053020637 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198053020637
Setting breakpad minidump AppID = 373300
Attempting to create OpenGL context: v3.3 (Core profile)...success.
Attempting to create OpenGL context: v3.3 (Core profile)...success.
DumpContextInfo: OpenGL vendor ATI Technologies Inc.
DumpContextInfo: OpenGL renderer AMD Radeon HD 7900 Series 
DumpContextInfo: Using OpenGL context version 3.3
DumpContextInfo: Context supports GLSL version 4.40
Fontconfig warning: "/home/marnix/.steam/steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/home/marnix/.steam/steam/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Installing breakpad exception handler for appid(gameoverlayui)/version(20160816194717)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
ERROR: ld.so: object '/home/marnix/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/marnix/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/marnix/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20160823214630_1.dmp[6473]: Uploading dump (out-of-process)
/tmp/dumps/crash_20160823214630_1.dmp
/home/marnix/.steam/steam/steamapps/common/dota 2 beta/game/dota.sh: line 104:  6459 Floating point exception(core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 6459 
No cached sticky mapping in ActivateActionSet.crash_20160823214630_1.dmp[6473]: Finished uploading minidump (out-of-process): success = yes
crash_20160823214630_1.dmp[6473]: response: Discarded=1
crash_20160823214630_1.dmp[6473]: file ''/tmp/dumps/crash_20160823214630_1.dmp'', upload yes: ''Discarded=1''
pid 6473 != 6472, skipping destruction (fork without exec?)
`

So far I have tried relaunching Steam. No result as of yet. I am currently validating the integrity of the game cache and will update once it's done. 

UPDATE: Verifying cache does not appear to have changed anything

**Comment by gdrewb-valve** [comment]
There's an AMD GPU problem occurring on all platforms and that's likely what you're hitting.  We believe we have a workaround that'll come out in the next update.

**Comment by nox-cpp** [comment]
Alright thanks for the info, really appreciate the quick feedback.

**Comment by gdrewb-valve** [comment]
The update with the fix has been released, are you still seeing this?

**Comment by DichromaticLB** [comment]
I think I have the same issue, the game's been the same since pitlord update.
I'm on a Debian flavour 64 bit
AMD FX 6300 
8gb ram
 AMD Sapphire HD7850

Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
ERROR: ld.so: object '/usr/$LIB/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/root/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/$LIB/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/root/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ERROR: ld.so: object '/usr/$LIB/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/root/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20160824013150_1.dmp[9981]: Uploading dump (out-of-process)
/tmp/dumps/crash_20160824013150_1.dmp
Setting breakpad minidump AppID = 570
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
crash_20160824013150_1.dmp[9981]: Finished uploading minidump (out-of-process): success = yes
crash_20160824013150_1.dmp[9981]: response: Discarded=1
crash_20160824013150_1.dmp[9981]: file ''/tmp/dumps/crash_20160824013150_1.dmp'', upload yes: ''Discarded=1''
pid 9981 != 9980, skipping destruction (fork without exec?)
ERROR: ld.so: object '/usr/$LIB/libgcc_s.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/root/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Installing breakpad exception handler for appid(steam)/version(1471977975)
/root/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 104:  9661 Segmentation fault      ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 9661 
No cached sticky mapping in ActivateActionSet.

**Comment by gdrewb-valve** [comment]
Do you have the latest update (there was a second smaller update today with the fix)?  If you do you'll need to keep crashing until one of your crashes has a crash ID.

**Comment by george-lukas** [comment]
Uff! I through it was only with me. I got a similar error. Instead black screen I got a visual glitch even after smaller update and steam minor update.
[http://pastebin.com/tG7bFkyd](url)
[http://imgur.com/a/yxMgn](url)

my system:
[http://pastebin.com/HVd8rgYW](url)

**Comment by gdrewb-valve** [comment]
@george-lukas please open a separate issue since you have a different problem.

**Comment by ghost** [comment]
@george-lukas looks like #1004 that I just opened

**Comment by george-lukas** [comment]
@gdrewb-valve seems that have a thread about this glitch. 
@impala2 thx for advice. :)

**Comment by nox-cpp** [comment]
I just updated  @gdrewb-valve I just installed the update and the game appears to run fine. The update seems to have fixed the problem. Thanks a lot!
