### ISSUE TITLE
Mac Osx  Source 2 warning - Only one instance of the game can be running

### ISSUE THREAD

**Issue by vaibhavch** [ValveSoftware/Dota-2#1012]
I am using Osx EI Captain 10.11.6  I am playing dota reborn without any issue since a year. during the recent update, whenever i start the game I got a popup saying "Only one instance of the game can be running at one time"

 I already did restarting mac,reinstalling steam as well as dota again. I am stuck with this issue. I am unable to play dota since a week.

 Please help me with this issue.

<img width="948" alt="screen shot 2016-09-03 at 3 44 12 am" src="https://cloud.githubusercontent.com/assets/1785310/18219659/f9452712-7188-11e6-8df5-0d12aa4a9d28.png">

**Comment by BetoMees** [comment]
Open your **Activity Monitor** and kill any process name **Dota 2** and try again.

**Comment by vaibhavch** [comment]
@BetoMees I already killed it. same error.

**Comment by vaibhavch** [comment]
@BetoMees But i can see that the process named "Steam Helper"  is not responding.
<img width="553" alt="screen shot 2016-09-03 at 4 12 29 pm" src="https://cloud.githubusercontent.com/assets/1785310/18224400/45a4d798-71f1-11e6-92cb-b9ae52f72daa.png">

**Comment by danginsburg** [comment]
Can you check if there is a file named /tmp/source_engine_*.lock?  If so, delete it and see if the problem goes away.  Another possible workaround is adding -allowmultiple to your Launch Options.  My guess is somehow there is a stray lock file in /tmp.

**Comment by danginsburg** [comment]
Closed pending more info.

**Comment by rickayy17** [comment]
i am just now having this problem. I try to run counterstrike global offensive and i am getting the error, is there a solution? and i too am on a mac with my steam helper not responding

**Comment by alikuro** [comment]
try,
myname$ cd /private
myname$ sudo chmod 777 tmp

**Comment by nvh95** [comment]
I have just encountered this problem. The reason is I deleted /tmp by accident. The solution is recreate one and make sure it is configured correctly. Follow this to fix [https://discussions.apple.com/thread/4986375](https://discussions.apple.com/thread/4986375)
or you can follow instructions bellow:
1. `cd /private` 
2. make sure there is `tmp` folder inside `/private` by `ls -l`, if not, create one by `sudo mkdir tmp`
3. `sudo ln -s private/tmp /tmp`
4. `sudo chmod -R 1777 private/tmp`
