### ISSUE TITLE
[MAC OSX] Cannot use CAPSLOCK key

### ISSUE THREAD

**Issue by adityakaulagi** [ValveSoftware/Dota-2#1029]
I can bind the capslock key to anything in the controls options menu, however, I cannot do the action the capslock key is bound to in game.

Right now, CAPSLOCK is my voice key, and when I press capslock in game, nothing happens. However, when I bind voice to some other key, like L, my voice works.

I started my game with `-input_message_spew` and `-console` and I saw this output when I pressed my capslock key:

```
SDL:  got SDL_KEYDOWN
KEYDOWN (keyc): sdlkeycode=1073741881 sdlscancode=57 SDL_GetKeyName='CapsLock' buttoncode=69 buttonname='CAPSLOCK' ButtonCode_GetLocalKeyNameUTF8='CapsLock'
SDL:  got SDL_KEYUP
KEYUP (keyc) sdlkeycode=1073741881 sdlscancode=57 buttoncode=69 buttonname='CAPSLOCK'
```

My System Information:

```
Computer Information:
    Manufacturer:  Apple
    Model:  MacBookPro11,3
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  2800 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce GT 750M

    Driver Version:  1.2
    Driver Date: 0  0
    OpenGL Version: 0.0
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x10de
    DeviceID:  0xfe9
    Revision:  0xa2
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 13.03" x 8.11"  (15.31" diag)
                                            33.1cm x 20.6cm  (38.9cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  16384 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  475968 Mb
    Largest Free Hard Disk Block:  315007 Mb
    VR Headset: None detected
```

I'm using the [Apple keyboard](http://www.apple.com/shop/product/MB110LL/B/apple-keyboard-with-numeric-keypad-english-usa) with numpad, which is connected through the USB port.

**Comment by gdrewb-valve** [comment]
This works properly for me on my Mac, we'll have to see if other people hit it to try and figure out what might be going on.

**Comment by FlaminSarge** [comment]
The issue I'm seeing is that when CAPSLOCK is pressed, DOTA considers it immediately released, for no discernible reason. I do not think this is an OS-level problem, as programs like Discord have no issues hooking up CAPSLOCK to Push-to-Talk (where the key must be held down to activate voice functions).

I conducted a little test; I did the following in Dota's console:

```
alias +test1 "test1_on"
alias -test1 "test1_off"
bind CAPSLOCK +test1
```

The output from pressing and holding CAPSLOCK without releasing was:

```
Unknown command: test1_on
Unknown command: test1_off
```

Releasing CAPSLOCK after this point did nothing.
Initially I thought this might be because I was opening console while holding a key, but I tried this with several other keys and none exhibited this behavior; I could keep holding the key as I opened console, and once I released the key, no matter when and in what state console was in, test1_off would be printed, rather than before releasing the key.

I also suspected it might be the way Dota hooks CAPSLOCK.
I went into my Mac system preferences and disabled Caps Lock as follows:
Keyboard > Modifier Keys... > Caps Lock > No Action

Once I did this, CAPSLOCK no longer functioned at all in Dota, but still functioned for applications such as Discord. Reassigning Caps Lock back to the Caps Lock modifier in the Mac system preferences brought back the ability to use Caps Lock in Dota, but with the limited press-and-release-immediately behavior. So it seems like Dota is hooking CAPSLOCK in a different way to other applications.

I'll try to post my system info here when I can.

@gdrewb-valve can you take a look at this again with this information in mind? Let me know if you need any more info.

**Comment by FlaminSarge** [comment]
Also wrote up this set of aliases that may or may not mitigate the problem (makes CAPSLOCK toggle voice when bound to `+voiceM`), given that Dota may or may not accept multiple 'alias' commands in one frame.

```
alias +voiceM +voice1
alias -voiceM -voice1
alias +voice1 +voicerecord
alias -voice1 "alias +voiceM +voice2; alias -voiceM -voice2"
alias +voice2 -voicerecord 
alias -voice2 "alias +voiceM +voice1; alias -voiceM -voice1"
```

**Comment by gdrewb-valve** [comment]
I do see the behavior where the key up for caps lock occurs immediately.  This is being reported by SDL so it's either something in the system or SDL and is all below Dota.  Assigning to the SDL dev for further investigation.

**Comment by adityakaulagi** [comment]
I found this bug on SDL bug list:

https://bugzilla.libsdl.org/show_bug.cgi?id=2157

I hope the [attached fix](https://bugzilla.libsdl.org/attachment.cgi?id=1837&action=diff) is helpful :)

**Comment by gdrewb-valve** [comment]
I would have thought that patch would have already been incorporated, but rcgordon will know.

**Comment by Tele42** [comment]
This is now [fixed upstream](https://hg.libsdl.org/SDL/rev/d19f7d2b6ec8) and will take effect when libSDL-2.0.5 makes it's way into production.

**Comment by rmbleeker** [comment]
I've actually seen the same behaviour on Linux for a while now, but never reported it. I simply stopped using the capslock key in Dota 2 and assigned it as my push-to-talk button in Mumble instead. Glad to see there is a fix for this on it's way though.

**Comment by gdrewb-valve** [comment]
The incoming fix is specific to OSX as far as I know.  I do not see the same problem on Linux.

**Comment by rmbleeker** [comment]
Doh. Sorry for the added noise. I had disabled the capslock key on my system, which obviously led to Dota 2 not recognizing it any more. Enabling capslock resulted in the desired behaviour, so I guess there's no issue on Linux.

**Comment by gdrewb-valve** [comment]
The Oct 13 update should have the OSX fix, is this still occurring?

**Comment by FlaminSarge** [comment]
Seems fixed on my end with a rudimentary test of binding `CAPSLOCK` to `+test1`, and seeing the error messages for "unknown command" for `+test1` and `-test1` occur at the correct times when pressing and releasing the key.

**Comment by adityakaulagi** [comment]
@gdrewb-valve 

Holding capslock now works for voice. Thanks for the quick turnaround on this issue!

**Comment by gdrewb-valve** [comment]
Thanks, closing.
