### ISSUE TITLE
[Linux] Oct 10 2016 Update breaks in-game chat

### ISSUE THREAD

**Issue by Conzar** [ValveSoftware/Dota-2#1041]
**Summary**
The in-game chat no longer works  after the Oct 10th, 2016 update.

**Problem**
Before, in-game chat worked without issues.  After the patch, when I press the enter key, the chat bar opens up and quickly closes.  I am able to use the chat without problems out of the game like pre-game chat, regional lobbies, etc.

**System Specs**
- OS: Ubuntu 14.04 LTS
- Steam package version: 1475701795
- CPU: Core i7-4770
- GFX: NVidia Geforce GTX 960
- RAM 16GB
- Disk: 60 GB SSD (dota 2 is installed here for very fast loading times)

**Comment by elarkham** [comment]
I have been experiencing the same issue except starting on the October 5th update. I had assumed it was an issue on my end because no one else I knew who used Linux was also experiencing it. I originally fixed it by switching my window manager but it seems to come and go somewhat randomly, as of the October 10th update, it has been permanent. 

When the issue is occurring it seems that pressing down on most keys results in the action being rapidly repeated. The main menu and hero abilities appear to be unaffected by this. 

Examples: 
- Clicking the ctrl button in the hero selection screen will enter grid mode and then exit.
- Holding space bar to force the camera to follow your hero (assuming you have it configured this way) results in the game rapidly re-selecting said hero. 
- In game chat is unusable due to the enter key causing the chat to rapidly open and close. 

For all examples if you hold down or press any of the keys, the action is repeated. 

I attempted to fix this by using `xset r` to disable key repeating but it only partially fixed the issue, it stops the action from being repeated infinitely when the key is pressed down but still repeats a few times on a "normal press", keeping the in game chat unusable. Its worth mentioning that `xset r` has no effect on the game when I'm not experiencing this issue, which I assume is the correct behavior. 

I hope this helps in any way.

**Comment by gdrewb-valve** [comment]
Does this repro in a bot game?  I just started a bot game on Linux and had no issues hitting enter to type and sent chat messages.

**Comment by elarkham** [comment]
Yes this is reproducible in bot games. However by a stroke of luck I think I may have found the root of the issue. It seems the problem will _only_ occur if you are running [SCIM](https://en.wikipedia.org/wiki/Smart_Common_Input_Method) in the background when starting the game. SCIM is started by default on many distributions and I believe KDE makes use of it as well.

**Comment by gdrewb-valve** [comment]
Ah, so this may be another IME issue like #1038.  There are SDL IME updates coming for #1038 and that may have a bearing here.

**Comment by Conzar** [comment]
Oh that's interesting.  I have language support installed on Ubuntu 14.04.  The keyboard input method is indeed fcitx.  So this bug is probably related to fcitx?  Even though it worked without issue before?

**Comment by gdrewb-valve** [comment]
The last couple of Dota updates have picked up newer versions of SDL and one of those changes led to some partial, unintended activation of fcitx (which is what #1038 is about).  An upcoming update will hopefully end up with functioning fcitx support in SDL and we'll see how that impacts the SCIM situation.

**Comment by Conzar** [comment]
@gdrewb-valve I exited the input manager for Ubuntu before starting a match last night, and in-game chat worked!  So this must be the problem.

**Comment by gdrewb-valve** [comment]
I believe the update on Oct. 12 contained full support for fcitx.  Can people comment on whether things are still broken or not?

**Comment by Conzar** [comment]
I can confirm the most recent patch fixed this bug.  I am closing issue.  Please open if anyone else is still having this issue.
