### ISSUE TITLE
Random Crash during game. All of the sudden

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1055]
That is just it. Suddenly the game crashed. I was casting WESG americas regional qualifier. I use a linux box with vulkan (nvidia 370.28) and my friend also casting through dotatv said he crashed as well barely seconds before me. He is using Windows 10 + probably DX.

We both used the new terrain from boston compedium. I don't know him, but i was using with everything maxed out with v-sync off.

Lots of interesting stuff in the tail of console.log here:
https://gist.github.com/admshao/41ba7b7774fae4dd089182991a2f85a5

also dmesg captured some libclient and libc segfaults
https://gist.github.com/admshao/84606848b7e16ba48ce259fec6e371b8

**Comment by gdrewb-valve** [comment]
The console log doesn't have any crash info so it doesn't appear like the crash was caught by Dota.  That often means it was the video driver that crashed and this may be related to Vulkan.

It's also possible it's a cross-platform issue since your friend crashed, but without crash info it's hard to say much about what's going on.

**Comment by gdrewb-valve** [comment]
Does this change with 7.00?

**Comment by gdrewb-valve** [comment]
Assuming inactive, closing.
