### ISSUE TITLE
[700] 15% ~ 20% performance loss

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/Dota-2#1097]
I got roughly 15~20% performance loss on my fps with this new patch.
(AMD 8 cores 4.8Ghz ...)

**Comment by Tele42** [comment]
I got a fairly good look at the new client last night and it feels like the overall performance is the same as before the update. However, the 3d rendered area is substantially larger than before because the 6.8x clients did not render 3d content behind the top and bottom UI elements. The 7.00 client has a larger viewport and my impression is that the larger viewport is just adding more overhead to the already cpu bottlenecked opengl render path.

**Comment by gdrewb-valve** [comment]
Performance on 7.00 is an issue across all platforms and will be handled by the larger team.  Leaving open #1101 for status.

**Comment by sylware** [comment]
vulkan! save us!
