### ISSUE TITLE
[Linux] Dota2 fails to start with error in dialog box

### ISSUE THREAD

**Issue by zeflap** [ValveSoftware/Dota-2#1155]
console output:https://gist.github.com/zeflap/c3d3bd16213aaf1a437633cf3ab5f5e7 
sysinfo: https://gist.github.com/zeflap/fc5fea15ab1167766dd639ae9252bc25
Dialog: ![1484587000](https://cloud.githubusercontent.com/assets/4191012/21993481/ac12cade-dc23-11e6-8d65-f64ac23a2f0b.png)

This started after installing [this](http://www.dota2.com/news/updates/26842/) patch and reproduction is a matter of trying to boot the game up.

**Comment by kisak-valve** [comment]
Hello @zeflap, the actual issue is "libudev.so.0: cannot open shared object file: No such file or directory" in the log.

The better way to resolve this is to compile a shim library which links against the system library like https://www.archlinux.org/packages/community/x86_64/libudev0-shim/ or https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/libudev-compat/files/udev_old.c while retaining ABI compatibility with libudev.so.0, but there is a more crude way of working around this by linking libudev.so.0 to libudev.so.1 and hope that the ABI-changed calls are not used.

Beyond that, this is an issue related to having the steam runtime disabled. You or your package manager who helped disable the steam runtime is responsible for managing any missing dependencies. Closing.

**Comment by zeflap** [comment]
Oh, I failed to see that might be what's causing it, thanks.

**Comment by zeflap** [comment]
@kisak-valve Managed to fix the issue by making /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 a symlink to .so.4.4.0 again, which does sadly break Don't Starve Together, fwiw.
