### ISSUE TITLE
[Sugestion] Create independent milestones for each update release

### ISSUE THREAD

**Issue by EPadronU** [ValveSoftware/Dota-2#116]
First of all: I'm very thankful for the great and hard work you devs are doing here. In particular, is great that you're indicating which bugs will be fix in the next update release, but for what I can see, you only have one milestone `next release`. It would be nice if you could create one milestone for each update release, for example: keep the bugs and suggestions to be release in the next update under the `next release` milestone and move the already fixed bugs in another one called `Update - 20150624`. That way we the users and you the devs could get a history of what bug was fixed in what update and also we could know which bugs will be fixed with the next update.

I apologize for my bad English. Keep with the great work.
Cheers.

**Comment by gdrewb-valve** [comment]
We don't keep around old releases so I'm not sure of the value of marking specific dates.  A person couldn't pick a particular release to go back to, for example, so it seems like there are just three buckets: things that are fixed in the current release, things that will be fixed in the next release and things that aren't fixed.  Those correspond to closed items, milestone: next-release items and no milestone items.

**Comment by EPadronU** [comment]
I understand your point. I thought you were doing this with the `next release` milestone but I wasn't sure. Thanks for clarifying it.

**Comment by gdrewb-valve** [comment]
We also may change the scheme in the future if being more precise helps out in some way, but for right now the current approach seems to be working.
