### ISSUE TITLE
Linux unusable UI in hero selection

### ISSUE THREAD

**Issue by philipgroet** [ValveSoftware/Dota-2#118]
Hi,

With the release of the Reborn Beta on linux I tried starting dota 2 reborn, and play a solo botgame. Sadly it didn't really work as expected. http://i.imgur.com/xpxwGfC.jpg
Name: 2015-06-26_00001.jpg  Views: 1  Size: 230.0 KB  ID: 32396
I hear the voice pack saying: "Make your pick", but I'm unable to see anything of the UI and am unable to even click on anything.

System I'm running:
- Linux 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- i7-3770k
- Nvidia GTX 670
- Video driver version: version string: 4.3.0 NVIDIA 331.113

Nothing in syslog, and no errors.

Thanks

**Comment by gdrewb-valve** [comment]
Can you update your drivers to 352 and try again?

**Comment by amfg** [comment]
Sorry I did not notice there is a separate repo for reborn.
Avraamu's issue might be similar to mine
https://github.com/ValveSoftware/Dota-2/issues/1798

**Comment by amfg** [comment]
I can confirm it does not occur with 352.21. Thank you.

**Comment by gdrewb-valve** [comment]
@Avraamu , does updating your driver help?

**Comment by Avraamu** [comment]
Sorry, I have not tried updating yet, will be back home in a couple of days, will give an update.

**Comment by glajchs** [comment]
I was also having what was probably this issue.  My UI was very messed up in a custom gam (battleships), and the steam overlay UI in the reborn client was also unusable (flickered between green and white).  I had Nvidia drivers 331.113 just like the original poster.

I just updated to the latest driver (352.21) and everything works now!

If it helps when I want to use the nvidia drivers via download (instead of from the package manager), I usually have to install them with the window manager off.
Download the file, note its location, and run it like so:

You might need to replace "mdm" with your window manager, and adjust the path to the file.

sudo /etc/init.d/mdm stop
sudo sh /home/scott/Downloads/NVIDIA-Linux-x86_64-352.21.run -s

**Comment by Avraamu** [comment]
After a  lot of hassling with Nouveau not wanting to disable, I got the drivers and Dota Reborn working.

Thanks

**Comment by gdrewb-valve** [comment]
Thanks, closing.
