### ISSUE TITLE
Missing dependency to libtxc-dxtn-s2tc:amd64 on Ubuntu 17.04

### ISSUE THREAD

**Issue by Zomtir** [ValveSoftware/Dota-2#1213]
With the upgrade from Ubuntu 16.04 to 17.04 Dota 2 was bringing up the following error:
`GL_EXT_TEXTURE_COMPRESSION_S3TC is not supported.`

Long story short, Dota 2 requires `libtxc-dxtn-s2tc:amd64` to be installed while steam only depends on `libtxc-dxtn-s2tc:i386`.

Steam package version: 1490228413

Can this dependency be fixed?

**Comment by kisak-valve** [comment]
Hello @Zomtir, this package is only required for mesa, and steam does not interact with your package manager on a per-game basis. Adjusting this dependency should not require this library for nvidia and amd proprietary driver users.

If you are using the distro-provided steam package, please contact a ubuntu package maintainer for steam. Otherwise, If you are using the upstream deb from Valve, then this should be in the [steam-for-linux](https://github.com/ValveSoftware/steam-for-linux) issue tracker.

As a side note, the S3TC patent expires on 2017-10-02, so at least this legal snafu can start going away next year.

**Comment by Zomtir** [comment]
I'm using the distro provided steam package with mesa. Thanks for the follow up!

Filed a bug report on the package: https://bugs.launchpad.net/ubuntu/+source/steam/+bug/1684755

**Comment by AngryPenguinPL** [comment]
Same here. Look like it a Ubuntu 17.04 bug.
This fix it. Terminal: `sudo apt-get install libtxc-dxtn-s2tc:i386 libtxc-dxtn-s2tc:amd64`
