### ISSUE TITLE
[Fedora25][Nvidia] Black screen and crash

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#1217]
Hi,
My last game is yesterday and there is no driver update as I remember.
Today I am unable to play any matches because everytime its entering the game after picking phase
my screen suddenly become black, its like shutting down my graphic card and I can know the computer
is hang because my keyboard or mouse cant make any action after that.

I will need to restart my computer everytime.

Here is my computer specs

AMD Phenom II x4 920
6 GB RAM
Nvidia 760 Ti

Driver : Nvidia 378.13 from negativo17 repo

and by the way I cant access system information from steam now, it will crash steam.
I dont know why.

Update:

Try on Vulkan and same result

**Comment by gdrewb-valve** [comment]
This doesn't sound like a Dota problem since a malfunctioning program can't hang your computer, only faulty system software.  As you already have a recent driver it's unclear what's going on, you may want to ask on a forum associated with your distro or with NVIDIA.

I'll keep this open for a while to see if other people are experiencing similar problems.

**Comment by rained23** [comment]
Can you help close this, my gpu cable burnt. Hardware issue

**Comment by gdrewb-valve** [comment]
OK, closing.
