### ISSUE TITLE
GameUI_Disconnect_MessageParseError

### ISSUE THREAD

**Issue by YangtseSu** [ValveSoftware/Dota-2#1240]
Archlinux zh_CN
This happens while playing game or watching a game.
https://img.vim-cn.com/22/c12a92808093058e8d49c6f5eb6d7539e8d8cf.png

**Comment by gdrewb-valve** [comment]
There isn't enough information for us to diagnose the issue.  Can you include your console text fromr Dota so that we can see networking errors?  Has Dota worked in the past?  If so when did this start happening?  Also we'll need specific information on your networking (wi-fi, wired, etc.) and internet to see if this is related to your system.  Also please post a gist of your full system specs.

**Comment by YangtseSu** [comment]
Dota2 works well,this happens about since a week ago.
I use wi-fi.
[sysinfo.txt](https://github.com/ValveSoftware/Dota-2/files/1030535/sysinfo.txt)

**Comment by gdrewb-valve** [comment]
Have you verified your Dota install?  Can you include your console text, as requested?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
