### ISSUE TITLE
[Linux] Game crashed on loading after accepting the match

### ISSUE THREAD

**Issue by admshao** [ValveSoftware/Dota-2#1275]
Normal match. Dota crashed and leave this on Dmesg [ 3214.784846] traps: dota2[13012] general protection ip:7f7f62679033 sp:7ffd6a970848 error:0 in libvulkan.so.1.0.51[7f7f6265f000+47000]

I couldn't reconnect and got penalty for this. Great.

System Info: https://gist.github.com/admshao/137d89e0a9d35e635d9282285bcf2031

**Comment by AngryPenguinPL** [comment]
Hey. In my observation I see that most Linux games have issues with bleeding edge distro like Arch...
For some users help launch Steam games with Steam-runtime not with system runtime like doing in arch or manjaro. Maybe you can check this game with Steam-runetime enabled?

**Comment by ankhharu** [comment]
I'm having the same problem. I accept the match, and while loading, dota crashes. I'm on Fedora 25, this just started today. Worked fine last night. 

**[ 3572.530874] dota2[2340]: segfault at 55b75f4009e8 ip 00007fdebe133b76 sp 00007ffc6dbeda60 error 4 in libjemalloc.so.2[7fdebe12f000+43000]**

I can recreate the issue if I start a bot match in steam-runtime. However, bot match opens fine in steam-native.

**Comment by djspacewhale** [comment]
I've been having this issue for a week, and my past 4 games have all been abandons despite my rebooting my computer after dota freezes everything up on map load and loading back in 10 minutes into the match. stuck in low prio for the seeming future because of this craziness. running Fedora 26, mystro256's amd mainline kernel. I understand you can't appeal low prio appointments, but it'd be fantastic if you weren't placed in there for seemingly-common technical bugs in the engine.

**Comment by gdrewb-valve** [comment]
@admshao, do you get the crash if you don't use vulkan?

**Comment by admshao** [comment]
@AngryPenguinPL I was using steam-runtime.

@gdrewb-valve Will test again soon

**Comment by admshao** [comment]
Vulkan or GL.. Played 1 game on each and had no crash. Maybe it's ok now after latests patches

**Comment by gdrewb-valve** [comment]
We'll hold this open for a bit and see if it happens on future games for you.

**Comment by gdrewb-valve** [comment]
Closing as this doesn't seem to have happened again.
