### ISSUE TITLE
Dota 2 is undergoing massive botnet attack

### ISSUE THREAD

**Issue by regs01** [ValveSoftware/Dota-2#1372]
It's being going for a 3rd day already. Impossible to start any custom game as mode is completely locked down by bots. Does anyone care actually?

**Comment by gdrewb-valve** [comment]
Closing as the issue is not something this tracker is for.  Valve is aware of the attack.

**Comment by regs01** [comment]
5th day...

**Comment by darklordabc** [comment]
Prehaps this isnt the place for it, but Valve has finally fixed the bots, but they did a really sub-optimal solution which has left a lot of people unable to join custom game lobbies. Is this intentional or is it a mistake? Nobody knows, could you please confirm one way or another.
https://www.reddit.com/r/DotA2/comments/7rg3fg/i_am_a_custom_game_creator_and_i_cant_even_join/
