### ISSUE TITLE
[MAC] Screen stutters when someone cast an ability for the first time in a game

### ISSUE THREAD

**Issue by bojunwu** [ValveSoftware/Dota-2#1382]
Screen stutters when someone cast an ability/item(like a tp) for the first time in a game. I guess the game just need some time to load the ability or item animation into memory. It's not really a bug but it's pretty annoying.

**Comment by danginsburg** [comment]
I can explain why this is, but unfortunately there is not a lot we can do about it on macOS.  What you are likely seeing is the cost to compile shaders when a new shader is used.  On Windows/Linux we mitigate this in two ways:

1. We use GL_ARB_get_program_binary and store a cache on disk of all previously compiled shaders.  This is loaded at startup and written to disk any time a new shader is encountered so after seeing a shader once you will not stutter again.  This extension is not supported in OpenGL on macOS.

2. We recently released Steam Shader Pre-Caching for Vulkan/OpenGL on Windows/Linux (http://store.steampowered.com/news/35534/).  This does even better by downloading a pre-warmed cache so that even the first time your machine sees a shader it is already cached and does not need to be compiled by the driver.

There is an option in Dota 2 to compile all shaders up front (-gl_disable_defer_shader_compiles -gl_time_shader_compiles).  Unfortunately, you will see much longer load times if you use this option.  For example on my MacPro this adds an additional 222 seconds to compile 12417 shaders.  It also increases memory usage.  It's not a realistic option to use, but you can see for yourself if you want to try it.

We also do a lot of work to try to ease the cost of compiling shaders, namely using LunarGLASS (https://github.com/LunarG/LunarGLASS/) to optimize the GLSL offline so that the driver has less to do.  Even with all that, there are still going to be stutters on macOS with OpenGL.

**Comment by athei** [comment]
Why not use Metal then? It seems that this is the way forward on macOS und surely supports binary shaders.

**Comment by roubachof** [comment]
@danginsburg  Does the `-gl_disable_defer_shader_compiles -gl_time_shader_compiles` options will still work todays on M1/2/3 macs ?
If yes, how do you set them ? I am not really familiar with those
