### ISSUE TITLE
Can't queue for or watch games.

### ISSUE THREAD

**Issue by weidtn** [ValveSoftware/Dota-2#1473]
#### Your system information

* https://gist.github.com/Aramus92/17b5e2e4a00aaacee54ffb69e22b309a
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes
#### Please describe your issue in as much detail as possible:

I can't search for a game. I click "Play Dota", select my Modes, then the "Play Dota" button gets grey, I get no queue status, and can't click this button again. When trying to watch any game I get this message after a short "waiting to watch game...":

"Check your Internet connection. Unable to download the network configuration from CDN".

Whenever I boot into windows (dual boot on same machine) Dota works without any problems.

**Comment by weidtn** [comment]
I just realized I can opt-out of Steam beta, did this, now it works again. So try to fix your beta.

**Comment by mjstahlberg** [comment]
Hello @Aramus92, I encountered the same problem under Arch Linux and opting out of the Steam Beta fixed it as well. So thanks! Since this appears to be at least partly a bug in Dota 2 and potentially just under Linux I suggest you keep this issue open, though?

**Comment by kisak-valve** [comment]
Hello @Viech, there are other open issue reports for this issue including #1474 and https://github.com/ValveSoftware/steam-for-linux/issues/5545.

**Comment by andrewnwq** [comment]
it is not working for me =( tried all methods ..

**Comment by gambitflush** [comment]
![screen shot 2018-10-04 at 1 53 36 am](https://user-images.githubusercontent.com/43794895/46437190-63d97a00-c778-11e8-8435-f11ebfefdac9.png)
hi, i use a macbook air os X 10.9.5 . I have got the same issue "Check your Internet connection. Unable to download the network configuration from CDN". This appears whenever i try to watch a video and when i try to find game the 'play dota' button on the right bottom freezes. I have contacted steam and valve as well and i haven't got any fix for that. This happened when i purchased dota plus few days ago.   i have rebooted my whole laptop and downloaded steam and game again and yet this issue comes up . i also reset my router and my net works absolutely fine. please help me out . thanks
![screen shot 2018-10-04 at 1 53 14 am](https://user-images.githubusercontent.com/43794895/46437178-5c19d580-c778-11e8-8e92-d3c8f2159774.png)

**Comment by yclyldrm** [comment]
Hi @gambitflush. Can you solve the problem? I have got same problem,too.

**Comment by Waviee** [comment]
Hey there, same issue here, made a bug ticket.

https://github.com/ValveSoftware/Dota-2/issues/1518

**Comment by wubwoofwolf** [comment]
Hi, I have the exact same problem.

**Comment by yclyldrm** [comment]
After I installed El Capitan(10.11.6), my problem gone. Maybe you can try upgrade your OS version.

**Comment by wubwoofwolf** [comment]
> After I installed El Capitan(10.11.6), my problem gone. Maybe you can try upgrade your OS version.

It sucks if that's the only solution because i'm on a hackintosh and can't upgrade my OS since my current version is the only one that supports Nuendo, a program I need for work. Also going through the effort of upgrading on hackintosh is too much and it may not even solve it.

**Comment by 2ndN** [comment]
i got this problems too 
i had Kali-linux first but after I tried everything i could (and still had this problem)
Installed windows and now this problem returned 
I have dota plus and this problem appeared after purchasing dota plus
I can't watch . i can't find [the key appears to grey colour after trying to find]

**Comment by 2ndN** [comment]
LOL it just fixed automatically after waiting to find 1v1 match on Dubai server (about 11 minutes taken) 
.
.
.
.
So i guess we have to find a game which never finds !!! For example (all random death-match) on Austalia
