### ISSUE TITLE
[Linux] someone else talks in the party and game shows my name instead of that player

### ISSUE THREAD

**Issue by Weirdo1312** [ValveSoftware/Dota-2#1593]
#### Your system information

* System information from steam: https://gist.github.com/aligodlike/2687921cf50fa289539ce4b3e79b2997
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
doesn't matter who is talking in-game (in party) or in main menu
it shows my own name as the one who is talking

#### Steps for reproducing this issue:

1. Open dota 2
2. join a party
3. someone else starts talking in mic and it shows my own name as the one who is using microphone

**Comment by josinaldobarbosa** [comment]
+1
[System information](https://gist.github.com/josinaldobarbosa/2ec12518f88195e786b47ec7d7c9c5f4)

**Comment by glubsy** [comment]
I have noticed this problem too. When I'm in a party, if a party member uses their microphone during a match, the bubble on the right side of the screen displays my own nickname, not theirs. 

Not sure if this is Linux specific, but my other team mates (most likely Windows users) didn't seem to notice... or they didn't bother at all because they already knew it's a bug?

Current system information: [gist](https://gist.github.com/glubsy/8930de18e83adb497905097091e9789c/bfb094255a0435a903c0f608a291009a6220251b)

**Comment by Weirdo1312** [comment]
> I have noticed this problem too. When I'm in a party, if a party member uses their microphone during a match, the bubble on the right side of the screen displays my own nickname, not theirs.
> 
> Not sure if this is Linux specific, but my other team mates (most likely Windows users) didn't seem to notice... or they didn't bother at all because they already knew it's a bug?
> 
> Current system information: [gist](https://gist.github.com/glubsy/8930de18e83adb497905097091e9789c/bfb094255a0435a903c0f608a291009a6220251b)

i'm pretty sure it's a linux only problem

**Comment by Weirdo1312** [comment]
This doesn't happen anymore
