### ISSUE TITLE
[Summer Scrub] game client doesn't respect system locale when displaying match dates

### ISSUE THREAD

**Issue by Cabanur** [ValveSoftware/Dota-2#1639]
#### [System information (gist)](https://gist.github.com/Cabanur/be3f08865bdd424ca28a309e2ecfbf61)

The game client uses the US date format (MM/DD/YYYY) in the recent matches list (see attatched picture), even though my locale settings indicate preference for DD/MM/YYYY.

This may also affect Windows, but I can't test it.

![dota-locale](https://user-images.githubusercontent.com/6509819/61255790-61299d80-a76a-11e9-9bc1-1b663a6686a8.png)

**Comment by gdrewb-valve** [comment]
Try adding

  -textsublanguage GB

to your launch options.

**Comment by Cabanur** [comment]
This correctly sets the date format in the recent game list and elsewhere. Thank you.

Was this caused by my mixed locale settings? Will the cilent autodetect the preferred format in the future?

**Comment by gdrewb-valve** [comment]
It's not related to your locale settings, it's because Dota on Linux forces the locale to en_US to avoid some text handling bugs.  I don't believe that's going to change.  Remove -textsublanguage GB and try with -set_locale_disable instead, does that work?  If so it confirms that it's due to the locale forcing.  In that case -textsublanguage would be the better option since it keeps the locale forcing to avoid that set of bugs while still getting your preferred regional language style.

**Comment by Cabanur** [comment]
Using `-set_locale_disable` has the same effect, dates are correctly in my prefered format.

Since you mentioned some text bugs I'll keep an eye out for those and if they appear switch back to `-textsublanguage GB`. If I find those, should I report them? Or are you already aware of them and have other priorities at the moment?

**Comment by gdrewb-valve** [comment]
My understanding is the that problems only show up in specific locales, such as Turkish, so you may not see any issues.  If you do feel free to report them and then the Dota team can decide what to do with them.
