### ISSUE TITLE
[Linux] FIRST LAUNCH Results In Complete System Freeze

### ISSUE THREAD

**Issue by shoober420** [ValveSoftware/Dota-2#1640]
* System information from steam: https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Installing the game, and doing a first launch will completely freeze the system, resulting in having to do a hard reset. I remember when I installed DOTA 2 a year ago, on first launch, it happend as well. After a hard reset, the game boots up fine. It was on OpenGL API.

#### Steps for reproducing this issue:

1. Fresh install of DOTA 2
2. Launch game for the first time
3. Complete system freeze

**Comment by Hursofid** [comment]
I can confirm the same thing for me - kernel panic after launching game in less than a minute
yesterday everything was fine
checked local files, reinstalled dota completely

```
Thu Jul 18 10:10:25 2019

*** Panic Report ***
panic(cpu 0 caller 0xffffff800c38dd11): "Spinlock acquisition timed out: lock=0xffffff801a5b2bc8, lock owner thread=0xffffff801aadcdb0, current_thread: 0xffffff801c1cadb0, lock owner active on CPU 0x3, current owner: 0xffffff801aadcdb$
Backtrace (CPU 0), Frame : Return Address
0xffffff80a55b3d70 : 0xffffff800bedab52
0xffffff80a55b3df0 : 0xffffff800c38dd11
0xffffff80a55b3f30 : 0xffffff800c38b564
0xffffff80a55b3f60 : 0xffffff800c428341
0xffffff80a55b3fb0 : 0xffffff800bfec3f6

BSD process name corresponding to current thread: dota2

Mac OS version:
15G22010

Kernel version:
Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64
Kernel UUID: 7564B0E7-EB5D-3887-BA79-59C870165AB1
Kernel slide:     0x000000000bc00000
Kernel text base: 0xffffff800be00000
__HIB  text base: 0xffffff800bd00000
System model name: MacBookAir6,2 (Mac-7DF21CB3ED6977E5)
```

@shoober420 what do you mean by "hard reset"?

**Comment by kisak-valve** [comment]
Possible duplicate of #1616.

**Comment by shoober420** [comment]
@Hursofid, It’s another way of saying restart via the button on the tower.

**Comment by Hursofid** [comment]
Well, that doesn't helped me out with the problem occurred...:(

**Comment by NotInThere** [comment]
I'm not sure if it's the same issue but I'm getting the exact same crash on main menu on OS X and its happening every time I launch. Its generating a CPU lockup and crashing the entire system. 

https://gist.github.com/NotInThere/b2e0f3a521a9ab01ea6ef1fcf6209235

I should state that this only started after the recent update as of yesterday (July 17th 2019). I had hoped that the small update a couple of hours later would address the issue but that's not the case.

I attached the OS Crash Report first in the text dump and lastly the Steam Info.

I have tried the typical: 
Deleting the download cache, verifying dota 2, and repairing disk permissions.

**Comment by ssukhadi** [comment]
@NotInThere Experiencing the same exact problem and it started as soon as the new patch downloaded at 5:17 PM on July 17th, 2019. Tried everything as well, hoping that theres some quick fix for this bug but it's still happening as of 2 minutes ago. My whole computer shuts down and a black screen comes up with a "A problem has occurred which has shut down your computer". Let me know if anything changes!

**Comment by zuhalm** [comment]
thsi is my system information


>
>  Computer Information:
> 
>     Manufacturer:  Apple
>     Model:  iMac12,2
>     Form Factor: Desktop
>     No Touch Input Detected
> 
> Processor Information:
>     CPU Vendor:  GenuineIntel
>     CPU Brand:          Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
>     CPU Family:  0x6
>     CPU Model:  0x2a
>     CPU Stepping:  0x7
>     CPU Type:  0x0
>     Speed:  3100 Mhz
>     4 logical processors
>     4 physical processors
>     HyperThreading:  Unsupported
>     FCMOV:  Unsupported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
>     AES:  Supported
>     AVX:  Supported
>     CMPXCHG16B:  Supported
>     LAHF/SAHF:  Supported
>     PrefetchW:  Unsupported
> 
> Operating System Version:
>     MacOS 10.11.6 (64 bit)
> 
> Video Card:
>     Driver:  AMD Radeon HD 6970M
>     Driver Version:  1.2
>     OpenGL Version: 2.1
>     Desktop Color Depth: 32 bits per pixel
>     Monitor Refresh Rate: 0 Hz
>     VendorID:  0x1002
>     DeviceID:  0x6720
>     Revision Not Detected
>     Number of Monitors:  1
>     Number of Logical Video Cards:  1
>     Primary Display Resolution:  2560 x 1440
>     Desktop Resolution: 2560 x 1440
>     Primary Display Size: 23.46" x 13.19" (26.89" diag)
>                                             59.6cm x 33.5cm (68.3cm diag)
>     Primary VRAM: 0 MB
> 
> Memory:
>     RAM:  16384 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     Media Type:  DVD
>     Total Hard Disk Space Available:  953049 Mb
>     Largest Free Hard Disk Block:  681028 Mb
>     VR Headset: None 
> 



i just updated dota 2 18 july 2019. when i launch the game it forced my mac to restart. i dont know how this is happen, before i updated i play dota it runs very well. this is so annoying btw. please resolve this :(

**Comment by danginsburg** [comment]
So far all the macOS reports are on macOS 10.11.6 - is anyone seeing this behavior on any other version?  We are suspecting some incompatibility with some low-level changes on macOS 10.11.  If anyone experiencing this can upgrade and tell us what version it resolves at that would be good information.

**Comment by NotInThere** [comment]
I'm currently updating straight to 10.13 from 10.11 since its a performance update of 10.12 and will update  once that finishes.

**Comment by NotInThere** [comment]
Ok so after the update to 10.13 Its no longer crashing upon hitting the main menu. Something!
I haven't launched a game or had DotA running for too long yet so will update if anything changes.

**Comment by zuhalm** [comment]
> Ok so after the update to 10.13 Its no longer crashing upon hitting the main menu. Something!
> I haven't launched a game or had DotA running for too long yet so will update if anything changes.

really ? should i update this mac :(  please valve resolve this problem . i dont want to update this os :(

**Comment by bjrmatos** [comment]
i'm on OSX 10.11.5 and i also see the crash every time i open the game, sometimes it loads the main menu but afters 2 seconds it crashes causing a restart of my machine.

i can't not upgrade to newer OS X because some hardware incompatibilities of my machine, but i never experienced a crash like this in the past. 

the crash started after the [The International Compendium Update](http://blog.dota2.com/2019/07/the-international-compendium-update-3/) (July 17, 2019). 

if someone can recommend me some launch parameters to try or some steps to collect information for helping to debug the issue i'm more than happy to help since this is causing that i'm loosing hours of fun playing the game :(

UPDATE: this is my system information (from steam)

```
Información del equipo:
    Fabricante: Apple
    Modelo: MacPro3,1
    Factor de forma: Sobremesa
    Entrada táctil no detectada

Información sobre el procesador:
    Fabricante de la CPU: GenuineIntel
    Marca de la CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Familia de la CPU: 0x6
    Modelo de la CPU: 0x3c
    Stepping de la CPU: 0x3
    Tipo de CPU: 0x0
    Velocidad: 3600 MHz
    Procesadores lógicos: 8
    Procesadores físicos: 4
    HyperThreading:  Compatible
    FCMOV:  No compatible
    SSE2:  Compatible
    SSE3:  Compatible
    SSSE3:  Compatible
    SSE4a:  No compatible
    SSE41:  Compatible
    SSE42:  Compatible
    AES: Compatible
    AVX: Compatible
    CMPXCHG16B: Compatible
    LAHF/SAHF: Compatible
    PrefetchW: No compatible

Versión del sistema operativo:
    MacOS 10.11.5 (64 bits)

Tarjeta de vídeo:
    Controlador:  NVIDIA GeForce GTX 750
    Versión del controlador: 1.2
    Versión de OpenGL: 2.1
    Profundidad de color del escritorio: 32 bits por píxel
    Frecuencia de actualización del monitor: 60 Hz
    Identificador del fabricante: 0x10de
    Identificador del dispositivo: 0x1381
    Revisión: 0xa2
    Número de monitores: 2
    Número de tarjetas de vídeo lógicas: 1
    Resolución de pantalla principal: 1920 x 1080
    Resolución de escritorio: 3840 x 2160
    Tamaño de la pantalla principal: 23.82" x 13.58" (27.40" diag)
 60.5cm x 34.5cm (69.6cm diag)
    Memoria VRAM principal: 0 MB

Memoria:
    RAM: 24576 MB

Varios:
    Idioma de la IU:  Español - España
    Tipo de soporte: DVD
    Espacio total en disco disponible: 2135517 MB
    Bloque libre más grande en el disco: 963380 MB
    Visor de RV: Ninguno detectado
```

**Comment by danboroda** [comment]
Computer Information:
    Manufacturer: Apple
    Model: MacBookPro8,1
    Type: Laptop
    Touch input not supported

CPU:
    Processor Manufacturer: GenuineIntel
    Processor Manufacturer: Intel (R) Core (TM) i5-2415M CPU @ 2.30GHz
    Processor Family: 0x6
    Processor Model: 0x2a
    CPU stepping: 0x7
    Processor Type: 0x0
    Clock frequency: 2300 MHz
    Logic Processors: 4
    Physical Processors: 2
    Hyper-Threading: Supported
    FCMOV: Not Supported
    SSE2: Supported
    SSE3: Supported
    SSSE3: Supported
    SSE4a: Not Supported
    SSE41: Supported
    SSE42: Supported
    AES: Supported
    AVX: Supported
    CMPXCHG16B: Supported
    LAHF / SAHF: Supported
    PrefetchW: Not supported

OS version:
    MacOS 10.11.6 (64 bit)

Video card:
    Model: Intel HD Graphics 3000
    Driver Version: 1.2
    OpenGL Version: 2.1
    Color depth: 32 bits / pixel
    Refresh rate: 0 Hz
    Manufacturer ID: 0x8086
    Card ID: 0x126
    Version: 0x9
    Screen count: 1
    Number of logical video cards: 1
    Resolution DOS. of the screen: 1280 x 800
    Desktop resolution: 1280 x 800
    The size of the base. of the screen: 11.22 "x 7.01" (13.23 "diag)
 28.5cm x 17.8cm (33.6cm diag)
    Basics video memory: 0 MB

Memory:
    RAM: 8192 MB

Miscellanea:
    Interface language: Russian
    Media Type: DVD
    Disk Space: 532693 MB
    Most free disk: 91399 MB
    Virtual reality helmet: not detected

**Comment by danboroda** [comment]
got same trouble guys
do not want to upgrade os because it will make mac slower(
Computer Information:
    Manufacturer: Apple
    Model: MacBookPro8,1
    Type: Laptop
    Touch input not supported

CPU:
    Processor Manufacturer: GenuineIntel
    Processor Manufacturer: Intel (R) Core (TM) i5-2415M CPU @ 2.30GHz
    Processor Family: 0x6
    Processor Model: 0x2a
    CPU stepping: 0x7
    Processor Type: 0x0
    Clock frequency: 2300 MHz
    Logic Processors: 4
    Physical Processors: 2
    Hyper-Threading: Supported
    FCMOV: Not Supported
    SSE2: Supported
    SSE3: Supported
    SSSE3: Supported
    SSE4a: Not Supported
    SSE41: Supported
    SSE42: Supported
    AES: Supported
    AVX: Supported
    CMPXCHG16B: Supported
    LAHF / SAHF: Supported
    PrefetchW: Not supported

OS version:
    MacOS 10.11.6 (64 bit)

Video card:
    Model: Intel HD Graphics 3000
    Driver Version: 1.2
    OpenGL Version: 2.1
    Color depth: 32 bits / pixel
    Refresh rate: 0 Hz
    Manufacturer ID: 0x8086
    Card ID: 0x126
    Version: 0x9
    Screen count: 1
    Number of logical video cards: 1
    Resolution DOS. of the screen: 1280 x 800
    Desktop resolution: 1280 x 800
    The size of the base. of the screen: 11.22 "x 7.01" (13.23 "diag)
 28.5cm x 17.8cm (33.6cm diag)
    Basics video memory: 0 MB

Memory:
    RAM: 8192 MB

Miscellanea:
    Interface language: Russian
    Media Type: DVD
    Disk Space: 532693 MB
    Most free disk: 91399 MB
    Virtual reality helmet: not detected

**Comment by shoober420** [comment]
I want to clarify that my complete system freeze only occured on first launch after installing the game. The game boots now after I hard reset my computer.

**Comment by Yakobius** [comment]
Hey, I have the same problem  and i just updated my Mac to see if it helps. I have El Capitan 10.11.6. Still shuts down after a few seconds upon starting Dota 2. It says also "Spinlock acquisition timed out:  ....

**Comment by jojalapa** [comment]
Still have same problem after the latest update in dota 2 :(. How can we help?

**Comment by cdtapay** [comment]
Having this same issue. My mac version is: El Capitan OSX 10.11.6 

Rollback the last update is an option. Basically, thousands of users cannot play.

**Comment by ssukhadi** [comment]
You're all going to need to update boys, I switch from sierra 10.11.16 to Mojave 10.15.16 and it works beautifully. Honestly the computer works better in general. Time to just bite the bullet and get it done because it won't work any other way at least for right now.

**Comment by danboroda** [comment]
> You're all going to need to update boys, I switch from sierra 10.11.16 to Mojave 10.15.16 and it works beautifully. Honestly the computer works better in general. Time to just bite the bullet and get it done because it won't work any other way at least for right now.

maybe you're right but we want more loyal user policy from valve

**Comment by amgorb** [comment]
same issue: crashes even with -vulkan option. MacOS Yosemite 10.10.5

**Comment by shoober420** [comment]
The DOTA 2 page does say that 10.9 is minimum, but when the updates keep coming, that can change. So for example, 10.9.4 was ok, but 10.9.7 might brake compatibility.

Honestly, any individual should use the latest version of any software. You’re literally asking for trouble, and only making it harder on yourself. There could even be security and performance improvements you’re missing out on because you won’t update.

**Comment by jojalapa** [comment]
i don't know if after update my old mac will be with same speed. Right now 10.11.6 works really good with no problems. I am fine not playing DOTA then. 
Thank you for the solution valve.

**Comment by ghost** [comment]
Hi,

Any news about this bug ?

As a lot of concerned people I am on MacOS ElCapitan 10.11.6, and honestly an os update is really not a solution, we need a real fix please. Some can't upgrade because they have old macs, some for compatibility problems, (myself, i have a slow internet and the upgrade to Mojave took me 2 days, i tried it once, installation problem, i need to download it again... yay... -_-)

My system information : 
```
Informations de l'ordinateur :
    Fabricant : Apple
    Modèle : MacBookPro11,4
    Type : Ordinateur portable
    Aucun écran tactile détecté

Processeur :
    Fabricant du CPU : GenuineIntel
    Marque du processeur : Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Famille du processeur : 0x6
    Modèle du processeur : 0x46
    Révision processeur : 0x1
    Type de processeur : 0x0
    Fréquence : 2200 Mhz
    8 processeurs logiques
    4 processeurs physiques
    HyperThreading : Pris en charge
    FCMOV : Non pris en charge
    SSE2 : Pris en charge
    SSE3 : Pris en charge
    SSSE3 : Pris en charge
    SSE4a : Non pris en charge
    SSE41 : Pris en charge
    SSE42 : Pris en charge
    AES : Pris en charge
    AVX : Pris en charge
    CMPXCHG16B : Pris en charge
    LAHF/SAHF : Pris en charge
    PrefetchW : Non pris en charge

Version du système d'exploitation :
    MacOS 10.11.6 (64 bits)

Carte graphique :
    Pilote : Intel Iris Pro
    Version du pilote : 1.2
    Version OpenGL : 2.1
    Profondeur de couleur du bureau : 32 bits par pixel
    Taux de rafraîchissement du moniteur : 0 Hz
    ID fabricant : 0x8086
    ID périphérique : 0xd26
    Révision : 0x8
    Nombre de moniteurs : 1
    Nombre de cartes vidéo logiques : 1
    Résolution de l'affichage principal : 1920 x 1200
    Résolution du bureau : 1920 x 1200
    Taille de l'affichage principal : 12.99" x 8.15" (15.31" diag)
 33.0cm x 20.7cm (38.9cm diag)
    Mémoire vidéo principale : 0 Mo

Mémoire :
    RAM : 16384 Mo

Divers :
    Langue de l'interface : Français
    Type de support : DVD
    Espace disque total disponible : 238208 Mo
    Plus grand bloc disponible sur le disque dur : 73452 Mo
    Casque VR : aucun détecté
```

Here is the most "popular" topic about it on the forum : https://steamcommunity.com/app/570/discussions/0/1644294896726172190/


Thanks for solving it.

**Comment by ohh-v2** [comment]
Not sure why this discussion is titled with [Linux], but yes, it's affecting me too: I have two Macs, both running up-to-date 10.11.6, and neither can run Dota... not for longer than a few seconds, anyway.

Dota 2 launches from Steam normally, and once started runs normally for a short time (on average about 30-45 seconds, once for a good 5 minutes, once about 3 seconds!). Then the game freezes, and a few seconds later the screen goes black and the Mac reboots. This happens regardless of what actions I'm taking in-game - it even happens if I do nothing at all, not touching the keyboard or mouse in any way. After rebooting, restarting Steam briefly shows a progress bar and says it's "Updating Steam" even though Steam had been up-to-date moments ago during the the previous launch.

This isn't happening with other Steam titles. Steam is up-to-date, and when I asked it to verify the Dota 2 datafiles it reported no errors.

(Quick note, regarding the suggestion above to simply update the OS: Updating to 10.13 would be nice, but for many of us our Macs won't upgrade past 10.11. Buying a couple of new Macs for the sake of one game - indeed, a game which still lists its system requirement as 10.9 - is more than a little hard to justify.)

**Comment by shoober420** [comment]
@ohh-v2 Because all you Mac users hijacked my issue. I’m the OP. Read the first post. My issue is completely different than everyone else. I of course have to pick a time to make this issue ticket when Mac is having a update regression.

**Comment by stephencarvalho** [comment]
Same Issue, since the update. Still experiencing the issue after 4 days also! Valve please help us out!
<details><summary>System Information</summary><p>

```
Computer Information:
    Manufacturer:  Apple
    Model:  iMac9,1
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM)2 Duo CPU     E8135  @ 2.66GHz
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  2660 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Unsupported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  NVIDIA GeForce 9400
    Driver Version:  1.2
    OpenGL Version: 2.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 0 Hz
    VendorID:  0x10de
    DeviceID:  0x867
    Revision:  0xb1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 16.97" x 10.59" (20.00" diag)
                                            43.1cm x 26.9cm (50.8cm diag)
    Primary VRAM: 0 MB

Memory:
    RAM:  3072 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  304297 Mb
    Largest Free Hard Disk Block:  181733 Mb
    VR Headset: None detected
```

</p></details>

<details><summary>ERROR INFORMATION</summary><p>

Anonymous UUID:       87A9EBDE-2D3B-2A09-A136-B369404845B3

Mon Jul 22 15:08:46 2019

*** Panic Report ***
Panic(CPU 0): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff8013f79c10, spinlock owner: 0xffffff80136914b8, current_thread: 0xffffff80136914b8, spinlock_owner_cpu: 0x0
RAX: 0xffffff801783bd30, RBX: 0x0000000000000000, RCX: 0xffffff801783bd30, RDX: 0xffffff801783bd30
RSP: 0xffffff807e99bec0, RBP: 0xffffff807e99bf70, RSI: 0x000000004f13580e, RDI: 0x0000000000000000
R8:  0xffffff807e99bf08, R9:  0xffffff8013f79c08, R10: 0xffffff801783bd68, R11: 0x0000011dbf33c060
R12: 0x0000000000000000, R13: 0xffffff801783bd20, R14: 0xffffff8013f79c08, R15: 0x0000000000000001
RFL: 0x0000000000000246, RIP: 0xffffff80085b5a60, CS:  0x0000000000000008, SS:  0x0000000000000000
Backtrace (CPU 0), Frame : Return Address
0xffffff80587e7f60 : 0xffffff800821e6a6 
0xffffff80587e7f80 : 0xffffff800821631e 
0xffffff80587e7fd0 : 0xffffff8008233ff9 
0xffffff807e99bf70 : 0xffffff80085b5eb4 
0xffffff807e99bfb0 : 0xffffff8008211867 

BSD process name corresponding to current thread: dota2

Mac OS version:
14F2511

Kernel version:
Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64
Kernel UUID: 9CB959EF-B0D4-3046-98E1-53536EA95A4F
Kernel slide:     0x0000000007e00000
Kernel text base: 0xffffff8008000000
__HIB  text base: 0xffffff8007f00000
System model name: iMac9,1 (Mac-F2218EA9)

System uptime in nanoseconds: 1227776822921
last loaded kext at 266889939601: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f8a912000, size 69632)
last unloaded kext at 329492949540: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f8a912000, size 61440)
loaded kexts:
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AGPM	110.19.6
com.apple.filesystems.autofs	3.0
com.apple.iokit.IOBluetoothSerialManager	4.3.6f4
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.driver.AppleHDA	272.18.3
com.apple.driver.AppleMikeyDriver	272.18.3
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f4
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleLPC	1.7.3
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.GeForceTesla	10.0.0
com.apple.driver.AppleBacklight	170.7.4
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.AppleIRController	327.5
com.apple.iokit.SCSITaskUserClient	3.7.5
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AppleFWOHCI	5.5.2
com.apple.driver.AppleUSBHub	705.4.2
com.apple.nvenet	2.0.22
com.apple.driver.AppleUSBOHCI	656.4.1
com.apple.driver.AirPort.Brcm4331	800.20.24
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.AppleGraphicsDeviceControl	3.10.25b1
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.DspFuncLib	272.18.3
com.apple.kext.OSvKernDSPLib	1.15
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f4
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.iokit.IOSurface	97.5
com.apple.iokit.IOBluetoothFamily	4.3.6f4
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.driver.AppleHDAController	272.18.3
com.apple.iokit.IOHDAFamily	272.18.3
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.0
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.nvidia.classic.NVDAResmanTesla	10.0.0
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.AppleUSBHIDKeyboard	176.2
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.iokit.IOSCSIMultimediaCommandsDevice	3.7.5
com.apple.iokit.IOBDStorageFamily	1.7
com.apple.iokit.IODVDStorageFamily	1.7.1
com.apple.iokit.IOCDStorageFamily	1.7.1
com.apple.iokit.IOAHCISerialATAPI	2.6.1
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.iokit.IOFireWireFamily	4.5.8
com.apple.iokit.IO80211Family	730.60
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.driver.NVSMU	2.2.9
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1
com.apple.kec.pthread	1
panic(cpu 1 caller 0xffffff80085b5445): "Spinlock acquisition timed out: lock=0xffffff8013f79c10, lock owner thread=0xffffff80136914b8, current_thread: 0xffffff80126f8c50, lock owner active on CPU 0x0, current owner: 0xffffff80136914b8"@/SourceCache/xnu/xnu-2782.70.3/osfmk/i386/locks_i386.c:378
Backtrace (CPU 1), Frame : Return Address
0xffffff807ea3bdb0 : 0xffffff800812ae01 
0xffffff807ea3be30 : 0xffffff80085b5445 
0xffffff807ea3bf20 : 0xffffff80085b34a4 
0xffffff807ea3bf50 : 0xffffff800864b636 
0xffffff807ea3bfb0 : 0xffffff8008234636 

BSD process name corresponding to current thread: dota2
Model: iMac9,1, BootROM IM91.008D.B08, 2 processors, Intel Core 2 Duo, 2.66 GHz, 3 GB, SMC 1.44f0
Graphics: NVIDIA GeForce 9400, NVIDIA GeForce 9400, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 1 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142323837334548312D4346382020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353737334448302D4348392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8E), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 4.3.6f4 17916, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: WDC WD3200AAJS-40H3A0, 320.07 GB
Serial ATA Device: HL-DT-ST DVDRW  GA11N
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: IR Receiver
USB Device: USB Optical Mouse
Thunderbolt Bus: 

</p></details>

**Comment by ardacam** [comment]
I think I'm having the same issue. Vulkan is causing system freeze and it happens lots of times in a single match. When I'm switching to opengl it's not fixing it I have to add `-vulkan_disable_steam_shader_cache` to launch options. I don't know how that helps since it's a vulkan only command as far as I know. I switched back to Windows to test it if it's a hardware problem on my side, but nothing happens on Windows. I can't provide any detailed logs since I'm on Windows now. Back in Linux I was using:

Gentoo Linux
Kernel 5.2.1
Mesa 19(vulkan enabled) with AMDGPU drivers
LLVM 7.1

My Specs:
CPU: AMD FX8350
GPU: AMD R9 380

It's really game breaking. I got 5 Low Prio matches because of a bug. My conduct summary lowered to 8k from 10k and none of them are my fault.

**Comment by shoober420** [comment]
Ok, I need to update this issue title.

**Comment by Hursofid** [comment]
Sooooo is there any fix already?

**Comment by sherb2k** [comment]
Apparently no fix. They're telling us to go talk to Apple. They will just tell you we cant upgrade. Should of told us this months ahead so we have time to prepare with a new pc.

**Comment by ohh-v2** [comment]
Hey, fellow Mac users:

In case you missed shoober420's posts, above, this thread was started for a Linux problem. The crashes with Dota on pre-10.13 OSX are now in a different bug report, #1642. If that's what you're here for, I'd suggest going to that thread and upvoting it there for visibility.

(Please read the group's [README](https://github.com/ValveSoftware/Dota-2) if you haven't already.)

**Comment by shoober420** [comment]
So I uninstalled the game, and deleted the DOTA 2 folder in the “steamapps/common” directory, and the game didn’t freeze my entire system on startup. There’s been several updates since I originally made this post, so I’m going to mark this as fixed.
