### ISSUE TITLE
[Linux] Crashes every game

### ISSUE THREAD

**Issue by mbfraga** [ValveSoftware/Dota-2#1778]
I am getting _very_ frequent crashes during games. I can't pinpoint it to any particular event, but some games it will crash up to 4 times. A lot of times the crash locks up my entire system, I can't even go to a different TTY...I have to reboot the computer.

[System Information](https://gist.github.com/mbfraga/5b0b4f3bafa8a3d84b20#file-system-information)
[stdout](https://gist.github.com/mbfraga/5b0b4f3bafa8a3d84b20#file-stdout) - this one was not from the same crash dump, but another crash
[Crash Dump](https://www.dropbox.com/s/7enu76inpclcwgy/crash_20150609125445_1.dmp?dl=0)

I don't know if this is related to [#1761](https://github.com/ValveSoftware/Dota-2/issues/1761)

additional info:
cpu: i5-4300m
I have played the game with primusrun (730m) and haswell graphics...I get crashes in both cases.

**Comment by iemesis** [comment]
I use this for when steam crashes in background(use your own display nummber):
sudo ionice -c 2 -n 0 nice -n -20 xterm -e 'su -l hk -s /bin/bash -c "DISPLAY=:0 steam steam://run/570"' && steam steam://SteamExit
Append additional parameters in when you click properties on game in steam(turns off vsync):
vblank_mode=0 primusrun %command% -console
You could try this since its value seems to be ralated to hangups, if you set it too high game wont start at all, i think default is around 5000.
sudo -s /bin/bash -c 'echo 2048 > /proc/sys/kernel/perf_event_max_sample_rate'

**Comment by mbfraga** [comment]
Thank you iemesis, that is good to know for the future.  Yesterday I installed Windows and Dota crashed as well there. I think this is hardware related, so I am closing this issue. I am having the laptop reparied, and if it still happens then, I will re-open.

That is still good information to have. Thanks!
