### ISSUE TITLE
No advance warning of 64bit requirement.

### ISSUE THREAD

**Issue by spacebiggles** [ValveSoftware/Dota-2#18]
The requirement for 64bit OS isn't clear when you go to download the DLC. When you try to start the game, there is no indication as to why it's not starting, you have to go manually look at the readme on github to get your disappointment.

**Comment by yaakov-h** [comment]
Is this Linux, or OS X?

**Comment by spacebiggles** [comment]
Linux, although reading the readme out front, I'd expect it's both.

**Comment by yaakov-h** [comment]
ah, OK. I only ask because OS X has been 64-bit-capable for so long that I'm not sure it's even possible to run Steam on a non-64-bit-capable Mac anymore.

**Comment by Vuccappella** [comment]
It's not.

**Comment by ArnaudAndre** [comment]
I think the important question is whether we will get 32-bit linux binaries later or if a 64 bit os will become a new requirement for dota2 on linux when reborn eventually leaves beta.

**Comment by davidw-valve** [comment]
We will try to add a note about the 64 bit requirement when downloading.

Going forward we are planning to only support Dota2 as a 64 bit application for OSX and for Linux.

**Comment by xpris** [comment]
Why not 32bit? If Windows build have both you can try also make it for Linux, we not have users second or thrid class. So, please make a 32 bit build.

**Comment by yaakov-h** [comment]
32-bit Linux doesn't show on the Steam Hardware Survey at all, if it did it would likely be less than 8% of the Linux playerbase and less than 0.05% of the overall playerbase. From an outside perspective it hardly seems worth it.

**Comment by Tele42** [comment]
@xpris In my opinion, it's unrealistic to make and maintain a 32 bit linux varient when there is are almost no 32 bit processors that are strong enough to run the game well anyway. At this point there is no benefit from running 32 bit distros on a 64 bit processor, due to greater TLC that has gone into the 64 bit kernel.

**Comment by davmac314** [comment]
> We will try to add a note about the 64 bit requirement when downloading.

Well, that hasn't happened, and it seems I just downloaded 6.7GB of nothing.

I understand that Linux users are a minority and that 32-bit Linux users are even more of a minority, but that's no reason to cause them this sort of problem. It's fine that you choose not to support 32-bit systems (I'd rather you did, but I can understand to some degree if you don't). But it's not cool to offer a huge download from within game, which then doesn't work.

**Comment by computerquip** [comment]
I dont know of any modern x86 processor that doesn't support amd64 that could run DotA. Why the urgent push for something like this?

**Comment by davmac314** [comment]
computerquip:

> I dont know of any modern x86 processor that doesn't support amd64 that could run DotA. Why the urgent push for something like this?

Urgent push? There are precisely two people here that have asked for a 32-bit version of Dota 2 Reborn (I'm not one of them). There are at least as many who've said they don't see the need, and there's a statement from a Valve employee that Dota 2 will be 64-bit going forwards.

The problem is not that Dota 2 Reborn isn't supported on 32-bit systems. The problem is that you have the option of downloading it on 32-bit systems and that it then doesn't work.

It's not just the matter of the processor. My processor will run 64-bit code just fine, but it needs a 64-bit operating system to do so. I'm running a 32-bit Linux system. Yes,. I could change my system and maybe I will at some point, but that's missing the point: that I've been duped into downloading 6.7GB of DLC that doesn't work on my system.

**Comment by yaakov-h** [comment]
How were you duped? According to #139, there's no in-game option, and the official instructions instructed gamers to go in-game to install it, not through the game properties in Steam.

**Comment by davmac314** [comment]
> How were you duped? According to #139, there's no in-game option

There was no in-game option previously, but there is now (it came in with some recent update; I couldn't tell you exactly when, because I've been away from the land of Dota for several days). When I use it, it downloads the DLC and says that I must restart Dota 2 and choose the "Play Dota 2 reborn" option. No such option is presented. As far as I can tell, the content that was downloaded contains only 64-bit executables.

**Comment by gdrewb-valve** [comment]
I've passed on the underlying request to the Steam team but this probably won't be addressed any time soon.
