### ISSUE TITLE
Window resolution is limited by previous fullscreen resolution

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#180]
This is a minor issue and there are workarounds, but anyway...

If you set the fullscreen resolution to be low (say 800x600) and then want to switch to windowed mode, proposed resolutions don't go higher than 800x600, even though your display allows higher res. 
To work around the issue, increase the fullscreen resolution.

This shouldn't bother many players since they are unlikely to switch to windowed mode at higher resolution. 

Tested on OS X 10.9.5.

**Comment by gdrewb-valve** [comment]
Windowed resolutions are limited to your desktop size to avoid creating windows larger than the desktop.  However if you have gone into a fullscreen mode that sets the desktop resolution so you see the limit you're hitting.  We could leave fullscreen mode temporarily but that would be quite annoying if you're just flicking through the options.  The better thing would be to remember what your true desktop resolution was but that's not as simple as it might seem.  We'll see if there's a reasonable way to improve this.

**Comment by jeanlain** [comment]
How do you limit the available resolutions for fullscreen in the first place? Why not just use the same list of resolutions for the borderless window?

**Comment by gdrewb-valve** [comment]
We limit fullscreen resolutions to what the system says are valid fullscreen resolutions.  Those resolutions may not all be meaningful for windows.  For example on a Retina machine your desktop may be at 1440x900 scaled, which will be reported as 1440x900.  The system can support 2880x1800 as a fullscreen resolution but you don't want to offer that as a window resolution because, with the scaling, it would not fit on the desktop.

**Comment by gdrewb-valve** [comment]
The 7/2 update should fix this, do you still see the issue?

**Comment by gdrewb-valve** [comment]
Closing for now.
