### ISSUE TITLE
[Linux] Borderless WIndowed mode minimizes when focus is lost

### ISSUE THREAD

**Issue by vyrus714** [ValveSoftware/Dota-2#182]
Brought up in #152, the 6/26 update changed the behavior to mimize the window when it looses focus. I believe it would be better to leave this up to the window manager, or at least add a menu option to toggle this.

**Comment by Tele42** [comment]
Historically, this has been controlled by the SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 environment variable.

**Comment by ArnaudAndre** [comment]
The borderless windowed is actually fine. You can test it by telling reborn to run in borderless windowed at a reduced resolution and it will behave sanely.

The problem is that when told to run borderless windowed at the native desktop resolution reborn will decide to run in fullscreen mode instead. Which, as I understand it, is just the way the fake fullscreen in linux source 2 is done. Except there is a big difference in how alt-tab is handled between fullscreen and borderless windowed. And I'm pretty sure easy alt-tab is the reason most people chose the borderless windows.

**Comment by bo0ohXae** [comment]
Not sure if this helps, but this worked as expected when reborn first came out for Linux, and broke a couple day later after one of the updates..  Really annoying as I have  monitors and as soon as I move the mouse to the other screen the game minimizes..

**Comment by chrylis** [comment]
Concur on all points: This worked in the initial release, it's broken in the new update, and the new behavior is unwanted.

**Comment by yaakov-h** [comment]
> The problem is that when told to run borderless windowed at the native desktop resolution reborn will decide to run in fullscreen mode instead.

This is likely caused by #22, which changed the behaviour (on OS X at least) to match what you're describing.

**Comment by vyrus714** [comment]
With the new fullscreen mode, the borderless window mode stays maximized on focus loss; issue resolved.

**Comment by chrylis** [comment]
This appears to work correctly.
