### ISSUE TITLE
Processing vulkan shaders everytime

### ISSUE THREAD

**Issue by safield** [ValveSoftware/Dota-2#1859]
Everytime I start dota2, it says "Processing Vulkan Shaders" which takes around 10 minutes to complete.

The best part of all of this is that my card does not even support vulkan, so why is it doing Vulkan specific stuff?

Also there is no export or copy button for system info AND it does not let me scroll while I select, so this is all I could grab for system info.

Operating System Version:
    Ubuntu 20.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.0-58-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20201203.1
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 580/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 390.138
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1080
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080

**Comment by kisak-valve** [comment]
Hello @safield, Vulkan shader pre-caching is handled by the Steam client, not Dota 2. Also, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7306.

For your video card, the best option is just to turn off the option entirely for the time being (Steam -> Settings -> Shader Pre-Caching -> uncheck `Enable Shader Pre-Caching`), at least until background processing of OpenGL shaders is an option.

Closing as a duplicate.
