### ISSUE TITLE
NSInternalInconsistencyException: NSWindow drag regions should only be invalidated on the Main Thread!

### ISSUE THREAD

**Issue by hhammoud01** [ValveSoftware/Dota-2#1894]
Original title: **Dota 2 crashing on macbook 13" (early 2015) retina display**

#### Your system information

* System information from steam: [find on gist here](https://gist.github.com/hhammoud01/d34f9808d858202e7401f19fbf6e66e7#file-sysinfo)
* Have you checked for system updates?: YES
* Are you using the latest stable video driver available for your system? YES
* Have you verified the game files?: YES

#### Please describe your issue in as much detail as possible:
Game not even launching, not from steam, not from command line as well. I saw in another thread that the person had the same issue which was solved by using "-gl" launch option. Did not work for me.
System is updated to latest version, as well as dota 2.

Here is the output when i run "dota.sh" from the command line: [here](https://gist.github.com/hhammoud01/3e30e3b06bf43359447fdd110e9d719e)

#### Steps for reproducing this issue:

1. Uninstalled dota 2, cleaned up all files
2. Uninstalled steam, cleaned up all files
3. Installed steam and dota 2. Same problem

**Comment by Turmfalke2** [comment]
I assume it has worked in the past/stopped working after a system upgrade?

I think the error you get when running it from dota.sh isn't the one actually preventing you from starting dota through steam, because if dota would create it's windows in wrong thread every mac user would be affected by that.

It is more likely that the game detects an issue, then tries to inform you of that using the SDL messages box, which tries to create the window from the wrong thread.

If you try to launch dota through steam using the steam ui, what exactly happens? Do you get a black screen for a moment?

After starting and failing to launch dota are there any files in /tmp/dumps/ or does /tmp/gameoverlayui.log exists?
I don't own a mac, so there is a bit of guess work involved on my end here.


https://wiki.libsdl.org/SDL_ShowMessageBox
>  This function should be called on the thread that created the parent window, or on the main thread if the messagebox has no parent.

Unless disabled in xcode, this is enforced at runtime when using AppKit.

**Comment by hhammoud01** [comment]
Issue solved! 
Apparently Xcode was not updated when I updated the system. I manually checked for updates for Xcode, updated it, restarted the macbook then it worked!

Thanks for the input.
