### ISSUE TITLE
Failed to create OpenGL context

### ISSUE THREAD

**Issue by MatthewRalston** [ValveSoftware/Dota-2#1910]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/MatthewRalston/bc923b6c24a65e5da21c90bbcbc99dd3
* Have you checked for system updates?: [Yes/No] Yes, this is what caused the issue.
* Are you using the latest stable video driver available for your system? [Yes/No] Yes, specifically, using extra/nvidia 460.67-4 from the Arch family via pacman/AUR package management.
* Have you verified the game files?: [Yes/No] No

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Hello, I'm not sure what caused this issue, but my RTX A6000 is suddenly unrecognized by Dota2 after a system upgrade `yay -Syu`

I am not sure if this is related to a driver upgrade from Nvidia, but suddenly my graphics card is not recognized, although it was working fine this morning.

#### Steps for reproducing this issue:

1. Use `yay -Syu` to trigger system upgrade on 3/28/21, and discover that the driver upgrade thrases your dota installation.
2. Reinstall Dota2 to verify that it is effected from the outside
3. Blame NVIDIA's drivers.

**Comment by kisak-valve** [comment]
Hello @MatthewRalston, your system information indicates you currently do not have a working video driver. The nVidia proprietary driver requires that the running kernel module, 32 bit userspace, and 64 bit userspace version have exactly the same version to work properly. Since you just updated your system's nVidia driver, it's likely that the nVidia kernel module loaded into memory is an older version, while the rest of the system is pointing to the newer version.

This is not a Dota 2 bug, all OpenGL and Vulkan accelerated applications are expected to fail in that situation. It is most easily resolved by rebooting your system.
