### ISSUE TITLE
MY SCREEN GOT BLACKED WHEN I PUT MY MOUSE ON SOMEONE OR A TOWER

### ISSUE THREAD

**Issue by varito1234** [ValveSoftware/Dota-2#1924]
WHEN I PUT MY MOUSE ON SOMEONE MY SCREEN GOT BLACKED I PLAY IN MAC AND ALL DAYS I GOT THIS BUG
<img width="1440" alt="Captura de pantalla 2021-04-18 a las 21 25 46" src="https://user-images.githubusercontent.com/82777919/115158201-59a8ce00-a08d-11eb-9482-0afdfbfa1ddb.png">
<img width="1440" alt="Captura de pantalla 2021-04-18 a las 21 25 49" src="https://user-images.githubusercontent.com/82777919/115158210-5dd4eb80-a08d-11eb-9860-8591b715f90c.png">
<img width="1440" alt="Captura de pantalla 2021-04-18 a las 21 25 51" src="https://user-images.githubusercontent.com/82777919/115158219-62010900-a08d-11eb-8260-e33c80d533c9.png">
<img width="1440" alt="Captura de pantalla 2021-04-18 a las 21 25 59" src="https://user-images.githubusercontent.com/82777919/115158223-67f6ea00-a08d-11eb-9401-738e8c2dd153.png">

**Comment by kisak-valve** [comment]
Hello @varito1234, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/328. Closing as a duplicate.

As a side note, please do not write in ALL CAPS when using this issue tracker. It is poor netiquette and not allowed in this issue tracker as noted at https://github.com/ValveSoftware/Dota-2#conduct.
