### ISSUE TITLE
shadow contours flicker

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/Dota-2#197]
With the 7/2 update, the contours of shadows may flicker. Turning shadows off and on doesn't fix the issue, but it seems that hiding and unhiding the game does it. 

OS X 10.9.5, radeon 7950.

**Comment by gdrewb-valve** [comment]
Similar to #55.

**Comment by jeanlain** [comment]
In my case it's only the contours that flicker. The shadows don't disappear entirely. I confirm that switching to another app and back temporarily removes the issue, which comes back a couple of minutes afterwards.

**Comment by jeanlain** [comment]
Also, unit shadows don't flicker. Only the shadows of vegetation.

**Comment by danginsburg** [comment]
@jeanlain Does adjusting the "Texture Quality" to Low make this issue go away?  I don't see this problem on my FirePro D500.  However, it's strange because I checked in a fix for the 7/2 update for this problem which occurred on NVIDIA.  The problem was with anisotropic filtering alpha tested objects rendered to the shadow map.  It only occurred when texture quality was set to high.

**Comment by danginsburg** [comment]
@jeanlain Ignore.  I've got this repro'd, thanks for the report.  Investigating.

**Comment by danginsburg** [comment]
I have found the issue and checked in a fix.  The fix will be part of the next update.

**Comment by jeanlain** [comment]
Excellent!
