### ISSUE TITLE
[OS X] Hosting a custom game will ask for permission randomly

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#211]
Hi,

As discussed at #141 , OS X will randomly ask for permission to use network when I am hosting 
a game which I think should only occur once for the entire session of the game and only revoke the
allow access to the network once Reborn closed.

With this thing pop up randomly its irritating, sometimes I need to go out of Reborn client just to click on
allow button.

**Comment by gdrewb-valve** [comment]
This isn't Mac-specific in that the game opens and closes listen sockets as necessary on all platforms.  It's particularly annoying on the Mac since the workaround for this on Windows doesn't apply and there can be multiple permission prompts but the fix, if any is made, will come from the larger team and won't be tracked here.
