### ISSUE TITLE
Vulkan Shaders every time the game is launched (On Windows).

### ISSUE THREAD

**Issue by layer07** [ValveSoftware/Dota-2#2180]
https://gist.github.com/layer07/249b38bf52bc0c651acc1cf68a3124fe

Every single time I open DOTA2 on Vulkan it gets stuck on the "Processing Vulkan Shaders". CPU Usage goes to 80-90%, takes forever to load, a lot of tiny processes are spawned by Steam and killed almost immediately. If I let it go for like an hour, it will open the game.

#### Steps for reproducing this issue:

1. Brand new install of windows.
2. Install DOTA 2 and enable Vulkan DLC
3. Switch to Vulkan, restart the game.

Just as a side note, the FPS could be better for DOTA, it is hard to achieve 240FPS and the game does look much smoother when running at 240Hz (on proper 240, 360hz) monitors. Even with the Core I9-13900K I still didn't get stable 200+ FPS. The GPU is heavily underused at 20-35%, so clearly a CPU bottleneck.

**Comment by kisak-valve** [comment]
Hello @layer07, on Linux, Steam's Vulkan shader pre-caching sub-component replays the shaders which have been seen with a game. This is then stored by the video driver in an on-disk shader cache so that those shaders do not need to be compiled on demand in the middle of gameplay, usually resulting in stuttering. Once this on-disk shader cache has been warmed up, subsequent runs of that process usually match what's been stored to the disk and it completes fairly quickly.

 It sounds like your video driver does not provide an on-disk shader cache, and you could look for a setting at `Steam` -> `Settings` -> `Shader Pre-Caching` -> uncheck `Enable Shader Pre-Caching` if it existing in the Steam for Windows client.

Regardless, this is an issue with the Steam for Windows client or your video driver, and not the Dota 2 client. Please report issues with the Steam for Windows client to https://help.steampowered.com/.

Closing as out of scope for this issue tracker.
