### ISSUE TITLE
Weird Killed by box when being killed by fountain

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#222]
![2015-07-07_00001](https://cloud.githubusercontent.com/assets/13085918/8566216/db2a8046-2586-11e5-904b-1f6b94c0c989.jpg)

**Comment by nixi-awoo** [comment]
This is an expected behaviour. The 'card' is set to show models of heroes. Since the fountain model is bigger it creates this effect. 

I seriously doubt this is a Linux / MAC only issue and can be tweaked by the main team. I might be wrong though. You can test it on windows if you have that installed.

**Comment by budimanjojo** [comment]
I don't know. I'll try to see how does it looks like in source 1 to make sure it isn't a bug

**Comment by gdrewb-valve** [comment]
Confirmed that this happens on Windows also.  I've passed this on to the larger team and it won't be tracked here.
