### ISSUE TITLE
Dota 2 not launching on linux

### ISSUE THREAD

**Issue by LibirSoft** [ValveSoftware/Dota-2#2222]
#### Your system information

* System information from steam https://gist.github.com/LibirSoft/47167765b246f41bba534bbdd35b4504
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

When i try to launch game it not launching. In logs i saw only one error ```src/tcmalloc.cc:390] Attempt to free invalid pointer: 0x5633dff2f570``` i try -vulkan -gl  launch options but event game logo not came

1. try to launch game

**Comment by kisak-valve** [comment]
Hello @LibirSoft, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2/issues/2026 / https://github.com/ValveSoftware/Dota-2-Vulkan/issues/420 / https://github.com/ValveSoftware/Dota-2-Vulkan/issues/414.

Please retest with mesa/RADV instead of AMDVLK.

Closing as a duplicate.

As a side note, it also looks like 32 bit OpenGL is not using your video card and falling back to llvmpipe to render Steam on your CPU, but that is unrelated to this issue.

**Comment by LibirSoft** [comment]
thx for helping me
