### ISSUE TITLE
[Linux] Freezing on scoreboard after Owerthrow match

### ISSUE THREAD

**Issue by VelorumS** [ValveSoftware/Dota-2#230]
It freezes almost every time (95%) after an Owerthrow match. After click on close button (sometimes without clicking).

Have to alt+tab and close it.

It wasn't like that on beta release. And I think, that yesterday it didn't freeze.

15.04
GTX760 4GiB
340.76-0ubuntu2

**Comment by AngryPenguinPL** [comment]
I have also the same issue.
Game freeze on scoreboard after owerthrow and also when I try find match for explain:

Match is found but some in player don;t accept it and game looking for another match and now 10 players accept and now game freeze. So I need rage quit game and restart it.

Also when game freeze, I can't anythink in game, I hear only the music.
I can't quit game, I can't also ALT+Tab and can't ALT+F4.
Only solution on my PC to quit game is press ALT+F4 and next go to tty CTRL+ALT + 1 and next back to tty2 , CTRL+ALT+F2 and now I see task manager with question (close dota2 process?) I press yes and game is now close. My DE is KDE4 (without compositons).

Two or 3 patch ago, this issue is not persist but now is very hindering the game.

My pc spec: https://gist.github.com/xpris/76419c07cb1748c43da5

**Comment by grasdaggel** [comment]
Solution for Linux:

Ctrl + Alt + T to open Terminal.

> $ ps fuxwww | grep dota

Go on and kill the third or fourth PID with kill PID

For example:
$ kill 3042
$ kill 3046

You then can restart.

**Comment by grasdaggel** [comment]
Disclaimer: doesnt work always. :(

**Comment by VelorumS** [comment]
Command to close:

killall -9 dota2

**Comment by supereddie** [comment]
I also had the freeze: the first time after only doing Demo Hero, quit Demo, and then trying to exit Dota 2; the second time winning 1 bot-match the scoreboard frooze.

In both instances I had to $kill the processes

**Comment by gdrewb-valve** [comment]
This doesn't appear to be a Mac/Linux issue as people on Windows are seeing it also, as are people with the main client.  The larger team mentioned that a possible fix was rolled out yesterday afternoon (July 18 at something like 17:00 US west coast time).

Are people still seeing this?

**Comment by VelorumS** [comment]
I hope that 17:00 US west coast time (whatever it is) was later than my first post.

I've stopped seeing this freeze from around that day.
