### ISSUE TITLE
Doesn't start on Fedora/Nobara with nvidia-vaapi-driver: libbz2.so.1.0: cannot open shared object file

### ISSUE THREAD

**Issue by arunstop** [ValveSoftware/Dota-2#2392]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [sysinfo @ gist](https://gist.github.com/arunstop/5a51cd19a9f34dfedfbd4134b9792bfa)
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Yesterday @ 11 July 2023, I was playing just fine, then today, I can't even start dota 

![2023-07-12_20-15](https://github.com/ValveSoftware/Dota-2/assets/10150211/03dccc74-d443-46e9-a591-ae72d3c89563)

I did no upgrade to my system. As seen here on my dnf history :

![image](https://github.com/ValveSoftware/Dota-2/assets/10150211/b8990cc9-466f-4dbc-921a-f81464e88f56)

Also I tried to run dota.sh file and this is the log it prints out :

[Dota.sh log @ gist](https://gist.github.com/arunstop/5a51cd19a9f34dfedfbd4134b9792bfa)

#### Steps for reproducing this issue:
-

**Comment by kisak-valve** [comment]
From https://github.com/ValveSoftware/Dota-2/issues/2392#issuecomment-1638617695


#### Workaround

Uninstall the `nvidia-vaapi-driver` package, both i686 and x86_64 versions.

---

Hello @arunstop, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Also, please take note that you linked the same gist twice.

**Comment by kisak-valve** [comment]
Can you check if the workaround noted at https://github.com/ValveSoftware/steam-for-linux/issues/9835 resolves this issue for you?

**Comment by arunstop** [comment]
Here's the gist of [diagnostic file](https://gist.github.com/arunstop/10f1b58f80f2fd3950d576b88c782780)

**Comment by arunstop** [comment]
As for that [workaround](https://github.com/ValveSoftware/steam-for-linux/issues/9835).

I am not sure how to actually install dota for the (latest - 1) version, also I don't know how this will help or not, but I got this [log](https://gist.github.com/arunstop/2c4715152cfd34994231013188ca3fc7) that probably indicate the dota was already running on sniper runtime.

**Comment by arunstop** [comment]
Update : I don't know how sufficient this workaround is and I also don't know if the dota team has fixed this issue, but after few steps of desperations I managed to play again by doing :

1. Opt in to Steam Beta client // Steam > Settings > Interface > Client Beta Participatio, select "Steam Beta Update"
2. Restart
3. Change dota's compatibilty to run on Proton 8.0-2 // Library > Select Dota 2 > Right click > Properties... > Compatibility > Check "Force the use of a specific Steam Play compatibility tool" > Select Proton 8.0-2

**Comment by manticore-projects** [comment]
> Update : I don't know how sufficient this workaround is and I also don't know if the dota team has fixed this issue, but after few steps of desperations I managed to play again by doing :
> 
>     1. Opt in to Steam Beta client // Steam > Settings > Interface > Client Beta Participatio, select "Steam Beta Update"
> 
>     2. Restart
> 
>     3. Change dota's compatibilty to run on Proton 8.0-2 // Library > Select Dota 2 > Right click > Properties... > Compatibility > Check "Force the use of a specific Steam Play compatibility tool" > Select Proton 8.0-2

I can confirm that this works, even without "Force Specific ...":
![image](https://github.com/ValveSoftware/Dota-2/assets/18080123/c4da213b-a960-491f-8197-6fa711f10fa6)

**Comment by kisak-valve** [comment]
Hello @arunstop, can you check if `Steam` -> `Settings` -> ` Compatibility` -> `Enable Steam Play for supported titles` is disabled, and if it is, then enable it and retest how the Linux native variant of Dota 2 behaves (not using Proton).

**Comment by smcv** [comment]
> Hello @arunstop, can you check if `Steam` -> `Settings` -> ` Compatibility` -> `Enable Steam Play for supported titles` is disabled, and if it is, then enable it and retest how the Linux native variant of Dota 2 behaves (not using Proton).

If that's successful, then the root cause is https://github.com/ValveSoftware/steam-for-linux/issues/9852.

**Comment by arunstop** [comment]
> Hello @arunstop, can you check if `Steam` -> `Settings` -> ` Compatibility` -> `Enable Steam Play for supported titles` is disabled, and if it is, then enable it and retest how the Linux native variant of Dota 2 behaves (not using Proton).

It is enabled. I just tested it again tho, running the native one, still got the same error as before.

**Comment by smcv** [comment]
@arunstop: Please try exiting from Steam, and running it from somewhere that you can see its log messages (in a terminal, or with its output going to the systemd journal, or something). This is partly as a way to get its output, and also partly as a way to eliminate https://github.com/ValveSoftware/steam-for-linux/issues/9835.

> It is enabled. I just tested it again tho, running the native one, still got the same error as before.

Please confirm what all these settings are:

* Steam -> Settings -> Compatibility -> Enable Steam Play for supported titles: on or off? (it should be on)
* Steam -> Settings -> Compatibility -> Enable Steam Play for all other titles: on or off?
* Dota 2's Properties -> Compatibility -> Force the use of a specific Steam Play compatibility tool: on or off? (it should be off)

Then try launching Dota 2. In Steam's output, there should be a long line that starts with `/bin/sh\0-c\0`. Copy/paste at least that line here. It should look something like this, but all one line:

```
/bin/sh\0-c\0
.../reaper SteamLaunch AppId=570 --
.../steam-launch-wrapper --
.../SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun --
.../dota 2 beta/game/dota.sh ...\0
```

If it looks like this, then that's not what we want, and a Steam client developer will need to look into why:

```
/bin/sh\0-c\0
.../reaper SteamLaunch AppId=570 --
.../steam-launch-wrapper --
.../dota 2 beta/game/dota.sh ...\0
```

If it looks like this, then that's also not what we want:

```
/bin/sh\0-c\0
.../reaper SteamLaunch AppId=570 --
.../steam-launch-wrapper --
.../SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun --
.../SteamLinuxRuntime/scout-on-soldier-entry-point-v2 --
.../dota 2 beta/game/dota.sh ...\0
```

**Comment by smcv** [comment]
(It is not yet clear whether what you're seeing is a Dota 2 bug or a Steam client bug, and part of what I'm trying to do here is to narrow down which one it is.)

**Comment by arunstop** [comment]
Sorry that my comment before was unclear, both of them were on, I never touched them.

![image](https://github.com/ValveSoftware/Dota-2/assets/10150211/7e340317-348a-468c-8d61-594fc9c27b0a)

1. Steam -> Settings -> Compatibility -> Enable Steam Play for supported titles: ON
2. Steam -> Settings -> Compatibility -> Enable Steam Play for all other titles: ON
3. Dota 2's Properties -> Compatibility -> Force the use of a specific Steam Play compatibility tool: ON

With this settings my Dota client runs well, But If I turn no 3 off, the error with `LoadSystemAndDependencies()` pops up.

**Comment by arunstop** [comment]
@smcv As you have instructed, I managed to print out the logs by running steam through the terminal. Here's the [gist](https://gist.github.com/arunstop/53d6b9f7daf5f3db46572f8789740d64) 

Also, the line that you are looking for is on line 69 (nice). Also those launch options don't affect things whether i put it on or not, the game won't start.

**Comment by smcv** [comment]
> Dota 2's Properties -> Compatibility -> Force the use of a specific Steam Play compatibility tool: ON

If you force use of Proton (any version), then Steam will download the Windows version of Dota 2 and run that. You can try using the Windows version as a workaround, but what we are trying to fix in this issue report is the case where:

1. Steam -> Settings -> Compatibility -> Enable Steam Play for supported titles: ON
2. Steam -> Settings -> Compatibility -> Enable Steam Play for all other titles: (shouldn't matter)
3. Dota 2's Properties -> Compatibility -> Force the use of a specific Steam Play compatibility tool: OFF

I think that is the configuration that you used to get the log in https://github.com/ValveSoftware/Dota-2/issues/2392#issuecomment-1636157673. Is that correct?

In your log, yes, lines 69 to 70 indicate that you are not experiencing https://github.com/ValveSoftware/steam-for-linux/issues/9835 or https://github.com/ValveSoftware/steam-for-linux/issues/9852, so that's good.

What do you mean by "those launch options"? The extra command-line options like `+map_enable_background_maps 1`? If yes, I hope those won't affect anything, but it's difficult to know that (I'm not a Dota 2 developer). To rule out any interference and make your setup as normal and boring as possible, it would be safest to test with the Launch Options set empty, and then try putting them back after we get this working.

I get this warning message:

> ` failed to dlopen "libpangoft2-1.0.so" error=libpangoft2-1.0.so: cannot open shared object file: No such file or directory`

even on a system where Dota 2 is working normally, so I don't think that is actually as bad as it looks.

But you also have this error message:

> `failed to dlopen "/home/arunstop/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpanorama_text_pango.so" error=libbz2.so.1.0: cannot open shared object file: No such file or directory`

and I think that might be more of a problem. This looks very similar to what @jn64 mentioned on #2390, so maybe you're both seeing the same issue.

I think the best next step here would be to collect a log from the container runtime framework, for which see https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md. The short version is: please run Steam with `STEAM_LINUX_RUNTIME_LOG=1`, and preferably also `STEAM_LINUX_RUNTIME_VERBOSE=1`. After trying to run Dota 2, you should find a log in `steamapps/common/SteamLinuxRuntime_sniper/var/slr-latest.log`: please attach it or upload it as a gist. This will tell us more about what is going on.

**Comment by smcv** [comment]
I think I might see what is happening here. The problem is that `libbz2.so.1.0` has two different names, `libbz2.so.1.0` and `libbz2.so.1`, seen on different operating systems. Usually its "real name" is `libbz2.so.1.0`, but in your case we're pulling in `libbz2.so.1` from your host operating system, Nobara Linux 37 (which is not something I'm familiar with, is it a variant of a more commonly-used OS?)

@arunstop or @kisak-valve, please could you change the title of this issue to mention the error message `libbz2.so.1.0: cannot open shared object file`? I think that's the key thing here, and having it in the title will stop people from confusing us with unrelated issues that have a similar symptom.

The log that I asked for in my previous comment will help us to understand how to solve this in the container runtime framework.

**Comment by jn64** [comment]
> Usually its "real name" is `libbz2.so.1.0`, but in your case we're pulling in
> `libbz2.so.1` from your host operating system, Nobara Linux 37 (which is not
> something I'm familiar with, is it a variant of a more commonly-used OS?)

Nobara is downstream of Fedora with gaming-focused patches. I'm using Fedora 38
so my problem may be the same as arunstop's.

I'll get my runtime log too.

**Comment by smcv** [comment]
Thanks, the more information the better! I don't have enough disk space on my test machines to install every possible OS variant, but I'll see whether I can reproduce this on Fedora, which would make things easier if it's also affected.

**Comment by AnttiRae** [comment]
Hey, I'm experiencing the same issue (`error=libbz2.so.1.0: cannot open shared object file: No such file or directory`). I'm running Fedora 38. Here is a steam log I got by running steam from the terminal: [gist](https://gist.github.com/AnttiRae/38e44365420ef05e05a4e9a975228466)  
Also here are my steam compatibility settings:
![image](https://github.com/ValveSoftware/Dota-2/assets/32770128/ac5cdfe1-1cd5-4c7b-9697-5f81bdb8277a)
In Dota 2 compatibility settings I have unchecked the "Force the use of...." setting

Hopefully this helps! I can provide more info if needed.

**Comment by jn64** [comment]
My verbose slr log attached.

Dota compat is off. Steam compat is on/on/Proton Experimental.

gh ate my attachment. https://github.com/ValveSoftware/Dota-2/files/12053105/slr-app570-t20230715T023025.log.gz

**Comment by arunstop** [comment]
@smcv 

> 1. Steam -> Settings -> Compatibility -> Enable Steam Play for supported titles: ON
> 2. Steam -> Settings -> Compatibility -> Enable Steam Play for all other titles: (shouldn't matter)
> 3. Dota 2's Properties -> Compatibility -> Force the use of a specific Steam Play compatibility tool: OFF
> 
> I think that is the configuration that you used to get the log in [#2392 (comment)](https://github.com/ValveSoftware/Dota-2/issues/2392#issuecomment-1636157673). Is that correct?

Yes that's correct.

**Comment by arunstop** [comment]
Also for the logs : https://gist.github.com/arunstop/668561ac4dc3e696eb3e0a77f18d0aad

**Comment by smcv** [comment]
This is probably a Steam Runtime bug rather than a Dota 2 bug, but let's leave it in this issue tracker instead of transferring it to https://github.com/ValveSoftware/steam-runtime, to avoid people reporting duplicates of it against Dota 2.

The problem appears to be:

* in Fedora, the canonical SONAME of libbz2 is `libbz2.so.1`, possibly with a compatibility symlink `libbz2.so.1 -> libbz2.so.1.0`
* in the Debian version that our container is based on, the canonical SONAME of libbz2 is `libbz2.so.1.0`, with a compatibility symlink `libbz2.so.1 -> libbz2.so.1.0`
* the container runtime framework detects that your OS's `libbz2.so.1` is required by your graphics driver stack for whatever reason
* so we make a symlink to it in the container's `overrides/lib/x86_64-linux-gnu/libbz2.so.1` (possibly also `libbz2.so.1.0` in the same directory, I can't see that from the log)
* and we remove the container runtime's `usr/lib/x86_64-linux-gnu/libbz2.so.1.0` and `usr/lib/x86_64-linux-gnu/libbz2.so.1` to make way for it
* but the compatibility symlink `overrides/lib/x86_64-linux-gnu/aliases/libbz2.so.1` still points to `usr/lib/x86_64-linux-gnu/libbz2.so.1.0` which you don't have
* so loading fails

This might not have caused an observable problem in previous uses of the container runtime (mostly Proton) because Proton might not need `libbz2.so.1.0`, but Dota 2 does. Or, your graphics driver requiring `libbz2.so.1` might be a recent change in Fedora, or the canonical SONAME being `libbz2.so.1` might be a recent change in Fedora.

**Comment by jn64** [comment]
Just confirming some details:

> in Fedora, the canonical SONAME of libbz2 is `libbz2.so.1`, possibly with a compatibility symlink `libbz2.so.1 -> libbz2.so.1.0`

This is on Fedora 38:

```sh
$ ls -l /usr/*/libbz2.*
lrwxrwxrwx. 1 root root    15 Jan 18 08:00 /usr/lib64/libbz2.so.1 -> libbz2.so.1.0.8
-rwxr-xr-x. 1 root root 81008 Jan 18 08:00 /usr/lib64/libbz2.so.1.0.8
lrwxrwxrwx. 1 root root    15 Jan 18 08:00 /usr/lib/libbz2.so.1 -> libbz2.so.1.0.8
-rwxr-xr-x. 1 root root 76224 Jan 18 08:00 /usr/lib/libbz2.so.1.0.8
```

> or the canonical SONAME being libbz2.so.1 might be a recent change in Fedora

As far as I can tell, the bzip2-libs package hasn't changed in ~2 years (except for rebuilds for each Fedora release).

**Comment by smcv** [comment]
This issue seems likely to be specific to Fedora and its derivatives. Fedora has [a patch](https://src.fedoraproject.org/rpms/bzip2/blob/rawhide/f/bzip2-saneso.patch) to change the library's "official" SONAME from `libbz2.so.1.0` to `libbz2.so.1`, diverging from the SONAME used upstream. Other distributions like Debian and Arch use the upstream SONAME `libbz2.so.1.0`, with a symlink `libbz2.so.1` provided for binary compatibility with Fedora.

The container runtime framework (pressure-vessel) should be able to cope with both, because it has the concept of a SONAME being an "alias" for another SONAME; but unfortunately the aliases feature currently only works one way round. We provide `libbz2.so.1` on systems like Debian where `libbz2.so.1.0` is treated as canonical, but we don't yet provide `libbz2.so.1.0` on systems like Fedora where `libbz2.so.1` is treated as canonical. I'm looking into fixing that.

**Comment by smcv** [comment]
> This might not have caused an observable problem in previous uses of the container runtime (mostly Proton) because Proton might not need libbz2.so.1.0, but Dota 2 does

This seems to be true: Proton 8.0 doesn't seem to contain references to libbz2.so.1.0, and most previous uses of the container runtime framework have been for Proton rather than for native Linux games (other than a few early adopters like Retroarch and Endless Sky).

> your graphics driver requiring libbz2.so.1 might be a recent change in Fedora

For what it's worth, I can't reproduce this issue on a Fedora 37 system with the proprietary Nvidia graphics driver. Could this have been triggered by a Fedora 38 change that might have been backported into Nobara Linux 37? Or the issue might be specific to systems with Mesa graphics (unfortunately my only existing Fedora installation is on Nvidia).

I'll try on 38, but this could take a while.

**Comment by jn64** [comment]
> Or the issue might be specific to systems with Mesa graphics (unfortunately my
> only existing Fedora installation is on Nvidia).

I'm using Nvidia on F38, with proprietary drivers from RPM Fusion.

**Comment by smcv** [comment]
> I'm using Nvidia on F38, with proprietary drivers from RPM Fusion.

OK, good, so if jn64 can reproduce this, in principle I should be able to as well (eventually, when dnf has finished upgrading 4214 packages). However, while I'm waiting for real test hardware to upgrade, I tried a F38 live-image system in a VM (presumably with Mesa software rendering) and that doesn't seem to exhibit this issue either; so there might be something your systems have in common beyond just the operating system that is triggering this for you but not for me.

To avoid having to install all of Steam, the simpler reproducer I'm using in the VM is to download https://repo.steampowered.com/steamrt-images-sniper/snapshots/latest-container-runtime-public-beta/steam-container-runtime-complete.tar.gz, unpack it, and run `steam-container-runtime/depot/run --verbose --devel -- bash -i` to explore the container interactively. This is not a 100% complete container, because my test VM doesn't have full 32-bit support, but it's good enough to check how libbz2 is being handled.

The way this stuff is meant to work is that the new version of Dota 2 runs in a container, and it will use libraries from the 'sniper' container runtime as much as possible; but we take the graphics drivers and Vulkan layers from the host system, and for every library that those depend on, we have to use the version of that library from the host system if it is newer than or equal to the version from sniper. To see the same behaviour that's in your logs, there must be something in your graphics drivers (or Vulkan layers or something else that we look at) that depends on libbz2.so.1, and it must be something that isn't present in my test VM.

In arunstop's log I noticed `obs_vkcapture_32.json` and `obs_vkcapture_64.json` (presumably the OBS Studio screencasting/streaming framework?), which could be a potential trigger because OBS Studio has non-trivial dependencies; but jn64 doesn't seem to have that layer, so that's probably not it.

You both have MangoHud and vkBasalt, so those are another potential trigger; but I don't see any obvious reason why either of those would pull in libbz2 (and adding them to my test VM doesn't have any effect).

Is there anything that you already know is unusual about your system, that could be a starting point for me to look at?

**Comment by smcv** [comment]
@AnttiRae: please could you try to get a log similar to https://github.com/ValveSoftware/Dota-2/issues/2392#issuecomment-1636677803 by following the instructions in the last paragraph of https://github.com/ValveSoftware/Dota-2/issues/2392#issuecomment-1636176405, and send it as an attachment or gist? That would give me another data point to compare with what jn64 and arunstop have said, and hopefully get me one step closer to being able to replicate the bug myself.

**Comment by smcv** [comment]
Another thing that would be useful is if @jn64, @arunstop or @AnttiRae can get another log, this time with `CAPSULE_DEBUG=tools STEAM_LINUX_RUNTIME_LOG=1 STEAM_LINUX_RUNTIME_VERBOSE=1` in the environment. It should contain some extra lines with prefixes like `capture_one:`, and those will tell me what is pulling in libbz2.

**Comment by AnttiRae** [comment]
Hi, I ran `STEAM_LINUX_RUNTIME_LOG=1 STEAM_LINUX_RUNTIME_VERBOSE=1 steam` from my terminal and launched Dota 2. Here's the log as a [gist](https://gist.github.com/AnttiRae/d7c6f7231977d9a5970b00a3b1a9b34e)

I also ran steam with `CAPSULE_DEBUG=tools STEAM_LINUX_RUNTIME_LOG=1 STEAM_LINUX_RUNTIME_VERBOSE=1 steam` Heres the log from that as another [gist](https://gist.github.com/AnttiRae/59f88860335b778428b0dc589c8dd70a)

Hopefully this helps.

**Comment by jn64** [comment]
Here's my log with CAPSULE_DEBUG=tools: [slr-app570-t20230718T001839.log.gz](https://github.com/ValveSoftware/Dota-2/files/12071735/slr-app570-t20230718T001839.log.gz)

<details>
<summary>Excerpt from log</summary>

```
$ grep -C5 'capture.*bz2' slr-app570-t20230718T001839.log
library_cmp_by_name:Comparing liblzma.so.5 "liblzma.so.5.2.5" from "/proc/self/fd/19" with "liblzma.so.5.4.1" from "/"
capture_one:Choosing liblzma.so.5 from provider
capture_one:Link target initially: "/usr/lib64/liblzma.so.5.4.1"
capture_one:Remapping "/usr/" to "/run/host/usr/" in "/usr/lib64/liblzma.so.5.4.1"
capture_one:Creating symlink /proc/self/fd/26/lib/x86_64-linux-gnu/liblzma.so.5 -> /run/host/usr/lib64/liblzma.so.5.4.1
capture_one:libbz2.so.1 is not in the container
capture_one:Link target initially: "/usr/lib64/libbz2.so.1.0.8"
capture_one:Remapping "/usr/" to "/run/host/usr/" in "/usr/lib64/libbz2.so.1.0.8"
capture_one:Creating symlink /proc/self/fd/26/lib/x86_64-linux-gnu/libbz2.so.1 -> /run/host/usr/lib64/libbz2.so.1.0.8
00:18:40.174789: pressure-vessel-wrap[21355]: D: -> 
00:18:40.174832: pressure-vessel-wrap[21355]: N: Profiling: end (real 0.2s, user 0.1s, sys 0.1s): Main capsule-capture-libs call
00:18:40.174907: pressure-vessel-wrap[21355]: N: Profiling: start: glibc
00:18:40.174936: pressure-vessel-wrap[21355]: D: Making provider's ld.so visible in container
00:18:40.174989: pressure-vessel-wrap[21355]: D: Provider path: /lib64/ld-linux-x86-64.so.2 -> usr/lib64/ld-linux-x86-64.so.2
```

</details>

---

> You both have MangoHud and vkBasalt, so those are another potential trigger; but I don't see any obvious reason why either of those would pull in libbz2 (and adding them to my test VM doesn't have any effect).
>
> Is there anything that you already know is unusual about your system, that could be a starting point for me to look at?

I have MangoHud and vkBasalt installed, but I've made sure they're not running, and the Dota launch options in Steam is blank. GameMode is also installed but not running. No OBS or anything else game/graphics related of this nature (addons/overlays/background).

My system is quite normal—F38, X11, Xfce, Nvidia 1050 Ti with proprietary drivers. Steam client is non-beta.

My Steam install is on a bind mount but that's unrelated.

**Comment by smcv** [comment]
Oh no. It looks like the root cause for this is the VA-API driver for the proprietary NVIDIA stack, possibly [this one](https://github.com/elFarto/nvidia-vaapi-driver):

```
capture_pattern:only-dependencies:if-exists:if-same-abi:path:/usr/lib64/dri/nvidia_drv_video.so
...
capture_one:libgstcodecparsers-1.0.so.0 is not in the container
```

and this pulls in several very non-trivial dependencies:

* the core GStreamer libraries
* all of GLib
* libdw from elfutils, which in turn pulls in libbz2 (and liblzma)

The model in which we use all of the host system's graphics drivers and their recursive dependencies is fine when graphics drivers limit themselves to depending on ubiquitous low-level libraries, but it breaks down if a graphics driver is going to start pulling in things like GStreamer (because the more we take from the host system, the more likely it is for something to go wrong).

In the short term, you can probably work around this by uninstalling the `nvidia-vaapi-driver` package (both i686 and x86_64 versions) if nothing else critical on your system depends on it.

Also in the short term, I've installed `nvidia-vaapi-driver` on my F38 test system, and hopefully it will help me to reproduce the bug so I can give pressure-vessel better handling for libbz2.

In the longer term, we might have to special-case this driver to be excluded from container setup, meaning the NVIDIA proprietary stack will have video codec acceleration for applications that use VDPAU, but not for applications that only use VA-API.

cc @TTimo

**Comment by smcv** [comment]
> Also in the short term, I've installed nvidia-vaapi-driver on my F38 test system, and hopefully it will help me to reproduce the bug so I can give pressure-vessel better handling for libbz2.

Yes, I can now get to the same failure. Thanks for the logs, everyone! Now that I can reproduce this myself, I don't need any more logs from affected systems.

**Comment by smcv** [comment]
@arunstop or @kisak-valve, it might be useful to retitle this to something like:

```
doesn't start on Fedora/Nobara with nvidia-vaapi-driver: libbz2.so.1.0: cannot open shared object file
```

**Comment by jn64** [comment]
Aha. I don't actually use `nvidia-vaapi-driver`; happy to remove it. I confirm removing it resolves this issue with Steam/Dota.

(offtopic) is there _any_ chance this could be related to other Fedora users reporting that Steam takes a long time (5mins+) to start? Possible interaction with the Steam client options for hardware acceleration?

**Comment by smcv** [comment]
> is there any chance this could be related to other Fedora users reporting that Steam takes a long time (5mins+) to start?

Anything is possible, but that doesn't seem particularly likely: Steam doesn't do anything with the container-runtime environment during its own startup, and nvidia-vaapi-driver having relatively "heavy" dependencies shouldn't cause that sort of delay. Steam is starting promptly for me on my F38 test system, similar to what I see in Ubuntu on the same hardware, even with nvidia-vaapi-driver installed (although admittedly I only have the 64-bit version right now, so that I can compare both code paths by looking at both architectures).

Please (ask the affected users to) report this to https://github.com/ValveSoftware/steam-for-linux/ as a separate issue if it isn't already there, with as much log/etc. information as possible.

**Comment by smcv** [comment]
@kisak-valve: Also perhaps useful if you can edit the original bug report to append:

#### Workaround

Uninstall the `nvidia-vaapi-driver` package, both i686 and x86_64 versions.

**Comment by smcv** [comment]
I have two possible solutions for this in the container runtime framework. Either one should be enough to avoid this, but for best robustness, my current plan is to do both.

If you're comfortable with testing unreviewed prerelease software, please undo workarounds (for instance reinstall `nvidia-vaapi-driver` if you had removed it), then try replacing `steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel` with the result of unpacking one of these. To return to the production version of pressure-vessel, [verify integrity](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB) on the "Steam Linux Runtime - sniper" tool in your Steam library.

~~This version fixes the handling of aliases like `libbz2.so.1.0`/`libbz2.so.1`: https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/jobs/282640/artifacts/raw/_build/production/pressure-vessel-bin.tar.gz (from [!573](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/573))~~

~~This version avoids picking up `nvidia-vaapi-driver` at all, ensuring it can't trigger issues like this: https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/jobs/282695/artifacts/raw/_build/production/pressure-vessel-bin.tar.gz (from [!574](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/574))~~

[edit: Both changes are now included in <https://repo.steampowered.com/pressure-vessel/snapshots/0.20230718.0/pressure-vessel-bin.tar.gz>]

~~If you would prefer to wait for an official solution, the next beta of the "Steam Linux Runtime - sniper" compatibility tool will hopefully include one or both of these changes, and will be re-released as stable after more testing.~~ [edit: This was [released as a beta](https://github.com/ValveSoftware/Dota-2/issues/2392#issuecomment-1658325784).]

The procedure for using beta versions is [the same as documented here](https://help.steampowered.com/en/faqs/view/5A86-0DF4-C59E-8C4A), but instead of the Properties of CS:GO, you'd go into the Properties of "Steam Linux Runtime - sniper".

**Comment by jn64** [comment]
I tested both versions with nvidia-vaapi-driver installed,
and they both resolve the issue (Dota launches).

**Comment by arunstop** [comment]
Glad to know that the fix will come soon! I don't think I will touch that `nvidia-vaapi-driver` at all. Don't want to break my system (who knows what'll happen) and Dota x Proton is working very well on my end, also thanks to @jn64 for testing that out :ok_hand:

**Comment by jn64** [comment]
> I don't think I will touch that `nvidia-vaapi-driver` at all.

nvidia-vaapi-driver is not part of a default Fedora Workstation install
(not sure about Nobara). It's only used for hardware acceleration in Firefox,
which requires some additional setup[1] including disabling the RDD sandbox
(RDD is the process used to decode media in Firefox).

If you don't have the necessary setup, or don't use Firefox to watch videos
with hardware acceleration on Nvidia GPU, you aren't using nvidia-vaapi-driver.
(I use mpv to watch YouTube videos; mpv uses nvdev directly with
`--hwdec=auto-safe` and doesn't need nvidia-vaapi-driver.)

Do you use a Nvidia GPU in the first place? I didn't see it mentioned.

You could ask in Nobara's support channels if you have any doubts about
removing it. I don't think there's any risk but who knows what Nobara does.

[1] https://github.com/elFarto/nvidia-vaapi-driver/#firefox

**Comment by arunstop** [comment]
No, I dont' have NVIDIA hardware, but.... I think Nobara has support for NVIDIA out of the box, I think even if I uninstall it, it will come back after a system update.

**Comment by smcv** [comment]
> the next beta of the "Steam Linux Runtime - sniper" compatibility tool will hopefully include [...] these changes, and will be re-released as stable after more testing.

A beta runtime with this change has now been released. Switching to the `client_beta` branch of "Steam Linux Runtime - sniper" should make Dota 2 launch successfully on Fedora/Nobara, even if `nvidia-vaapi-driver` is installed. The fixed version can be identified by seeing `pressure-vessel 0.20230718.0` (or later) in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`.

If you are affected by this issue, please try the beta, which should fix it. Please report any regressions to <https://github.com/ValveSoftware/steam-runtime/issues>. The procedure for using beta versions is [the same as documented here](https://help.steampowered.com/en/faqs/view/5A86-0DF4-C59E-8C4A), but instead of the Properties of CS:GO, you'd go into the Properties of "Steam Linux Runtime - sniper".

The updated runtime will be copied to the default (non-beta) branch after it has had more testing.

For gamers who are comfortable with running beta software and able to report bugs with useful logs on behalf of the Fedora community, it would be helpful to keep running the beta even after this is fixed. It usually works well, and I run it on my own (Debian-based) gaming system when I'm not at work. If you see regressions with the beta, please report them to <https://github.com/ValveSoftware/steam-runtime/issues>, then work around them by turning off the beta and going back to the stable branch. The more representatives of different distros we have using the beta, the fewer bugs will get as far as the stable branch!

**Comment by GloriousEggroll** [comment]
> Replying to https://github.com/ValveSoftware/Dota-2/issues/2392#issuecomment-1638827131

Thanks for working around this so that users don't have to uninstall the nvidia-vaapi-driver packages. I've validated on my AMD system that with that package installed i can reproduce the issue, and changing 'steam linux runtime - sniper' to client_beta resolves the issue on my side without needing to remove the package.

As for the Nobara side currently we have the nvidia-vaapi-driver package as part of our codec installer, which isn't correct since not everyone uses Nvidia. I'll get it moved over as part of the nvidia driver installation instead, that way it's not on everyone's system on Nobara moving forward.

**Comment by GloriousEggroll** [comment]
> No, I dont' have NVIDIA hardware, but.... I think Nobara has support for NVIDIA out of the box, I think even if I uninstall it, it will come back after a system update.

It's part of the codec installer, you can remove the package and it won't come back. The only thing the codec installer mainly checks for is ffmpeg. If ffmpeg is missing it will ask you to install codecs.

As additionally noted I'll remove the nvidia-vaapi-driver package from the codec installer and move it to the nvidia installer instead to avoid this issue in the future.

**Comment by smcv** [comment]
> The updated runtime will be copied to the default (non-beta) branch after it has had more testing.

The default branch now has sniper depot 0.20230718.55074 (Steampipe build ID 11828592) which resolves this issue.
