### ISSUE TITLE
Game crashes with VK_ERROR_OUT_OF_HOST_MEMORY in vkCreateDescriptorSetLayout

### ISSUE THREAD

**Issue by vossnick** [ValveSoftware/Dota-2#2402]
Every time I start the game it crashes.  I tried from the command line so I could get details which I will include in a link.
My system is up to date.
I have reinstalled the game.  I have verified the game files.
Video drivers are up to date.

System Info:
https://gist.github.com/vossnick/65c484f8db30c0f645c4f96a62686fbe

Launch and crash:
https://gist.github.com/vossnick/218c1beb10620a557e93fcc4356ae349

git will not allow me to upload the .dmp file.

**Comment by kisak-valve** [comment]
Hello @vossnick, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by vossnick** [comment]
Steam Runtime Diagnostics:
https://gist.github.com/vossnick/5b9bee2570aee111d023e08703c36f38

**Comment by smcv** [comment]
> `voss@vossLinux:~/.steam/debian-installation/steamapps/common/dota 2 beta/game$ ./dota.sh`

Launching Dota 2 from outside Steam, without using the Steam Runtime 3 'sniper' container runtime, is not a supported way to run it, so the log from https://gist.github.com/vossnick/218c1beb10620a557e93fcc4356ae349 does not necessarily reflect what happens when you launch it from inside Steam.

There are two main things that could be going wrong here:

1. Dota 2 being launched in the wrong environment (not using the Steam Linux Runtime 3 'sniper' container runtime)
2. Dota 2 being launched in the correct Steam Linux Runtime 3 'sniper' environment, but it doesn't work

The first step here is to check whether (1.) is the problem. If it is, we need to solve that first. If it is not, we can move on to (2.).

Please try running Steam from a terminal (or with its output sent to a log file, or with its output sent to the systemd Journal) with the `STEAM_LINUX_RUNTIME_LOG` environment variable set to `1`, for example:

```
STEAM_LINUX_RUNTIME_LOG=1 steam
```

In Steam's output, you should see that it is running a command that looks something like this:

```
/bin/sh\0-c\0
.../reaper SteamLaunch AppId=570 --
.../steam-launch-wrapper --
.../SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun --
.../dota 2 beta/game/dota.sh +engine_experimental_drop_frame_ticks 1 +@panorama_min_comp_layer_dimension 0 -prewarm_panorama
\0
```

(It will be logged as one very long line, and ... will be replaced by paths to your Steam installation and Steam library - I've broken it into shorter lines and abbreviated the paths here to make it more readable.)

If you do not see a command that looks like that, then please see https://github.com/ValveSoftware/Dota-2/issues/2404#issuecomment-1653541234 for some possible causes.

If you *do* see a command that looks like that, then the next step is to investigate why Dota 2 isn't launching successfully. Because of the `STEAM_LINUX_RUNTIME_LOG=1` variable, Dota 2's output should be redirected into a log file, with a symbolic link `steamapps/common/SteamLinuxRuntime_sniper/var/slr-latest.log` pointing to it, along with debugging information about the container runtime. Please attach that log file.

**Comment by smcv** [comment]
From your log, this looks suspicious:

```
39(3.979882):  ERROR! VK call failed! result = VK_ERROR_OUT_OF_HOST_MEMORY ( vkCreateDescriptorSetLayout( m_pDeviceVulkan, &descriptorSetLayoutCreateInfo, NULL, &pipelineLayout.m_ppDescriptorSetLayouts[ nDescriptorSet ] ) )
```

If the same thing can be seen in `slr-latest.log` then that is probably the root cause of your crash, and someone who is better at Vulkan than me should take over investigating this.

**Comment by smcv** [comment]
@kisak-valve, it might be helpful to edit the title to include something like `VK_ERROR_OUT_OF_HOST_MEMORY in vkCreateDescriptorSetLayout`, to avoid getting mixed up with other issues that could be described as "game crashes before launching" but are unrelated to this one.

**Comment by smcv** [comment]
> From your log, this looks suspicious:

#2388 looks rather similar, possibly these issues are duplicates of each other.

**Comment by vossnick** [comment]
I tried a varity of things, but this fixed the issue.  Starts and plays fine.
-vulkan_disable_graphics_pipeline_library

**Comment by vossnick** [comment]
Odd that this came out of the blue after plaing for a year or so.  But it is working great now.  Thank you for all the help!
