### ISSUE TITLE
Dota cant start after some updates on ubuntu (23.04)

### ISSUE THREAD

**Issue by aveSwamp** [ValveSoftware/Dota-2#2431]
System information: https://gist.github.com/aveSwamp/0e0727d872f5aaabb519433065056f3c
Checked system updates: [YES]
Using latest stable video driver: [YES]
Verified game files: [YES]
Problem description: https://gist.github.com/aveSwamp/69ec7d0e1609fb467f94875e2f5e7359

**Comment by kisak-valve** [comment]
Hello @aveSwamp, the mesa/Vulkan drivers provided by the Oibaf PPA are currently broken. This issue has been reported a couple times over at https://gitlab.freedesktop.org/mesa/mesa/-/issues/9585 / https://gitlab.freedesktop.org/mesa/mesa/-/issues/9692 and needs to be fixed in the video driver.

You should be able to confirm that assessment by going to Steam's Runtime Diagnostics (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and looking at the x11/Vulkan sections.

If you're able to reproduce this issue after switching to a different build of mesa, let me know and we can ponder this further.
