### ISSUE TITLE
[OS X Yosemite] Intel HD5000 low fps

### ISSUE THREAD

**Issue by rained23** [ValveSoftware/Dota-2#245]
Hi, the performance of Intel HD5000 are so bad but playable, its around 20 - 35 fps on all turned off
and lowest setting. Playing custom game like Green TD Reborn, when spawn so much monster will
make it as low as 1 - 6 fps.

The following is my Macbook Air specs

![image](https://cloud.githubusercontent.com/assets/907309/8803438/7eba0bec-2ff9-11e5-955a-4799d145ff08.png)

**Comment by danginsburg** [comment]
@rained23 Please post your system specifications.

**Comment by rained23** [comment]
@danginsburg updated.

**Comment by danginsburg** [comment]
I have spent a lot of time looking at perf on Haswell on OSX.  I have a fix for one of the big performance issues.  We have a vertex shader that outputs more than 8 interpolators for drawing the world geometry.  It turns out that the HD5000 driver is punting to SW to execute this vertex shader.  It is unclear to me why this is the case because the hardware is capable of >8 interpolators so it appears to just be a driver issue.  That being said, I've worked around the driver issue by reducing the number of interpolators.  The fix will be in the next update.

**Comment by dmpanch** [comment]
The same here: still 30 FPS on the same MacbookAir.

**Comment by chrylis** [comment]
Not sure how much is shared across the OS X and Linux versions, but sounds just like #201.

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101.  Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
