### ISSUE TITLE
map bug help!!!

### ISSUE THREAD

**Issue by XXXbxuan** [ValveSoftware/Dota-2#2452]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

#### Steps for reproducing this issue:

1. my map of the floor is blue
2. i dont have version(dont have bright or dark of floor)
3. this is the example
![Screenshot (23)](https://github.com/ValveSoftware/Dota-2/assets/143816068/d9f7a039-040c-4486-9503-56efe8e6070e)

![Screenshot (25)](https://github.com/ValveSoftware/Dota-2/assets/143816068/e68f4e48-6498-4b83-afc7-464035d80a31)

**Comment by 4erepaxen** [comment]
#2452

**Comment by danginsburg** [comment]
You did not provide any system information.  There is a  bug with multi GPU systems on Windows that has this symptom that will be fixed in today's release along with a macOS bug on Intel GPUs that will also be fixed in the next update.  If your bug is something different, please refile including the requested system information.
