### ISSUE TITLE
Cannot launch Dota2 with Fossilize WARNs and core dumped

### ISSUE THREAD

**Issue by BrikeX** [ValveSoftware/Dota-2#2497]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/BrikeX/8991482439be911984ef8170bfe8dd58): 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
I installed Steam from Ubuntu 18.04 Software Center. After downloading Dota2, it cannot be launched correctly. Some error msgs are shown in the terminal:

Fossilize WARN: Referenced Pipeline layout 18e378211faa8917, but it does not exist.
This can be expected when replaying an archive from Steam.
If replaying just the application cache, make sure to replay together with the common cache, as application cache can depend on common cache.
Maximum number of clients reachedMaximum number of clients reached09/29 02:47:48 Failed writing minidump, nothing to upload.
/home/***/snap/steam/common/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 117: 12711 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@

**Comment by kisak-valve** [comment]
Hello @BrikeX, `Maximum number of clients reached` and `Driver: Mesa llvmpipe (LLVM 15.0.7, 256 bits)` is more concerning than the Fossilize related log lines.

Llvmpipe is mesa's Faster software renderer and tells us that the Snap environment you're running Steam inside isn't giving Steam, and by extension Dota 2 access to your video card.

Please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Separately, please test how the game behaves without Canonical's snap packaging being involved.

**Comment by BrikeX** [comment]
@kisak-valve thanks, this is the [Steam Runtime Diagnostics](https://gist.github.com/fc28966af194e38019928bb50f5e27e7.git)

**Comment by BrikeX** [comment]
@kisak-valve I have tested steam & dota2 without Canonical's snap packaging and dota still cannot be launched.

**Comment by kisak-valve** [comment]
Thanks, it looks like you're using a distro release that's about 3 years older than your hardware, and the extended diagnostics information shows that at https://gist.github.com/BrikeX/fc28966af194e38019928bb50f5e27e7#file-gistfile1-txt-L285-L300 and https://gist.github.com/BrikeX/fc28966af194e38019928bb50f5e27e7#file-gistfile1-txt-L320-L343.

Since we already know that OpenGL and Vulkan doesn't work with newer mesa in the Snap environment, then that tells us that the most likely caused by your kernel being older than when support for your GPU was added in general.

With Intel (and AMD) graphics, I'd recommend using a distro release that is newer than the hardware you're running on, and the Xeon W-11955M was released somewhere around mid-2021.

You might get lucky and find a set of experimental overrides or manually check and update the Linux kernel, mesa, and possibly add any needed hardware firmware to newer than your hardware, but that can me more effort than it's worth compared to a general system upgrade to a newer distro release.

In any case, thanks for the details. It's clear now that all GPU accelerated applications will have trouble with your current system install and this is not a game-specific issue.
