### ISSUE TITLE
Steam Deck. Dota 2 doesn’t launch/Unable to ping any region 

### ISSUE THREAD

**Issue by Xotabch1** [ValveSoftware/Dota-2#2586]
Hello Everyone,

So, I have usual the cheapest version of  Steam Deck, like it was from the box, no messing with programs or what’s inside the steam deck.

* OS variant steamdeck-rc/ OS Version 3.4.11 (system update channel is beta)
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? (don’t now, probably yes)
* Have you verified the game files?: [Yes]

**My Issue:**
First a lit bit of history to understand.
Since the 27 September Dota update I couldn’t launch dota at all till yesterday. 
I pressed “green play button”, than I was having black screen with steam logo on it, and than again dota 2 page in my library with green play button.

**The situation right now:**
I have 2 accounts on my steam deck, they are attached to one email.

**1 account** 
1 account has Dota 2 which doesn’t have ranking matches (because I didn’t connect phone number to it).
This account can right now launch dota 2 but:
When I am trying to choose the right server it has the next text: “Unable to ping any region. Check your Internet connection”. .Screenshot attached. 
![87EB8972-CBEF-4024-A2CE-4886AF9DE5A1](https://github.com/ValveSoftware/Dota-2/assets/141767456/2bb86a89-93de-444b-86b8-2ae1037dd6b4)

I tried my mobile internet, problem is the same.
I have seen that the problem might be with firewall, but I don’t think that steam deck has it at all.

**2 account** 
2 account, has dota 2 with activated ranked matches.
Here I cannot launch it at all. 
(I press “green play button”, than I have black screen with steam logo on it, and than again dota 2 page in my library with green play button.)

*****Why different accounts have different problems on 1 device?*****

I am tired of not been able to play my favorite game.
Steam support is useless. Don’t understand how is it possible to not being able launch Valve game on Valve product.

PS: Sorry, I am not so good with technical specifics since I am just playing. If you need more specifics just write where could I find them.

**Comment by mkjOoB** [comment]
@Xotabch1 can you test if the whole device can access internet at all, e.g. browser app in steam deck desktop mode? You may also name your internet provider.

**Comment by Xotabch1** [comment]
> @Xotabch1 can you test if the whole device can access internet at all, e.g. browser app in steam deck desktop mode? You may also name your internet provider.

@mkjOoB

In the Desktop mode, I opened steam dota 2 page through Firefox without any problems.

In the game mode, when I open dota I can watch International right now.

I am in Toronto Canada and using Bell.

my mobile Internet is from Chatr.

**Comment by mkjOoB** [comment]
@Xotabch1 You could try a number of things:
* Switch off beta updates on steam deck
* Verify Dota 2 game files
* Factory reset your steam deck at System's setting tab, you should disable beta branch 1st probably
P.S. this does seem like something went wrong and it is probably not your connection's problem. Not a valve guy.
Удачи.

**Comment by Xotabch1** [comment]
@mkjOoB 

I have done everything you told me about, unfortunately the result is the same(

**Comment by Zawah** [comment]
For reference, dota 2 with "Proton experimental"  compatibility shows the same behavior... on debian(no nvidia 535 available yet for my distro)


Weird thing is that you can interact with some features, like selecting a guild contract or changing your profile, but you can't ping any server or watch games(and matches still load but can't connect to watch).

(I was trying proton experimental because since the 10th anniversary update, native game keeps crashing, and for some reason it was working with proton 8.0.4 until updates were rolled out and stopped being able to even open it. Last update allowed proton experimental to launch but you can't play...)

**Comment by Xotabch1** [comment]
> For reference, dota 2 with "Proton experimental" compatibility shows the same behavior...
> 
> Weird thing is that you can interact with some features, like selecting a guild contract or changing your profile, but you can't ping any server or watch games.

I use Proton Experimental too, without it, it doesn’t launch at all
I started using Proton experimental since March this year I guess.

**Comment by Xotabch1** [comment]
> For reference, dota 2 with "Proton experimental" compatibility shows the same behavior... on debian(no nvidia 535 available yet for my distro)
> 
> Weird thing is that you can interact with some features, like selecting a guild contract or changing your profile, but you can't ping any server or watch games.
> 
> (I was trying proton experimental because since the 10th anniversary update, game keeps crashing without compatibility, and for some reason it was working with proton 8.0.4 until updates were rolled out and stopped being able to even open it. Last update allowed proton experimental to launch but you can't play...)

@Zawah 
where are you from ?
I am from Canada, Toronto.

asking because I know guys from USA and Russia and they are OK.
Maybe it is local problem ?

**Comment by Zawah** [comment]
> > For reference, dota 2 with "Proton experimental" compatibility shows the same behavior... on debian(no nvidia 535 available yet for my distro)
> > Weird thing is that you can interact with some features, like selecting a guild contract or changing your profile, but you can't ping any server or watch games.
> > (I was trying proton experimental because since the 10th anniversary update, game keeps crashing without compatibility, and for some reason it was working with proton 8.0.4 until updates were rolled out and stopped being able to even open it. Last update allowed proton experimental to launch but you can't play...)
> 
> @Zawah where are you from ? I am from Canada, Toronto.
> 
> asking because I know guys from USA and Russia and they are OK. Maybe it is local problem ?

I don't think it has anything to do, mostly because it looks like I have connection to the game systems(profiles load, I can see what my friends are playing for example) but I can't match up....



Can you confirm if you can modify your profile, or if you have a guild select a contract, or if you go to watch you get matches listed but can't connect to spectate?

**Comment by mkjOoB** [comment]
Should probably ping these here, too.
https://github.com/ValveSoftware/Proton/issues/7152
https://github.com/ValveSoftware/Proton/issues/6631

Could be so, that valve made dota/cs2 intentionally borked on proton, just a guess.
@Xotabch1 Anyways, you could try to get logs from the game when running proton by adding this to launch options:
`PROTON_LOG=1 %command% <your game flags go here no brackets needed>`

Then after running a game, the file will be in your home directory, with a name steam-570.log
Though I guess it's redundant, this issue is not with steam deck but proton-8.0.4 crashing outright, and Proton Experimental not able to connect/ping game servers. I wasn't able to find a fix for proton, Proton Hotfix, Proton Experimental [bleeding-edge] branch all have this issue.

You should stop using proton for this game until it is fixed, disable it for dota in compatibility settings.
Tell me if that works, if not, try adding this to launch options
`%command% <your flags go here, no brackets> |& tee /tmp/dota2.log`

Then you game log will be at /tmp/dota2.log, you can get it out if you know how, or you could use something like this in desktop mode's terminal, it will print out the url which you can give to us:
`cat /tmp/dota2.log | curl -F 'clbin=<-' https://clbin.com`

Anyhow this command can be used to get any log out, just replace /tmp/dota2.log with full path of one you desire.

**Comment by kisak-valve** [comment]
Hello @Xotabch1, running Dota 2 (for Windows) with Proton is not officially supported, and is out of scope for this issue tracker.

On the Steam Deck, there should be no compatibility tool selected to use with the game in the per-game properties so that the Dota 2 for Linux client is run inside the Steam Linux Runtime 3.0 container environment. Selecting Steam Linux Runtime in the per-game compatibility options will result in https://github.com/ValveSoftware/steam-for-linux/issues/9844.

Feel free to continue discussing this issue in an unofficial capacity on the compatibility report for the game in the Proton issue tracker (https://github.com/ValveSoftware/Proton/issues/6631).

**Comment by prnvp23** [comment]
> Hello @Xotabch1, running Dota 2 (for Windows) with Proton is not officially supported, and is out of scope for this issue tracker.
> 
> On the Steam Deck, there should be no compatibility tool selected to use with the game in the per-game properties so that the Dota 2 for Linux client is run inside the Steam Linux Runtime 3.0 container environment. Selecting Steam Linux Runtime in the per-game compatibility options will result in [ValveSoftware/steam-for-linux#9844](https://github.com/ValveSoftware/steam-for-linux/issues/9844).
> 
> Feel free to continue discussing this issue in an unofficial capacity on the compatibility report for the game in the Proton issue tracker ([ValveSoftware/Proton#6631](https://github.com/ValveSoftware/Proton/issues/6631)).

What does this mean? Okay so we are meant to use the native linux version on Steam Deck and other Linux distros. First off I don't understand why a Valve game is not officially supported on Proton but putting that aside, the native linux version is also crashing on launch for me now despite verifying integrity of game files. Any and all issues faced by Proton users for this game are just being dismissed as not planned and not officially supported while the native linux version which was already running worse is now not running at all. So are we just never gonna get a fix and be completely unable to play an official Valve game on an official Valve device?

**Comment by 958josue** [comment]
que tal mi amigo soy de Perú y juego casi seguido el dota 2 .
cuando tuve la steam deck lo jugaba bastante  en ella ,asta me acostumbré a jugar con el mismo mando de la steam deck .
asta que estés de navidad o después creo para ser exacto ,tengo el mismo problema tuyo .
asta compre tarjeta interna de 512gb y quise aprovechar la formateada de steam deck pensando que se solucionaría todo pero Continuo con el mismo error mi estimado .
no eres el único estimado solo espero que alguien capas pueda darnos la solución y poder disfrutar de nuestro juego favorito y de las steam deck . 
EL PROBLEMA PARECE QUE PROVIENE DEL SISTEMA ANTITRAMPAS DEL MISMO SERVIDOR DE DOTA 2
