### ISSUE TITLE
[OS X] Borderless window mode makes game appear behind dock and menubar

### ISSUE THREAD

**Issue by mfilej** [ValveSoftware/Dota-2#260]
When I go to Video settings and set Display Mode to Borderless Window, the dock and menubar will be visible above the game.

This is a problem I noticed the day after the OS X Reborn client came out, but it was then fixed. Now it reappeared (not sure when exactly because I haven't been active for the past 2 weeks).

Screenshot:
![screen shot 2015-07-23 at 12 25 02](https://cloud.githubusercontent.com/assets/3621/8848211/eaa8d012-3135-11e5-8d44-902933299d97.png)

This issue does not appear in with _Desktop-friendly Fullscreen_ mode, but that mode is not satisfactory to me as I describe in #259.

**Comment by jeanlain** [comment]
I suppose this is intentional since the "desktop-friendly fullscreen" mode is supposed to be equivalent of a fullscreen borderless window. However, since there are issues with Vsync in fullscreen mode, I too would like to use the borderless window mode at full screen resolution without seeing the menu bar and dock.

**Comment by mfilej** [comment]
Why do you think it is intended to be like this? I don't suppose anyone finds this useful, am I wrong?

**Comment by jeanlain** [comment]
A regular window is generally not supposed to sit on top of menus and dock. In your screenshot, you use a window at full screen resolution. In this case it is recommended to simply use one of the two available fullscreen modes (which have their own problems, but this is another issue). 
But I agree that they could just make the game window sit on top of everything else. I think it is easy to do in Xcode.

**Comment by mfilej** [comment]
> A regular window is generally not supposed to sit on top of menus and dock.

I think that would be true for the Windowed mode. In Borderless the game acts far form a regular window For instance it has no chrome and it can't be moved around.

**Comment by gdrewb-valve** [comment]
@jeanlain is correct, Reborn deliberately offers multiple modes so that users can choose the behavior they want.  If you don't want to see desktop elements use one of the fullscreen modes.  For example, desktop-friendly fullscreen is very similar to a borderless window and doesn't cause mode switches like exclusive fullscreen.  Does it work the way you want?

**Comment by jeanlain** [comment]
It wouldn't hurt to make the borderless window float on top of the menu and dock, like it did before. I would personally appreciate it since the fullscreen modes have issues with V-Sync. If people want to put other windows on top of the game, they could choose the standard window mode.

**Comment by gdrewb-valve** [comment]
Desktop-friendly fullscreen at monitor size is exactly equivalent to what monitor-sized borderless window was.

**Comment by mfilej** [comment]
I'm curious to hear what the use case is for having the dock/menubar float over in Borderless? Seems like you can't really play in that mode without clicking on the dock/menubar accidentally?

**Comment by jeanlain** [comment]
Arguably, this allows putting another app on top of the game (say your twitter app ;-) with the game being still visible. But this is never really useful, and if you want that, you could choose the standard window mode instead. Since the borderless mode allows the window to be as large as the monitor, there is an argument that it should be on top of the menu bar and dock.

**Comment by gdrewb-valve** [comment]
We made the settings change to attempt to be consistent.  Windowed modes are windows and work like all other windows, which means they are underneath the desktop elements like the dock.  Fullscreen modes take over the whole screen and hide desktop elements.  Previously it was somewhat strange that a borderless window 1 pixel smaller than the monitor would be under the dock but one exactly matching the monitor would be over the dock.

The new modes offer everything that was offered before, desktop-friendly fullscreen at monitor size is precisely the same mode as what a monitor-sized borderless window was, so there is not reason not to offer the choice.

**Comment by gdrewb-valve** [comment]
Aside from the discussion of what modes should be offered is there an issue here that isn't already in other issues?  I'm going to close this out.

**Comment by mfilej** [comment]
Feel free to close, thanks for the feedback. :heartbeat:

**Comment by gdrewb-valve** [comment]
Thanks, closing.
