### ISSUE TITLE
Dota 2 stuck at logo & crash

### ISSUE THREAD

**Issue by faiezyacob** [ValveSoftware/Dota-2#2608]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/faiezyacob/be2689131c7afabe9c117f725cdb15b4
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

I've tried two method for this. One without using the compatibility layer & the game stuck at the dota 2 logo forever. When tried running using compatibility layer, the game goes until the Valve logo & crash after that. I have tried running the game with `-vulkan_disable_graphics_pipeline_library` but the issue still persists.

**Comment by kisak-valve** [comment]
Hello @faiezyacob, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Probably unrelated to this issue, but `Driver: Mesa llvmpipe (LLVM 16.0.6, 256 bits)` in your system information tells us that Steam is being forced to fallback to mesa's faster software renderer to run at all. That hints that your NVIDIA driver install is incomplete. Most likely the `lib32-nvidia-utils` system package is missing for the video driver's 32 bit userspace libraries.

**Comment by faiezyacob** [comment]
Hi @kisak-valve attached is the [gist](https://gist.github.com/faiezyacob/603674bea99f8bd7a29e913f621fa668) for the `Steam Runtime Diagnostic`. 

I have installed `lib32-nvidia-utils` and the issue still persists.

Edit: I wonder if i should wait for the Vulkan shaders to complete?

**Comment by kisak-valve** [comment]
Thanks, it looks like the Vulkan render paths are healthy on your system.

I have a guess that your wlroots based wayland compositor is using an EGL based render path, and that's most likely running on llvmpipe as well due to https://gist.github.com/faiezyacob/603674bea99f8bd7a29e913f621fa668#file-gistfile1-txt-L282-L304. I suspect that the NVIDIA proprietary driver is having a hard time interacting with wlroots running on llvmpipe in that configuration and there might be an additional missing system package needed to let the NVIDIA proprietary driver back your desktop session. It might be worthwhile to test how the game behaves with an X based user session. 

This is a blind guess, but maybe that render path needs `egl-wayland`. Can you check if that system package is installed, and if adding it followed by restarting your user session have an effect or make the runtime diagnostics look healthier at least?

**Comment by mkjOoB** [comment]
@kisak-valve @faiezyacob source2 vulkan is currently broken on nvidia proprietary drivers with wayland session, It does not affect X11 sessions. Try to downgrade to 535 or lower driver release for use with wayland. The fix should be in next release after 545.29.02, as per https://github.com/ValveSoftware/csgo-osx-linux/issues/3504#issuecomment-1788268591.

**Comment by faiezyacob** [comment]
Hi @mkjOoB can link me to downgrading steps? That would really be helpful as im fairly new to Linux

**Comment by mkjOoB** [comment]
@faiezyacob I see you're using arch, you could try installing nvidia-535xx-utils from Arch User Repository, as the official repoes now ships the current version, you'll need a package manager update to simplify installs from AUR.
You can follow install instructions here: https://github.com/Jguer/yay#installation
After yay is installed, run `yay -S nvidia-535xx-utils` to use 535 branch. Hint, yay can now be used instead of pacman, be vary of relying on AUR for other packages, more on this can be read here:
https://wiki.archlinux.org/title/Arch_User_Repository
Do note you'll have to `yay -S nvidia`, when the update is out, do monitor it yourself, otherwise you'll get stuck on 535. Also you should remove -vulkan_disable_graphics_pipeline_library from dota cmdline, it's well supported now, and is/was for times when certain vulkan extension was fairly new. Disabling it unnecessary and likely comes with performance cost.

**Comment by faiezyacob** [comment]
Hi @mkjOoB can confirmed downgrading to 535 fixed the issue. Thanks!
