### ISSUE TITLE
[Linux] Failed to initialize Vulkan

### ISSUE THREAD

**Issue by Wujekklawy** [ValveSoftware/Dota-2#2706]
#### Your system information

* [System information](https://gist.github.com/Wujekklawy/5682ed8c3bc613214c73f6074e1d8049) 
[Steam Runtime Diagnostics](https://gist.github.com/Wujekklawy/6b11c7753913434699883be6b3560c43) 
* Have you checked for system updates?: [Yes]
* Are you using the latest stable video driver available for your system? [i think so]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
When i try to run dota i get "failed to initialize Vulkan" error. This is my first time using linux so probably i didn't do something that is obvious. i have Gforce GTX 680 and before changing from windows dota was running flawlessly. (if i recall i had problems with Vulkan on windows too when i changed to it being curious). I spent 6+ hours trying to find solution on the internet

#### Steps for reproducing this issue:

1. instal dota
2. click play
3. wait few seconds

**Comment by kisak-valve** [comment]
Hello @Wujekklawy, Dota 2 is accurately telling you that Vulkan is broken in the Steam in Snap packaging that you're using (https://gist.github.com/Wujekklawy/6b11c7753913434699883be6b3560c43#file-gistfile1-txt-L321-L334). This is a video driver and/or Snap issue, not a game issue.

Generally speaking, the NVIDIA 470 series video driver is needed for this hardware generation to support Vulkan 1.2. Even if it's installed on your host system, it may not be available in Snap's runtime environment.

**Comment by Dracosophy** [comment]
I'm in the same situation; moved from win7 with dota2 working perfectly in dx11 on a GTX660 TI 2gb , install Linux and the 470xx driver and now when i can get the right kernel and driver version to agree with my system and dota2 it still will freeze or CTD after 30 min or 300 min at random. Also the Linux install of dota2 seems really bad as there is a bunch of stuff in the console about failing to find things and other errors that were not there before, nor do my friends have it. I've seen the exact same errors in multiple Linux distro now (arch and ubuntu), and always though it's Vulkan that causes an eventual crash on that driver.
it's a first generation vulkan support card, so i get it; it's old af (2011~) but it runs on dx11 and openGL perfectly... dota2 just stopped supporting OGL a few years ago iirc, and the only way i know to get it running in dx11 in Linux is install the windows game and use PRoton or something to run it?
That's my next step because this is really annoying to be almost able to play, in fact it runs better with better FPS, but completely randomly freeze or CTD!

Having tried a million different kernels and settings, i think it must be XFCE or vulkan just don't like my old hardware and since not many people use those old cards & drivers anymore, no one is fixing whatever vulkan crash is happening for us who have them.
I've read about the exact sort of issues i have where people using the 500 series nvidia drivers had it eventually fixed for them, or they rolled their driver back an kept playing no problem... but those drivers are about the most common, and the 400 (470) is legacy for old old Nvidia cards ... fermi core or whatever.
