### ISSUE TITLE
[Developer] 'IsInvulnerable' called on an entity (npc_dota_goodguys_fort at -5920 -5352 240) that cannot be seen! flood/spam

### ISSUE THREAD

**Issue by Espionage724** [ValveSoftware/Dota-2#2737]
```
[Developer] 'IsInvulnerable' called on an entity (npc_dota_goodguys_fort at -5920 -5352 240) that cannot be seen!
[Developer] 'IsInvulnerable' called on an entity (npc_dota_goodguys_fort at -5920 -5352 240) that cannot be seen!
[Developer] 'IsInvulnerable' called on an entity (npc_dota_goodguys_fort at -5920 -5352 240) that cannot be seen!
[Developer] 'IsInvulnerable' called on an entity (npc_dota_goodguys_fort at -5920 -5352 240) that cannot be seen!
[Developer] 'IsInvulnerable' called on an entity (npc_dota_goodguys_fort at -5920 -5352 240) that cannot be seen!
[Developer] 'IsInvulnerable' called on an entity (npc_dota_badguys_fort at 5528 5000 248) that cannot be seen!
[Developer] 'IsInvulnerable' called on an entity (npc_dota_badguys_fort at 5528 5000 248) that cannot be seen!
[Developer] 'IsInvulnerable' called on an entity (npc_dota_badguys_fort at 5528 5000 248) that cannot be seen!
[Developer] 'IsInvulnerable' called on an entity (npc_dota_badguys_fort at 5528 5000 248) that cannot be seen!
```

Similar lines are flooded constantly in Dota 2's Console!

I'm not sure if there's an obvious solution and gameplay seems fine otherwise, but I'm wondering if I can stop that message from being reported or logged like that as it seems like a large performance hit just flood-reporting it?

___

I'm loading into a Bot match with this:

```
~/'Steam/steamapps/common/SteamLinuxRuntime_sniper/run' -- ~/'Steam/steamapps/common/dota 2 beta/game/dota.sh' -console  +sv_lan '1' +dota_bot_set_difficulty '3' +dota_start_ai_game '1' +map 'dota'
```

And have RMMAI bot scripts in `bots` folder for Local Dev Scripts ([info](https://github.com/adamqqqplay/dota2ai/issues/156)).

It doesn't sound like the error is specific to how I'm loading it, but I wonder if anyone else can replicate it from main menu -> play vs Bots and Default or any other workshop bots?

___

#### Steps for reproducing this issue:

1. Start bot match
2. Open Console
3. Observe spam

**Comment by kisak-valve** [comment]
Hello @Espionage724, I was passed a note from a Dota 2 developer.

They write:
```
This is a bot script trying to look at data on an entity in fog, so the server is preventing them from cheating.
If this is just a user that wants to silence the spam, they should be able to `developer 0` in console.
If this is the script developer they should be able to stop making such requests.
```

Are you able to reproduce this issue without the third party bot script(s) being involved? This looks like something that needs to be evaluated and resolved on the issue tracker you linked.

**Comment by Espionage724** [comment]
Thanks! It does only happen on those bot scripts and not the Default ones: https://www.youtube.com/watch?v=GJo5N9VC7bQ

**Comment by forest0xia** [comment]
I really don't like the words saying the script or the developer was trying to cheat by calling that api for the units that can not be seen. The only reason for the bot scripts to make that api call on the invisible unit is because the unit was returned in the APIs such as GetNearbyHeroes, and the developer simply trusted the api result to be accurate and safe and directly call the other APIs on the returned units for bot's decision making.
If the Valve developers are good enough, can you make these easy and possible improvements to avoid these kind of silly spams for all of us:
1. Do not return the units from the GetNearby* api calls if the unit is not visible.
2. Do not show those spamming logs by default logging level. 
3. By default can we fallback to nil or false if the unit called on the api is not accessible.
4. Add more log/ exception tracking to this api as well as other APIs (there are a lot of such APIs throw logs without exception tracking), so the other developers without the internal access can be able to realize where exactly went wrong for the warning/error message.
