### ISSUE TITLE
Dota 2 Workshop Tools Alpha : Failed to start game (missing executable)

### ISSUE THREAD

**Issue by clankill3r** [ValveSoftware/Dota-2#305]
Max OS X 10.10.4
MacBook pro retina early 2013.

Beta Participation: Steam Beta Update

Troubleshoot didn't help:
https://support.steampowered.com/kb_article.php?ref=8676-EFLX-7453&l=english&steamid=76561197985052912&errortype=EAppUpdateError&errorvalue=28

I think the tools are actually missing cause If "Delete Local Content..." and reinstall then it downloads 0 bytes.

This problem seems to be really common, also for other platforms.

**Comment by gdrewb-valve** [comment]
The tools only exist for Windows so this isn't supposed to work.  As they're also done as a DLC I'm not sure they can be hidden per-platform but I'll check.

**Comment by gdrewb-valve** [comment]
How did you set up the workshop tools?  How are you trying to launch them?

**Comment by clankill3r** [comment]
Talking about mac:
First I just downloaded under tools "Dota 2 Workshop Tools Alpha". This with steam not being in Beta Participation and Dota 2 not being installed. (I just wanted to play with hammer and I was hoping I could launch it without the need of Dota 2).

Then I tried a lot of things where I can't remember the order. On a mac the only way to launch it seems to be from the tool menu.

On windows I can launch it with no problem (I did go in steam beta and added the DLC). I just start Dota 2 and it prompts me with 3 options where one is launching the tools. I didn't even need to install the tools on windows in order to be able to run them.

I hope this helps.

**Comment by gdrewb-valve** [comment]
On my Mac the Workshop Tools entry says "this program is not available for this computer".  I get the same message when trying to install it.

Regardless, there is no Mac version of the tools so failure is expected.

**Comment by clankill3r** [comment]
In case it helps:

Notice disk usage is `none`
<img width="956" alt="screen shot 2015-08-11 at 11 03 52 pm" src="https://cloud.githubusercontent.com/assets/738650/9210588/6a99453a-407d-11e5-9bed-c4bd0671221b.png">

On `Browse Local Files...` it brings me to:

> /Users/doekewartena/Library/Application\ Support/Steam/steamapps/common/dota\ 2\ beta

On verify cache it is verifying dota 2 I guess (since it takes some time).

On delete local tool content I get the same and reinstalling I get the same.
Maybe the order of operations I did in the beginning had to do with it.

**Comment by rained23** [comment]
anyway if Workshop Tools in not available on OS X, I hope it should be added as soon as possible.

Right now I am really interested to develop some custom games but due to Windows only. 
I am not buying Windows to just develop a custom games.

Plus many developers having OS X machine, I think its good to have it in OS X.

**Comment by gdrewb-valve** [comment]
Sorry but there are no plans to support the Workshop Tools on anything other than Windows.  I'm going to close this out as there's no Reborn bug.  You could potentially open a Steam bug but in my testing it appeared to work correctly.

**Comment by ramma** [comment]
@gdrewb-valve Are there no plans period, or just for the Alpha phase of the Dota 2 workshop tools?

**Comment by dhollinger** [comment]
@gdrewb-valve So despite the big SteamOS/Steam Machine push, there won't be any tools for those users only for the Windows users?

**Comment by ekianjo** [comment]
This is really disappointing, Valve.

**Comment by Theswweet** [comment]
@gdrewb-valve Well that's unfortunate. I really, really hope you guys reconsider.

**Comment by eddie-dunn** [comment]
I am assuming you are not considering Linux/OSX support _right now_ because you have bigger fish to fry at the moment, what with the coming SteamOS launch and everything. I'm okay with that.

"No plans" can be very ambiguously interpreted, however. Do you mean no plans at the moment? Or no plans ever?

**Comment by ekianjo** [comment]
eddie-dunn, you have to remember that Valve is not your typical company with rules and policies, their development is relying on smaller teams and is based on ongoing employees' interests - it may very well be that not all teams are interested in supporting Linux at all, while some others are doing most of the work for it, severed from the bigger projects like DOTA2.

**Comment by Maokei** [comment]
That's quite disappointing valve!

**Comment by clankill3r** [comment]
Please stop posting comments like that. They have close to zero value.
Also:

> Conduct
> 
> There are basic rules of conduct that should be followed at all times by everyone participating in the  discussions. While this is generally a relaxed environment, please remember the following:
> 
> ...
> Do not intentionally multi-post an issue.

I think github is a really nice way to create a bridge between the devs and the community. But with non constructive posts like "That's quite disappointing valve!". All you do is waste time of devs and encourage them to check the issues less often.

I'm sure they have good reasons. Maybe there are dependencies like the .NET framework that only runs on windows or something. Or maybe it requires to much maintenance to have a mac os x version in this stage.

Valve ain't stupid. They also have hardware surveys so I think they are pretty well aware of the amount of MAC / Linux users.

**Comment by ekianjo** [comment]
> I'm sure they have good reasons. Maybe there are dependencies like the .NET framework that only runs on windows or something. Or maybe it requires to much maintenance to have a mac os x version in this stage.

Reasons is exactly what I would like to hear, instead of just saying that they are not going to support it.

**Comment by dhollinger** [comment]
@clankill3r Those metrics are not accurate. I can tell you that in the last 6 months my wife (running windows) has gotten the steam survey 6-7 times, as someone running only Linux (primarily for professional reasons) I've only ever seen the survey once in the last year. That disparity in frequency will create inaccurate results. That said, OSX (Sitting around 3%) and Linux (Sitting around 1.2%) both come to at least 4 - 4.5 million users on those platforms alone and that is no small number to ignore.

**Comment by elbuglione** [comment]
5% OSX+Linux = 4.5 millions of Developers an Designers
95% Windows = 100 Millions of Non Developers and Non Designers.

**Comment by gdrewb-valve** [comment]
There are no plans to support the tools on anything except Windows for the forseeable future.  Valve understands that will disappoint many people but we only have so many resources and maintaining the tools across all platforms has a substantial cost. We know this is not what people using this bug tracker want to hear but that's the state of things, sorry.

**Comment by pithium** [comment]
@ekianjo: Let me translate what eddie-dun was attempting to say....

@gdrewb-valve: Linux is a different platform, and the users are different. Supporting Linux involves supporting Linux Users, and I understand if this seems odd, because in Win32 things are the pposite. The paradigm for development is different, and the tools are different. I can name 3 very nice 3d FPS engines that do not suffer on Linux the way Source does and do equally well on Windows, Mac, PPC and ARM. There are potential Valve customers that delete the Windows partition on every computer they buy without hesitation. Why? Because of everything you just said.

There was an interview in the Dota newslist about how Valve believes their "strongest form of communication software". I hope that's a legit interview. Drop the D3D, .net, and other MS dependencies, and support Windows, Mac and Linux. Or don't. And support only Windows. It's your software do what you want. 
But it's THIS:  "There are no plans to support the tools on anything except Windows for the forseeable future." Marketing bs that we rejected a long time ago.

http://www.pcgamer.com/valve-on-dota-2-reborn-community-and-building-a-game-for-the-long-term/?ns_campaign=article-feed&amp;ns_mchannel=ref&amp;ns_source=steam&amp;ns_linkname=0&amp;ns_fee=0

We know you already know how to write an SDL application, and SDL works fine on Windows so "maintaining tools across all platforms" is an excuse I'm not paying $$ for. Hell using SDL you could port Source to android and IOS. Is your resource budget bigger than volunteer project funded by donations?

end of rant... maybe someday we will stop punishing people for having a favorite platform.

**Comment by vokama** [comment]
@gdrewb-valve Sorry to bother, but it really teases me. Does this also mean that S2 SDK will not be available on Linux in the near future?

**Comment by LLFourn** [comment]
Sorry to comment on an old issue but can someone who is part of the VALVE developer community mention that it only works on Windows on the wiki so ppl don't waste there time trying to figure out why they can't install it.

https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Installing_and_Launching_Tools

**Comment by gdrewb-valve** [comment]
I passed this on and the page has been updated.

**Comment by neronmoon** [comment]
That's quite disappointing, valve!

**Comment by migrome** [comment]
Has anyone managed to launch Workshop Tools using wine?

**Comment by baaannnaaannn** [comment]
pls valve make a tools for linux
