### ISSUE TITLE
[OSX] Game keeps crashing after newest update (Sep 01)

### ISSUE THREAD

**Issue by alexmcjuicy** [ValveSoftware/Dota-2#343]
The game crashes at random times, whether in game, at the main menu, or browsing custom games.

System info:

Macbook Pro (2011)
2.3 Ghz Intel Core i5
4GB Memory
Intel HD 3000 384 MB graphics
Software version 10.9.0

I don't know much about computers so I just copied and pasted the crash report from my computer to this link:

http://pastebin.com/zTAqJ9wH

Hopefully there's just a bug and my computer is able to run it eventually. For the record I run source 1 client with 0 problems.

**Comment by gdrewb-valve** [comment]
The crash is in Apple's OpenGL driver so this may not be simple for Valve to fix.

**Comment by jeanlain** [comment]
Maybe update the OS to 10.9.5?

**Comment by alexmcjuicy** [comment]
@jeanlain 

From about 30 minutes of Googling and looking into the subject of OpenGL, as far as I was able to discover, not even OS Yosemite (aka 10.10) has a more recent upgrade for OpenGL. It seems I already have the latest version of OpenGL that Apple supports which is 4.1.

Does anybody know what version of OpenGL is required for Reborn?

**Comment by gdrewb-valve** [comment]
It's not the version of OpenGL, it's that the newer OpenGL driver in 10.9.5 might have bug fixes and the crash you're seeing may be fixed in a newer system.  It's possible that it's something that Reborn is doing also but running on the newest system is usually a good idea, unless there's a specific reason not to.

**Comment by danginsburg** [comment]
@alexmcjuicy There is a known driver bug that causes a crash in 10.9.0 on HD 3000, you will need to update OS X to use Dota 2 Reborn.  I recommend OS X 10.10.5.  It may work in 10.9.5, but I seem to recall seeing a driver bug there that caused a crash loading the hero selection screen on HD 3000.  I'm going to close this because the issue with 10.9.0 is a known driver bug and we won't be able to fix it.
