### ISSUE TITLE
Cursor size on high DPI screens

### ISSUE THREAD

**Issue by bosssarawongsuth** [ValveSoftware/Dota-2#347]
The cursor is extremely small on 3k and 4k resolution display making it impossible to use skills and right click accurately since it blends in with the skill effects etc. during team fights. It's a lot bigger in Dota 2 Source 1.

**Comment by gdrewb-valve** [comment]
Can you post your Steam system info?  Cursor scaling should work on Windows, mostly on Linux and not on OSX.

**Comment by bosssarawongsuth** [comment]
![20150903_134302](https://cloud.githubusercontent.com/assets/9318706/9652136/752d16bc-5210-11e5-8797-0714d5a12a7b.jpg)

Above is the example of how small the cursor is. I don't know why it says below in the Steam system info that my resolution is 1440x810 because it is actually 2880x1620 and I'm using 200% scaling for texts,apps,etc in Windows display settings to increase my text size.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  2494 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce GTX 970M

```
DirectX Driver Name:  nvd3dum.dll
Driver Version:  10.18.13.5582
DirectX Driver Version:  10.18.13.5582
Driver Date: 25 Aug 2015
OpenGL Version: 4.5
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 59 Hz
DirectX Card: NVIDIA GeForce GTX 970M
VendorID:  0x10de
DeviceID:  0x13d8
Number of Monitors:  1
Number of Logical Video Cards:  1
No SLI or Crossfire Detected
Primary Display Resolution:  1440 x 810
Desktop Resolution: 1440 x 810
Primary Display Size: 13.54" x 7.60"  (15.51" diag)
                                        34.4cm x 19.3cm  (39.4cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 3072 MB
Supported MSAA Modes:  2x 4x 8x 
```

Sound card:
    Audio device: Speakers (Realtek High Definiti

Memory:
    RAM:  16301 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  Undetermined
    Total Hard Disk Space Available:  1181874 Mb
    Largest Free Hard Disk Block:  263301 Mb
    OS Install Date: Jan 01 1970
    Game Controller: None detected

**Comment by gdrewb-valve** [comment]
It's possible Steam isn't marked as DPI-aware so Windows is lying to Steam.  Does Reborn show the proper monitor resolution in the video settings?

As this isn't a Mac or Linux issue this should go in the regular forums.  I'll leave it open for a bit to gather info.

**Comment by bosssarawongsuth** [comment]
Yes Reborn uses 2880x1620 resolution, Sorry I posted in the wrong forum, I'll repost this in a regular forum
Cheers

**Comment by bosssarawongsuth** [comment]
I couldn't find a forum on github for the regular Dota 2 Reborn. I tried registering for the forum on dev.dota2.com and it gives me a "database error" and trying to sign in with that account, the system says I'd been banned for "No specified reason". Is it possible for you to pass on this information to the Windows team as Reborn is going to be the main client in a few weeks and this issue is really important to a lot of people with high dpi screens?

**Comment by gdrewb-valve** [comment]
I've passed this on.

**Comment by rcano** [comment]
I'd like a review of this issue, since I have a linux machine with 2880x1620 res and the cursor is the size of the head of a ranged creep, just like image posted already.
In fact, the cursor shown throughout the UI is bigger than that shown ingame for some reason.
Here is my system info:

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3700 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-28-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation Quadro K2100M/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.41
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x11fc
Number of Monitors:  2
Number of Logical Video Cards:  2
Primary Display Resolution:  2880 x 1620
Desktop Resolution: 4320 x 1620
Primary Display Size: 13.39" x 7.48"  (15.31" diag)
                                        34.0cm x 19.0cm  (38.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  31805 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  157576 Mb
    Largest Free Hard Disk Block:  132078 Mb

Installed software:

Recent Failure Reports:

**Comment by danginsburg** [comment]
@rcano I am unable to repro this at 2560x1440.  Would you be able to provide a picture or screenshot of the cursor in menu and in game?

**Comment by rcano** [comment]
Here they are:
![dota-mouse-ui](https://cloud.githubusercontent.com/assets/759769/9921538/f21efd8a-5cb4-11e5-80cf-3e95eef8a43a.png)
and in game (the cursor is above the hero portrait):
![dota-mouse-in-game](https://cloud.githubusercontent.com/assets/759769/9921544/fcdb9738-5cb4-11e5-9d54-8107317668ff.png)

In game is slightly smaller ? (maybe an illusion due to the different style, ingame one having a black border). Notice though that the cursor is roughly half the height of the portrait, while in normal 1080p the cursor should be about the height of the portrait. A cursor the size of the visible butterfly would be nice, and even better, the option to configure it in the settings pane would be ideal as usual.

**Comment by BirdInTheCity** [comment]
@gdrewb-valve You mentioned above that cursor resizing doesn't currently work on a Mac.  Is it in the pipeline to get a mac fix in place?  I'm currently playing on a 2015 5k iMac and the game runs fantastically well at full resolution, but it's almost unplayable because the cursor is so small.

There seem to be some workarounds on reddit, but I'll wait if a better solution is being implemented.

**Comment by gdrewb-valve** [comment]
At the moment no, unfortunately.  We have a pile-up of SDL issues (SDL is providing the information about high-DPI to Reborn and it doesn't have an OSX path for that) so this is behind other bugs.

**Comment by gdrewb-valve** [comment]
Is this still happening after the March 24 SDL update?

**Comment by rcano** [comment]
Just checked, and yes.

**Comment by aigarius** [comment]
I think that the issue is actually something a bit different - the desktop friendly resolution could be at fault. If you have a 4k screen and your real resolution is set to 4k, but in Dota2 you set the resolution to 1080p then the game is rendered at 1080p and then scaled up by compositor, but the cursor is a hardware cursor that is rendered by compositor directly and thus it does not get scaled in that process. So one solution could be to scale the cursor by the ratio between real and in-game resolution or (more flexibly) provide an option for cursor scale in game.

**Comment by gdrewb-valve** [comment]
You're correct that the cursor doesn't scale with upscaling video settings but the cursor size should still be doubled on a high DPI system.  I believe most of the reports here are that it doesn't get scaled at all.

**Comment by rcano** [comment]
I'm using my native resolution (which isn't 3k but something close to it). The cursor is not being scaled at all. If I configure full screen with resolution of 1080p it is scaled up, just not with native resolution.
Indeed I think the real solution is providing an option to configure it (even if console based).
On the other hand, without really knowing SDL, I don't think any update to it will give you the DPI, since that is a KDE based setting in my case, but it could be a GNOME one, or enlightenment, or what have you. Maybe preconfigured sizes per screen resolution could be better. As a hack, I can swap the dota icon images with scaled up images, but it's a major pain, and I don't know if it works anymore (I think I did this with source 1).

**Comment by gdrewb-valve** [comment]
We need actual DPI information for reasonable automatic scaling. Basing it purely on resolution won't work well since you need to know the screen's physical size to have an idea of how large the cursor will appear.

Adding some kind of arbitrary user control might be possible, I'll check on that.

**Comment by aigarius** [comment]
Why would DPI matter? On my 13" laptop a 5mm cursor would be fine, but on my 60" TV I need a 4cm cursor at least. But if the resolution is the same, they are the same size in pixels. IMHO the cursor size needs to be proportional to the resolution as a baseline and from that users could adjust. Casters, for example, might actually want to have a smaller cursor in the streams. People with vision problems might want huge cursors even in 1080p resolution.
This could be a console command first and if many people use it, then promote to the UI.

**Comment by gdrewb-valve** [comment]
The DPI information is used for auto-sizing as it's the only way to guess how big a cursor would appear.

**Comment by gdrewb-valve** [comment]
The April 12 update added a -cursor_scale_percent launch option.  -cursor_scale_percent 50 will make the cursor 50% of its default size, -cursor_scale_percent 200 will make it twice as large as normal and so on.  People can give it a try to override the auto-scaling decision.

**Comment by mgalvank** [comment]
@gdrewb-valve How do I reduce it to the default size ? Here's how my cursor looks ingame after the latest update. 
![img-20160412-wa0002](https://cloud.githubusercontent.com/assets/16555428/14482006/fd944440-0105-11e6-974f-42d8254ddc37.jpg)

**Comment by gdrewb-valve** [comment]
-cursor_scale_percent 100 is probably what you want.

**Comment by rcano** [comment]
Great! I believe this can now be marked as fixed

**Comment by mgalvank** [comment]
@gdrewb-valve Yes, but how do I do that ? I tried doing it in console but it's not working.

**Comment by gdrewb-valve** [comment]
Right click on the game in your game list in Steam.  Choose Properties.  In the General tab there is a button named "Set Launch Options..."  Click on that and enter the text, then start the game.

**Comment by mgalvank** [comment]
@gdrewb-valve  Thanks that fixed it. Cheers.

**Comment by gdrewb-valve** [comment]
The fact that auto-sizing of the cursor is wrong sometimes affects all platforms so this will be handled by the larger team.  Anybody is welcome to use -cursor_scale_percent to work around it for now.
