### ISSUE TITLE
[Linux] Losing focus for more than a couple of seconds causes disconnect

### ISSUE THREAD

**Issue by chrylis** [ValveSoftware/Dota-2#360]
I often switch to other windows while dead. In Reborn, I can switch for a few seconds (about six), but more loss of focus reliably causes a server disconnect. I observe this in "default" or in "desktop-friendly fullscreen".

**Comment by chrylis** [comment]
This also happens if switching away from the loading screen, and then the game won't let you reconnect. Instant punishment for FTR.

**Comment by elfernesto** [comment]
Experiencing the same problem. It was present from early reborn betas.

**Comment by chrylis** [comment]
Also happens when focus is lost enough during a queue, which is infuriating with long queue times. This is clearly a *voluntary* issue caused by the game's choosing to stop responding to the network when it loses focus. I have no idea why somebody at Valve thought this was a good idea, but it's a major problem.

**Comment by gdrewb-valve** [comment]
I was unable to repro this.  Can you post your Steam system info?

What I did:
Start lobby on machine A (happened to be Windows).
Join lobby from machine B (Ubuntu 12.04).
Start game, pick characters.
On machine B switch to a different window.  Let it sit for a while, no problems.

**Comment by chrylis** [comment]
Was this a bot game or a real game?

**Comment by chrylis** [comment]
```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x46
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3300 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2

    Driver Version:  3.0 Mesa 10.6.4
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0xd26
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1600
    Desktop Resolution: 2560 x 1600
    Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                            59.7cm x 33.6cm  (68.5cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: VIA VT1802

Memory:
    RAM:  15972 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  128885 Mb
    Largest Free Hard Disk Block:  29417 Mb

Installed software:

Recent Failure Reports:
    Sat Oct  3 01:16:56 2015 GMT: file ''/tmp/dumps/crash_20151002192709_1.dmp'', upload yes: ''Discarded=1''
    Fri Oct  9 06:23:28 2015 GMT: file ''/tmp/dumps/crash_20151009002914_1.dmp'', upload yes: ''CrashID=bp-7d6431d0-e75e-4f7a-9f79-19d732151008''
```

**Comment by chrylis** [comment]
I'm using desktop-friendly fullscreen and switching desktops. The application is blurred (because compositing is disabled) but not minimized.

**Comment by gdrewb-valve** [comment]
My game had two humans and the rest filled with bots.  I was using a windowed video mode, does that change the behavior for you?

**Comment by chrylis** [comment]
I can give that a try, but that was causing lots of other problems (such as with general desktop focus and edge panning) when I tried it back before friendly fullscreen was added.

**Comment by elfernesto** [comment]
I'll test again later today also in windowed mode. 

Usually i'm in fullscreen mode, and bug is consistent. Everytime I tab-out to some other application dota disconnects from game server after around 10 seconds

**Comment by chrylis** [comment]
As this issue is completely reliable, I'd be happy to replicate it for you in real time if that would provide any useful data.

**Comment by gdrewb-valve** [comment]
I tried it with desktop-friendly fullscreen and I got the disconnect, so I can start investigating further.  My initial attempts didn't repro it but I didn't have the option to minimize on focus.  If you turn off that option so that the game doesn't minimize do you still get the problem?  That may also be why I couldn't repro with a window either.  Has anybody seen it when using a plain window?

**Comment by chrylis** [comment]
I never minimize the game, though I'm not sure what specific X events get sent when you switch away from the virtual desktop on a fullscreen window. The "minimize on blur" bug (#182) was a problem specifically because "blur" (I switched desktops) isn't the same as "this window isn't fullscreen and primary" when you have multiple virtual desktops.

**Comment by gdrewb-valve** [comment]
By default SDL will minimize on focus loss when you're using desktop-friendly fullscreen.  There's an option in the video settings to control it and I didn't have any problems until I allowed minimizing so I was guessing that might be part of it.

**Comment by gdrewb-valve** [comment]
In my testing this is definitely related to minimizing on focus loss.  When you switch back to the workspace with Reborn running, but minimized, SDL gets a focus-in event and tries to do a window grab.  That doesn't work since the window is minimized and SDL keeps trying over and over again and never gives control back to Reborn to run the game.  Eventually the server thinks the client has disconnected and gives up.  I'll raise this with the SDL devs.

**Comment by chrylis** [comment]
The distinction between "not visible" (or possibly "not on top") and "minimized" might be important; I can see from my pager that the window is still taking up the whole desktop (thus not minimized from a X perspective) but isn't visible, which SDL may treat identically.

**Comment by chrylis** [comment]
FWIW, I don't have the problem when queuing. It does show up on the loading screen and even after clicking "accept" on a match while still in the lobby.

**Comment by chrylis** [comment]
It also apparently disables the "pause countdown" sounds, which is _really_ nasty.

**Comment by engywook** [comment]
I have this too, posting to get a notification when/if it is fixed.

**Comment by engywook** [comment]
I am watching the Frankfurt Majors in the client and can switch workspace without getting disconnected while watching. I guess the data is just broadcast and not much is sent from the  client watching but still.

**Comment by chrylis** [comment]
@engywook You won't get "disconnected" because you're only spectating. The client engine will pause, and you'll (1) get the music (2) but no event sounds (3) and notice a big jump when you switch back and it teleports everyone.

**Comment by engywook** [comment]
@chrylis I still heard the casters though. I don't recall if I heard event sounds.

**Comment by chrylis** [comment]
@engywook Interesting, and I wonder if there's a multicast setup involved. Regular voice chat cuts out.

**Comment by Turmfalke2** [comment]
ok, I missed this bug report. I am suffering from exactly the same issue, are there any additional information that we might be able to provide you so this can get fixed?

**Comment by gdrewb-valve** [comment]
No, we just need to get some of the SDL dev team's time so that they can take a look.  That's out of our control.

**Comment by ErnestasJa** [comment]
For me when I tab out of window dota2 freezes completely and I have kill the process. Though killing the process freezes my whole system..

**Comment by jerobarraco** [comment]
i have the same issue. its very annoying, i use to change windows while im dead or sometimes i need to, and i get disconnected. ALL THE TIME, is VERY annoying. 

im using kde ubuntu 14.04, compositing DISABLED, game mode "borderless window", but if i recall correctly, same issue happened with fullscreen and desktop friendly FS with auto-minimize.
Also, i noted that while minimized, the cpu consumption is half than focused. exactly half.

i usually change virtual desktops, not windows, and still the same.

`
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x1
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3100 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-77-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon R7 200 Series   

```
Driver Version:  4.5.13416 Compatibility Profile Context 15.20.1046
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x6658
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 18,66" x 11,65"  (21,97" diag)
                                        47,4cm x 29,6cm  (55,8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  16048 Mb

Miscellaneous:
    UI Language:  English
    LANG:  es_AR.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  365526 Mb
    Largest Free Hard Disk Block:  5247 Mb

Installed software:

Recent Failure Reports:

`

**Comment by gdrewb-valve** [comment]
Is this still happening after the March 24 SDL update?

**Comment by chrylis** [comment]
Yup, with the addition of all the performance glitches.

**Comment by icculus** [comment]
Just wanted to ping on this; are people still seeing this issue? I'm not able to reproduce it now (Ubuntu 16.10, the default Unity desktop environment, "desktop-friendly" window, etc), but it's possible I'm not doing it right. A lot of code has changed in these pieces of SDL since March.

Let me know when you get a chance!

**Comment by ramma** [comment]
Also unable to reproduce it on 16.10, but I can't actually set the display mode to desktop-friendly fullscreen like was mentioned above for reproducing this. The option reverts to "Use my monitor's current resolution" once the options are reopened, but the other display modes set just fine. Not sure if the display mode matters much.

Either way I got no disconnects in all modes I could set, irrelevant of whether "Desktop-friendly full screen minimize on focus lost" was on or off.

**Comment by Turmfalke2** [comment]
hi @rcgordon 
I am using Gentoo with herbstluftwm and the problem still persists.
Test 1:
I created a lobby on the luxembourg server with no bots, after spawning as Abaddon I changed to another tag (completely hides the window) for 2 minutes. While doing so I still heard the music, but up on changing back to the tag with dota 2 I got disconnect from the server message with no way to reconnect.

Test 2:
A bit later, apparently the steam servers went down(?) I entered the game in offline mode and launched the demo mode for Abaddon. Again after 2 minutes of being on other tag I switch back to be greeted by the 'Dire victory' with the continue button that brings me back to the main menu.

I could really use a better terminology to describe what my wm is doing, but I think it should be identical to minimize a window in an ordinary desktop environment. https://herbstluftwm.org/tutorial.html

E: I am using the 'Desktop-friendly fullscreen minimizes on focus loss option' and if I don't switch a tag and just partially cover the otherwise fullscreen Dota window with other windows I don't encounter any disconnects.

**Comment by dsjoho** [comment]
Still seeing this @rcgordon on archlinux (current up to a couple of days) with KDE/Plasma 5.8.
Switching workspaces for more than a couple of seconds causes a disconnect, in all the scenarios described above. 
This with dekstop-friendly fullscreen, as well as the border-less window.
The option for minimizing on focus loss is disabled.

**Comment by TheNeikos** [comment]
@imdoes I also use Herbstluftwm and have the same issue

**Comment by dsjoho** [comment]
@TheNeikos @Turmfalke2 I have changed to herbstluftwm for unrelated reasons and in the process found a workaround which isn't pretty, but it works. 
I do not know how to achieve the same thing in other window managers, but it's probably doable, ymmv.

Add the following rule to your hlwm autostart (or just test it out manually, might want to add your normal `tag=X`, I removed mine so as to not suprise you if you copy paste). 
The key parts are the `ewmh* `rule(s) with `fullscreen=on` being possibly necessary. Feel free to experiment, this works for me:

```
# dota 2
hc rule class=dota2 focus=off ewmhnotify=off ewmhrequests=off fullscreen=on
```
In dota I have (without being sure how it's affected by other modes): desktop-friendly fullscreen mode. 
Minimize on focus lost doesn't seem to have any effect good or bad.

If you now open any other program (I prefer a simple terminal) on the same tag as dota and _make sure that the focus is on that window,_ you will be able to switch tags indefinitely without dota disconnecting or resizing its window (which happens if the ewm hints are allowed). 
Once you're back on the dota tag, just cycle the non-game-window back into the background and continue where you left off :)

**Comment by TheNeikos** [comment]
Something I did find while scouring the internet today is this console command:
`engine_no_focus_sleep 0`

And from my testing it seems to work, maybe it can help you (and maybe the devs can put some light on what this one does differently to the menu options?)

**Comment by gdrewb-valve** [comment]
The March 16th update has the latest SDL which is supposed to have a fix for this.  If anybody is still seeing it please post here.

**Comment by TheNeikos** [comment]
Or that might have fixed it! I will try it without setting that value

Just ran a test game, and it seems fixed, and it's also much smoother so yay! Thanks a lot

**Comment by gdrewb-valve** [comment]
Closing as this appears fixed.
