### ISSUE TITLE
Low fps on new update

### ISSUE THREAD

**Issue by Frank1230** [ValveSoftware/Dota-2#389]
Since the merger of Reborn to the main client, the game seems to be experiencing my lower levels of FPS than it's predecessor.  Going from a stable 120 down to numbers varying from 40-70, going even lower when graphic heavy animations are happening.  This makes the game essentially unplayable.

**Comment by troughton** [comment]
I'm also having this issue on a mid-2012 Retina MacBook Pro (2.6GHz i7, 8GB RAM, GeForce 650m, El Capitan public beta). With the settings the same as the previous client (albeit with Shadows off instead of on low), I get 25-50fps, usually hovering around 35fps, compared to a fairly consistent 45-70fps on the old client. It also 'feels' lower still than that, making me think that those average framerates are higher than the instantaneous framerates – however, I'm only speculating.
Notably, turning off all settings brings the framerate to 100-120fps (at 1080p), but even enabling one option (e.g. even Animated Portrait) reduces it to ~70-60fps and sometimes lower. 
The performance level is also much lower compared to the Windows version on the same hardware – with all settings enabled, at 1080p and with -dx11 as a launch option, I get 40-60fps, and it feels much smoother. I understand performance parity is not expected, but in the old client I could get close by turning shadows from high to medium and disabling ambient occlusion – this is no longer the case.

A semi-related issue is that there are drastic framerate drops (low 20s or even lower) when I jump to viewing a different section of the map for a 1-2 second period (e.g. if I'm in mid and I click to top lane, the framerate will drop or the game might even pause until that area is loaded in).

My video.txt file reads as follows:

`"video.cfg"
{
    "VendorID"      "4318"
    "DeviceID"      "4053"
    "setting.cpu_level"     "2"
    "setting.mem_level"     "2"
    "setting.gpu_mem_level"     "1"
    "setting.defaultres"        "1920"
    "setting.defaultresheight"      "1080"
    "setting.gpu_level"     "3"
    "setting.version"       "1"
    "setting.knowndevice"       "1"
    "setting.fullscreen"        "0"
    "setting.coop_fullscreen"       "1"
    "setting.nowindowborder"        "0"
    "setting.mat_vsync"     "0"
    "setting.dota_cheap_water"      "0"
    "setting.r_deferred_height_fog"     "1"
    "setting.r_deferred_simple_light"       "1"
    "setting.r_ssao"        "0"
    "setting.cl_globallight_shadow_mode"        "0"
    "setting.r_dota_fxaa"       "0"
    "setting.r_deferred_additive_pass"      "1"
    "setting.dota_portrait_animate"     "1"
    "setting.r_deferred_specular_bloom"     "1"
    "setting.r_deferred_specular"       "1"
    "setting.dota_ambient_creatures"        "1"
    "setting.r_texture_stream_mip_bias"     "0"
    "setting.r_dota_normal_maps"        "1"
    "setting.r_dashboard_render_quality"        "1"
    "setting.shaderquality"     "1"
    "setting.recommendedheight"     "800"
    "setting.mat_viewportscale"     "1.000000"
    "setting.r_fullscreen_gamma"        "2.101416"
    "setting.useadvanced"       "1"
    "setting.aspectratiomode"       "1"
    "setting.fullscreen_min_on_focus_loss"      "0"
}`

**Comment by wliment** [comment]
same problem , in osx 10.10  (i7, 16GB RAM, GeForce 750m) old client is smoother than reborn client ,

**Comment by davidw-valve** [comment]
To achieve equivalent performance to the Source1 client you may have to disable some graphical settings.

The reason this is is that many graphical features were not implemented on OSX on Source1, even if they appeared to be usable from the menus. Now we have implemented them, but this means that you have to turn them off if you want performance comparable with Source1.

**Comment by troughton** [comment]
Would you be able to give an indication as to what settings would need to be disabled to be equivalent to the S1 settings? In testing a little more it seems that High Quality Water and "Specular and Light Blooms" are the major performance killers - particularly the former.

Also, disregard this if you can't answer it, but is there any expectation for performance to close in on what I get under Windows/DX11 on the same hardware? I understand that drivers/APIs are different and that there are issues with Apple's OpenGL implementation (especially since they're shifting their focus to Metal) – is this level of performance roughly what we can expect going forward, or is there still significant optimisation to be done?

**Comment by danginsburg** [comment]
@troughton On Linux with NVIDIA GL the performance is better than the same machine on Windows+DX11.  The code is essentially the same on OSX, except Mac GL doesn't support GL_ARB_buffer_storage (used to write vertex/index/constant updates to persistently mapped buffers from multiple threads), GL_ARB_vertex_attrib_binding (used to reduce switching vertex API overhead), and seems to have a poor implementation of ARB_texture_storage causing performance drops (when it should be faster).

Ambient Occlusion and Anti Aliasing are not implemented in the source 1 version on OS X, so at a minimum turn those off for comparison.  There are other significant differences between the shaders from Source 1 and Source 2.  The Source 2 vertex shaders make use of storing transform data in vertex textures which is a win on efficient OpenGL implementations because it increases batch efficiency by reducing draw calls.  Unfortunately, on some OS X OpenGL drivers this seems to come at a performance cost.  

We have also had to workaround OS X GL shader bugs that don't exist on the same hardware on Linux/Windows.  For example, on Intel HD 5000 we were punting to software on one of our heaviest used vertex shaders because it used more than 8 interpolators (something the HW supports just fine).  This meant moving a lot of instructions from the vertex shader to fragment shader which came at a performance cost, but better than punting to software.

We are trying to work with Apple and IHVs to resolve performance issues as best we can.  We will continue to try to improve performance.

**Comment by Vuccappella** [comment]
I'm experiencing fps drops as well compared to source 1. I used to run both source 1 and now Source 2 with only the Animate Portrait and High Quality Water settings on, Source 1 I'd get a constant 120fps but on source 2 I get 70-110 and the biggest problem is it fluctuates a lot and it's not steady, I feel.

**Comment by admshao** [comment]
I have to say that just the day before the merge of clients. The Linux Reborn client was so solid with constant 120 FPS(if i type fps_max 300 -> fps went to 220-240) and now after the merge it fluctuates a lot. between 110-120(fps_max 300 -> fps goes to 110-200). I know its weird. But i can provide logs if u guys teach me how to greb.

Its still way better than Win7 for my rig. Nice work!

Ubuntu 15.04 (Linux 3.19.0-28-generic)
OpenGL version: 3.2.0 NVIDIA 346.59 @ GTX 770 4GB
Processor: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
Physical Memory: 7928MB Total

**Comment by Vuccappella** [comment]
Just played today and it was actually lower (iMac (27-inch, Late 2012) 3.2 GHz Intel Core i5 24 GB 1600 MHz DDR3 NVIDIA GeForce GTX 680MX 2048 MB )) I get 30-60 fps comapred to the 120fps of source one and its constantly fluctuating :(. Same settings as source 1, graphics high, rendering high, only animated protrait on, nothing else. Is there anything i can try to attempt a fix ?

**Comment by Frank1230** [comment]
I originally started this thread.  I have lowered the graphics lower and it worked all right for a day or two. Today there was a small update implemented that seems to have made it worse. It's become actually unplayable; the Fps drops to 1 for a good 15 seconds at the beginning of games and is oscillating more than before. These sorts of problems never happened on source 1. I understand certain graphic settings are now in effect for Mac, but now everything is turned off, I lowered the graphics to the lowest possible while trying to keep the game still enjoyable and it barely performs. I'm quite confused

**Comment by gdrewb-valve** [comment]
How is the perf nowadays?

**Comment by Frank1230** [comment]
Much better in fact. The interface and loading times are also much quicker. Sometimes though, there are some isolated games which cause my fps to drop.

**Comment by gdrewb-valve** [comment]
OK, I'm going to close this issue.  If you find a specific set of repro steps for a slowdown go ahead and open a new one.
