### ISSUE TITLE
Korean does not work on Mac Reborn Client (Now the main client)

### ISSUE THREAD

**Issue by sunwoo-kim** [ValveSoftware/Dota-2#392]
When you set the language to Korean for Dota in the main client, all the korean characters are invisible; same with the chat: You cannot type any Korean in the chat. Please fix this.

**Comment by danginsburg** [comment]
Confirmed.  Investigating.

**Comment by sunwoo-kim** [comment]
Hi, since you responded, I'd like to mention the long-lasting korean chat bug on the mac client as well: 
When you chat in game, You have to put a space after what you write in korean (on a mac), otherwise your message gets repeated for some bizarre reason or doesn't send sometimes. Thanks for your work!

**Comment by danginsburg** [comment]
We have tracked down the issue.  At the moment we just have a workaround, but will be working on a real fix.  This bug impacts both Linux and OSX and the crux of the problem is the game relying on the presence of the Gulim system font for Korean characters.  To workaround:
1. Go to a windows machine and copy c:\Windows\Fonts\gulim.ttc
2. On OSX or Linux, do mkdir ~/.fonts
3. Copy gulim.ttc to that folder

You should see Korean characters after that.  We'll work on a better fix, but should get you going for now.

**Comment by sunwoo-kim** [comment]
Oh cool. So that was the directory, not the main font one; I tried installing Gulim before but it didn't work. This way, you can make the font anything you want! 

By the way, I just wanted to point out that a lot of Korean people HATE Gulim, so maybe when you're working on the fix, you might want to take note of that. 

Thanks a lot.

**Comment by danginsburg** [comment]
We have a fix for this bug on OSX/Linux that will go out in the next Dota 2 update.  It will not require or use the Gulim font.  It uses our own font.  Thanks for the bug report.

**Comment by appleparan** [comment]
Please let windows team do same thing (embed your own font). Gulim = Comic Sans in Korea. Nanum Gothic is recommend (SIL OpenFont license 1.1) for korean fonts.

**Comment by appleparan** [comment]
Font issue is fixed today. it is not perfect (see #425), but anyway now I can see and type Korean.
