### ISSUE TITLE
[Linux] FPS Drops (Arch Linux, AMD CPU, NV GTX 650 352.30)

### ISSUE THREAD

**Issue by nekuro-dev** [ValveSoftware/Dota-2#395]
I'm getting massive FPS drops every 2-3 seconds, making the game unplayable.
The FPS will go from ~60 to ~10-20, irrespective of settings or resolution. I can put settings to the lowest, where I get >100fps, and yet it still drops,  causing a lot of stuttering.

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0xa
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3214 Mhz
    6 logical processors
    6 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  Fluxbox
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 650/PCIe/SSE2

```
Driver Version:  4.5.0 NVIDIA 352.30
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xfc6
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1600 x 900
Desktop Resolution: 1600 x 900
Primary Display Size: 17.44" x 9.80"  (20.00" diag)
                                        44.3cm x 24.9cm  (50.8cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Nvidia GPU 42 HDMI/DP

Memory:
    RAM:  4963 Mb

Edit: I just tried a bot game after validating files again, and I wasn't getting any frame drops. I then went in the menu and turned shadows off, then went back in the game and the FPS drop issue was back. After that point no change of settings stopped the frame drops. I'm not sure if this is relevant or just coincidental.

**Comment by danginsburg** [comment]
If you run with -console and hit "\" when the framerate drops, do you see any messages in the console that correspond with when the drops happen?  If so, can you run with -con_logfile and post the contents of game/dota/console.log when you see the framerate issue?

**Comment by nekuro-dev** [comment]
I checked the console as the drops started happening, but it was empty.
Weirdly the frame rate keeps spiking down even while paused over a hero just standing in lane.
I'll be checking the windows version later today or tomorrow to see if I get the same issue there.

Edit: Tested the windows client. Same issue. Seems it's not a linux client issue - just source 2 not liking my hardware or something. I do know that this is a relatively recent issue... It didn't happen when the reborn beta started.

**Comment by danginsburg** [comment]
This is a total guess, but might the CPU be getting frequency scaled (perhaps due to heat)?  On my Intel box I do this (the last part wouldn't be relevant since you are on an Intel CPU):

#!/bin/bash

set -x

cpufreq-set -c 0 -r -g performance
cpufreq-set -c 1 -r -g performance
cpufreq-set -c 2 -r -g performance
cpufreq-set -c 3 -r -g performance
cpufreq-set -c 4 -r -g performance
cpufreq-set -c 5 -r -g performance
cpufreq-set -c 6 -r -g performance
cpufreq-set -c 7 -r -g performance

mount -t debugfs none /sys/kernel/debug > /dev/null 2&>1 || true
MAXCLOCK=`cat /sys/kernel/debug/dri/0/i915_max_freq`
bash -c "echo $MAXCLOCK > /sys/kernel/debug/dri/0/i915_min_freq"

rmmod intel_powerclamp x86_pkg_temp_thermal

Then I do this to watch the clock rates:

gnome-terminal -e 'watch -n1 "cat /proc/cpuinfo | grep MHz"'
gnome-terminal -e 'watch "sudo sensors -f"

At the very least you could try watching /proc/cpuinfo as at the bottom to see if your CPU is getting frequency scaled at the points at which the framerate drops.

This is just a shot in the dark, I haven't seen this behavior on an NVIDIA GPU like you have.

**Comment by davidw-valve** [comment]
Can you please also tell us what /sys/devices/system/clocksource/clocksource0/current_clocksource contains on your system?

**Comment by nekuro-dev** [comment]
No frequency scaling, just tested to make sure. current_clocksource is tsc

**Comment by suptimal** [comment]
tsc i have framedrops too

**Comment by suptimal** [comment]
yesterday anything was smooth => dota update => today its laggy

**Comment by gdrewb-valve** [comment]
Has anything changed with the recent updates?

**Comment by gdrewb-valve** [comment]
Closing pending more info.
