### ISSUE TITLE
[Linux] Failed to start game (missing executable).

### ISSUE THREAD

**Issue by caesium1107** [ValveSoftware/Dota-2#401]
The following are the solutions I tried:

-Delete appcache folder
-Verify integrity of game cache
-Flushing my Steam application files
-Opted into Beta participation
-Fresh Re-download (including Steam client)

Worked fine in Source 1. Happened since yesterday, when Source 1 was completely replaced by Source 2. Current OS is Elementary OS Freya.

**Comment by davidw-valve** [comment]
What are your system specs?

Are you on a 32 bit system by chance? (Dota2 now only supports 64 bit Linux).

**Comment by BeastOutside** [comment]
If you see message with "Force Quit" and "Wait",just press wait,and game will be minimize into dock.Now,just click to "Dota 2",and your game will run.I think,this is an patheon issue,but if u do what i sayed,game works
P.S. sorry for bad english

**Comment by caesium1107** [comment]
Hi David. Yes, I'm on a 32 bit system, though was not aware that Dota 2 only supports 64 bit Linux currently. Is there any future update that will enable 32 bit Linux to run Dota 2 (so that I don't have to reinstall my os)? And is 32 bit Windows still being supported? Thanks.

**Comment by ArnaudAndre** [comment]
See david's answer in #18 . No plan to keep supporting 32 bit linux.
They're still building for 32 bit windows.

**Comment by davidw-valve** [comment]
I am afraid that we don't have any plans to support Dota2 on 32 bit Linux going forward. The Linux ecosystem has great support for 64 bit applications and that is what most users use.

We do still support 32 bit on Windows.

**Comment by dafuq1337** [comment]
Could you at least fix that I can install it, if I can't run it - and if that's to much work, at least give a decent error message?
It seems like a huge waste of time and broadband to install it (twice).
While figuring out what the problem is, steam recommanded to remove the appcache folder - which obviously didn't help ...

If I try to start dota, I get the error "Failed to start game (missing executable)." - which is the reason why I reinstalled. Only after trying to start the executable in the terminal, gave a error which explained the problem ...

I can truly understand that you don't support 32 bit, but at least  give decent errors / write it in the f***\* requirements / make it public.

**Comment by Tele42** [comment]
The 64 bit requirement is documented at https://github.com/ValveSoftware/Dota-2 but not on the store page.

**Comment by dafuq1337** [comment]
Sorry, I didn't find this. Would it be possible to update the instruction in store? I think that would really be great and beneficial as I am not the only one who missed this dependecny.
I think the links to this github page are rather hidden ...

Thanks for the fast reply.
