### ISSUE TITLE
[OS X] Watching & Queuing crash in El Capitan Public Beta

### ISSUE THREAD

**Issue by michaelkclements** [ValveSoftware/Dota-2#471]
I had been playing Reborn since the first El Capitan Public build came out a few months ago now and I thought finally Dota was playable without worrying about crashes. Never really experienced it on a regular occurrence like the Source 1 Dota did; until now. 

I had just been watching a few games (after a few weeks break from playing Dota) and it started crashing fully. Kept doing the same thing and managed to crash it every time in a relatively short period of time.

https://i.imgur.com/WdakG54.jpg Here's an image of the crash logs. I'm using a 2012 iMac with an 3.4 GHz Intel Core i7 and GTX 680MX if that helps?

**Comment by michaelkclements** [comment]
The latest patch may have fixed the issue. Will keep checking.

**Comment by michaelkclements** [comment]
Nope. It seems it happens when I'm watching a game and finding a game at the same time.

**Comment by danginsburg** [comment]
The crash pictured in the far right was fixed by the 9/19 update.  The other three crashes in your screenshot are different.  Please post Steam -> Help -> System Information.  Also, if you could provide either an upload of the minidump file from a crash or your Steam ID we can take a look at the crash in more detail.  If you run with -con_logfile and provide game/dota/console.log that may provide useful information to us as well.

**Comment by michaelkclements** [comment]
System Info - http://pastebin.com/raw.php?i=X8yDdtLz
Crash log just now after clicking to join a 10v10 Custom Game then quickly watched the first item in the watch tab while still in queue. Pretty much insta-crash - http://pastebin.com/raw.php?i=XYfTXTsX
Console log - http://pastebin.com/raw.php?i=ZY4mJfhj

Hope that helps.

**Comment by gdrewb-valve** [comment]
These aren't Mac-specific bugs and I've passed them on to the larger team.  I believe at least one more of the crashes should be fixed.
