### ISSUE TITLE
[Linux] Input Methods not supported

### ISSUE THREAD

**Issue by rcano** [ValveSoftware/Dota-2#50]
I'm using the great fcitx for input method handling, unfortunately dota2reborn ignores it completely not allowing me to type in anything but english (it does seem to respect keyboard layout though). It also ignores my xmodmap'ped keys.

**Comment by gdrewb-valve** [comment]
It's expected that IMEs do not work as there is no support (just as in Source 1 Dota 2).  There are issues with keyboard layouts that may affect the xmodmap case, though.

**Comment by rcano** [comment]
If there is no support for IME in Linux, can we make this issue a feature request? I see no good reason to have IME support in Windows and not in Linux.

**Comment by osleg** [comment]
@rcano I guess that dota just grabs the keys from X server and using it's own mappings, this actually desired way of how OpenGL should handle this

**Comment by rcano** [comment]
@osleg Actually a recent update in the Reborn (I didn't pinpoint which) added support for the mapped keys. But when this issue was created it was not picking them up (just like main client).
Still this issue is now an enhancement request for IME support on linux.

**Comment by osleg** [comment]
@rcano I have xmodmaped keys as well and they are not honored by Reborn, though since last update I was unable to start the game so maybe it was added it in it

**Comment by gdrewb-valve** [comment]
@osleg, have you been able to try this since?  I'm going to rename this to reflect that it's now just for the IME request.

**Comment by RenanOliv** [comment]
I've done some tests and hopefully I can provide more info about this issue.

My keyboard model is a Steelseries Apex Raw and I'm using Ubuntu 14.04 LTS. As the Apex Raw has no official Linux support I'm using an utility to enable the extra macro keys named [ApexCtl](https://github.com/tuxmark5/ApexCtl).

So basically Dota 2 can't understand my keybinds at all with xmodmaped and since [it is kinda deprecated](http://lists.freedesktop.org/archives/xorg/2008-April/034402.html) I tried my best to make it work creating a custom xkbmaps.

My MX1-MX5 keys were mapped to F1-F5 keys, but only the MX3 and MX4 keys were able to be binded in Dota 2. When using xev both keys show the same result, the only difference is that the mapped key has a `XKeysymToKeycode returns keycode: 19` assigned to it. Any other software is able to understand the mapped keys, I had no problem using it on Firefox, Sublime or Unity. 

Maybe Dota can't see any specific Key Codes? It seems very unlikely, since I can use my keyboard macro keys to type in the game chat (If I bind a letter, for example) and all my macro keys key codes are in a good range (183-172).

I hope this can help somehow, I recently switched from Windows and I spent some weeks trying to understand both how the Linux environment works and how to fix this problem.

**Comment by gdrewb-valve** [comment]
@RenanOliv, if you start with -input_button_code_is_scan_code does that make a difference?  That should switch Reborn to using scan codes underneath, which may or may not help you.

This has nothing to do with IMEs, just for clarity with the overall issue.

**Comment by gdrewb-valve** [comment]
If only one input method was supported which one would you vote for?  fcitx?

**Comment by rcano** [comment]
Definitely fcitx.

**Comment by xen0n** [comment]
fcitx :+1: , but maybe supporting the general IME framework like XIM or KDE IM is what people want instead... AFAIK fcitx and ibus are almost equally popular among Chinese users.

**Comment by zeroedout** [comment]
It looks like GNOME [integrates ibus now](https://help.gnome.org/misc/release-notes/3.6/i18n-ibus.html.en), so +1 for ibus! I don't pity the dev that has to look up the different Linux input methods and choose just one to support. Does Valve have data on which desktops / input methods are most common among Linux Steam Users? I mean internal data, I can always point you folk to community data but it's hardly reliable.

**Comment by gdrewb-valve** [comment]
No, we don't.  We've looked at a few options in the past; SDL has ibus support so that's one of the leading contenders.

**Comment by gdrewb-valve** [comment]
The latest release enables the SDL ibus IME support.  Has anybody had any luck trying it out?

**Comment by rcano** [comment]
I can't test since I don't use ibus IME, only fcitx.

**Comment by jingzhaoyang** [comment]
Today, I suddenly found that the Chinese can be input using fcitx, but the `Enter` open dialogs invalid. I can only click the icon to open the dialog and input .

**Comment by gdrewb-valve** [comment]
The SDL devs are taking a look at this, I don't think the fcitx support is complete.

**Comment by Tele42** [comment]
Initial support for fcitx appears to have been added yesterday: https://hg.libsdl.org/SDL/rev/6660aa9120d6

**Comment by gdrewb-valve** [comment]
I believe the update on Oct. 12 contained full support for fcitx. Can people comment on whether it is working for them?

**Comment by rcano** [comment]
It works for me! Thanks!
The only issue I have is when using a table lookup (such as for unicodes) the popup appears, but I can't click, my cursor goes back to desktop cursor while hovering over it, but I can't interact. Otherwise it's perfect!

**Comment by gdrewb-valve** [comment]
Go ahead and open a specific issue for that and I'll assign it to the SDL devs.  I'm closing this as the general feature request is addressed, now we'll switch to individual bug issues.

**Comment by Saladin1812** [comment]
Fcitx not working on fedora 30 for me i cant type japanese on steam Valve doesnt care we know now.. also simply i can type japanese in browser and other places simply adding japanese input in gnome settings but steam is still typing in english. Thanks Valve for pathetic support.
