### ISSUE TITLE
[Linux] Client crashes when I select the "watch" tab

### ISSUE THREAD

**Issue by sinatosk** [ValveSoftware/Dota-2#568]
Using other areas of the client including playing games and no problems but with watch tab... crashes after a second and in that second everything in the client is paused...

I see this in my dmesg

`dota2[8238]: segfault at a ip 00007f70de5fc95e sp 00007ffeebaa5820 error 4 in libtcmalloc_minimal.so.0[7f70de5e7000+21000]`

and sometimes

`GlobPool0[7878]: segfault at 5 ip 00007f940204895e sp 00007f93f93b3110 error 4 in libtcmalloc_minimal.so.0[7f9402033000+21000]`

the number after "segfault at ", "ip ", "sp " and "libtcmalloc_minimal.so.0[" changes

and minus the usual steam dump crash upload stuff this is at the end

`pid 9131 != 9129, skipping destruction (fork without exec?)`

info from steam about my setup

http://pastebin.com/MLPxB6Wm

**Comment by loisgomez** [comment]
Affected as well on Ubuntu 14.04 since last patch.

Crash output.
    Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
    ERROR: ld.so: object '/home/berto/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so'  from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/berto/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/berto/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
crash_20151014141223_1.dmp[7960]: Uploading dump (out-of-process)
/tmp/dumps/crash_20151014141223_1.dmp
/home/berto/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: línea 104:  7923 Violación de segmento  (`core' generado) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 570 "Dota 2", ProcID 7923 
crash_20151014141223_1.dmp[7960]: Finished uploading minidump (out-of-process): success = yes
crash_20151014141223_1.dmp[7960]: response: Discarded=1
crash_20151014141223_1.dmp[7960]: file ''/tmp/dumps/crash_20151014141223_1.dmp'', upload yes: ''Discarded=1''
pid 7960 != 7958, skipping destruction (fork without exec?)

```
Información sobre el procesador:
Fabricante:  GenuineIntel
Familia de la CPU: 0x6
Modelo de la CPU: 0x3a
Stepping de la CPU: 0x9
Tipo de CPU: 0x0
Velocidad: 4300 MHz
Procesadores lógicos: 8
Procesadores físicos: 4
HyperThreading:  Compatible
FCMOV:  Compatible
SSE2:  Compatible
SSE3:  Compatible
SSSE3:  Compatible
SSE4a:  No compatible
SSE41:  Compatible
SSE42:  Compatible

Información sobre la red:
Velocidad de la red:  

Versión del sistema operativo:
Ubuntu 14.04.3 LTS (64 bits)
Nombre de kernel: Linux
Versión de kernel: 3.19.0-30-generic
Editor de X Server: The X.Org Foundation
Versión de X Server: 11701000
Gestor X Window: Compiz
Versión del runtime de Steam: steam-runtime-release_2015-06-12

Tarjeta de vídeo:
Controlador:  NVIDIA Corporation GeForce GTX 680/PCIe/SSE2

Versión de controlador: 4.5.0 NVIDIA 355.06
Versión de OpenGL: 4.5
Densidad de color del escritorio: 24 bits por píxel
Frecuencia de actualización del monitor: 59 Hz
Identificador del fabricante: 0x10de
Identificador del dispositivo: 0x1180
Número de monitores: 1
Número de tarjetas de vídeo lógicas: 1
Resolución de pantalla principal: 1920 x 1200
Resolución de escritorio: 1920 x 1200
Tamaño de pantalla principal: 20,43" x 12,76"  (24,06" diag)
                                        51,9cm x 32,4cm  (61,1cm diag)
Bus principal: PCI Express 16x
Memoria VRAM principal: 2048 MB
Modos MSAA compatibles: 2x 4x 8x 16x 

Tarjeta de sonido:
Dispositivo de sonido: Intel PantherPoint HDMI

Memoria:
RAM:  7867 Mb

Varios:
Idioma de la IU:  Español
IDIOMA: es_ES.UTF-8
Micrófono:  Not set
Espacio total en disco disponible: 227093 MB
Bloque libre más grande en el disco: 109686 MB
    Software instalado:
    Informes de fallos recientes:
Wed Oct 14 12:04:02 2015 GMT: file ''/tmp/dumps/crash_20151014140326_1.dmp'', upload yes: ''CrashID=bp-d75265d0-bda1-4da1-b431-324b52151014''
```

```
```

**Comment by Tele42** [comment]
Duplicate of #561.

**Comment by gdrewb-valve** [comment]
Closing duplicate.
