### ISSUE TITLE
Clicking to buy an item sometimes not working

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Dota-2#576]
Sometimes when I click on an item to buy it, the click will be registered and the sound feedback will be present, but the item won't be bought. If the bug occurs in Quick Buy, the item will disappear from the QB. Here's a video:

http://gfycat.com/EllipticalImprobableAlleycat

Happens on Linux (Mint 17.2 x64) and possibly Windows (a friend of mine seems to have the same problem).

Also, sometimes when I try to buy an item in Dire top/Radiant bottom secret shop, the item will go into stash instead of being directly equipped on the hero (boots, TP, for example). You can hear the sound of entering the shop, you'll be in range, but it still goes to stash. Again, happens to a friend on Windows, too.

**Comment by gdrewb-valve** [comment]
Issues which occur on all platforms aren't handled here, but I passed this on to the larger team.  One person did comment that on a quick look the GIF seemed to have correct behavior but they weren't sure exactly what they should be looking for.  Can you give more details on exactly what's going wrong in the GIF?

**Comment by gdrewb-valve** [comment]
Also, do you have a match that Valve employees could watch to see the issue?

**Comment by ghost** [comment]
I'm reporting this bug here because I'm not 100% sure it happens on other platforms. So to explain the problem a bit better. Sometimes when I try to buy an item, I hear the sound feedback of it being bought, but that's all. No item was bought, no gold was spent. I just get the sound feedback of it being bought.

And on the gif you can see that I click on ALL THREE components, but only TWO were bought (and were made into the Headdress). I clicked on the recipe too (in this case for the Pipe of Insight), it disappeared from the Quick Buy, however it WASN'T BOUGHT. Even though I got the visual and sound feedback.

I don't see how this is supposed to be intended.

**Comment by gdrewb-valve** [comment]
The larger team had a question about what was in the quick buy.  Response:
Headdress has 3 components one of which is a recipe.  He has no recipe in the stash and the amount of gold deducted from him is equivalent to the amount an entire Headdress costs(~600).  Could it be that he put the wrong item in quick buy, because to complete Pipe in this situation he would actually need 4 components.  The gif only starts with 3.

**Comment by ghost** [comment]
Yes, seems so. However, I put Pipe in QB. Here's the Match ID 1870968576. Watch from around 45:18, Lion's Player perspective. The recipe for the Pipe just disappeared. I did not drop any other item into QB. I'm playing on 1080p, just in case you need to know for the replay to be shown properly (cursor positioning).

However, the other problems I mentioned are still there. E.g., getting the sound feedback for buying an item, but not actually purchasing it, even though it was clicked on.

**Comment by gdrewb-valve** [comment]
I've passed this on.

**Comment by gdrewb-valve** [comment]
The larger team looked at your match and feels that things are working as expected with the purchasing.  The sound issues aren't Linux-specific so I'm closing this out.

**Comment by ghost** [comment]
So nothing on why the Recipe for Pipe disappeared by itself on 45:18? Without me doing anything?

**Comment by gdrewb-valve** [comment]
They thought that you had clicked, is this not accurate?
::: Watching his mouse positions again, it looks exactly like he moves his mouse over where the pipe recipe would be in the combine tree inside the shop, and clicks, then moves his mouse quickly away.

**Comment by admshao** [comment]
On top of that. I can add that weird things happens when you have exactly
the money for a item. or the mana. and so forth

Let me try to be clear. You have 70 gold and want to buy a tp on the
Shortcut that you place above the Gliph Button. You spam clicks until you
have the 75 gold. The client will hide and show the item and play the sound
like you had just bought and after that gives the error message about
lacking gold.

But it`s way worse with speels and mana. (i might add cooldowns here too)
The game just ticks and you have the exactly mana for a spell. For a
fraction of second or so, you still can`t use the spell, The icon is full
colored showing that you have the mana, but the game gives you the error
message about lacking mana. It`s been like this since Source 1. And for
sure not linux related. But for me it`s a problem on gameplay. And gosh how
many situations it happened to change the flow of the game.

2015-10-21 21:30 GMT-02:00 Drew Bliss notifications@github.com:

**Comment by gdrewb-valve** [comment]
@admshao, I've passed this back to the main team but this isn't really the forum for things that happen on Windows and in Source 1.
