### ISSUE TITLE
hero texture and model error

### ISSUE THREAD

**Issue by Eignar17** [ValveSoftware/Dota-2#587]
![pantallazo](https://cloud.githubusercontent.com/assets/8561550/10570298/94ed2c66-75f7-11e5-9fb2-2a1ccc1ef00a.png)

**Comment by justSQL** [comment]
AFAIK, this is a reaaalllyyy old issue and I'm surprised it's still not fixed. This has been bothering modders even before they had official support. It's related to customs not refreshing the herolist/addon_english files. I'm  a bit surprised that it's still not fixed after official support. There have been multiple reports about this on the dev forums, and i'm fairly sure there are many with even better repro steps and the like, but these two i could find within 5 minutes of searching: http://dev.dota2.com/showthread.php?t=182743&highlight=custom+game+ui+bug http://dev.dota2.com/showthread.php?t=183028&highlight=custom+game+ui+bug

Would be really great if someone could pass this to the larger team to finally have a look at it. We've had this issue for pretty much since the beginning of dota 2.

(someone else can give more detailed information about this bug and i can get people to give more insight here if that's required for this to get fixed.)

**Comment by justSQL** [comment]
Decided to gather a few more posts from the dev forums:
http://dev.dota2.com/showthread.php?t=176336&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=176025&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=175654&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=174710&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=174175&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=176765&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=173983&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=180954&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=180599&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=180343&highlight=custom+game+ui+bug (maybe related?)
http://dev.dota2.com/showthread.php?t=180198&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=180141&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=178669&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=178416&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=182442&highlight=custom+game+ui+bug
http://dev.dota2.com/showthread.php?t=182604&highlight=custom+game+ui+bug

Would probably be good to get it fixed finally.. :p

**Comment by gdrewb-valve** [comment]
I'll send it on.

**Comment by gdrewb-valve** [comment]
The larger team has this list now.  Due to the number and variety of bugs here it's hard to say when they'll get addressed.
