### ISSUE TITLE
[MAC OS] Left CMD key binding doesn't work

### ISSUE THREAD

**Issue by gselsidi** [ValveSoftware/Dota-2#616]
Can you add functionality to bind the CMD key?

In windows keyboards the ALT key is in current CMD key position on MACs. There are alot of bindings that involve the ALT key in windows, which translates into the Left CMD key on mac.

**Comment by Tele42** [comment]
There should be an option in an advanced hotkey section to allow this as noted at https://github.com/ValveSoftware/Dota-2/issues/465#issuecomment-147472279.

**Comment by gselsidi** [comment]
@Tele42 

Thanks will try that, will close issue for now.

**Comment by gselsidi** [comment]
The only thing I achieved was to bind CMD by itself, which is utterly useless. I need to bind cmd+q cmd+w cmd+e like alt in windows.

**Comment by gdrewb-valve** [comment]
Reborn only supports binding Alt as a modifier (for example, you cannot bind Ctrl+key on Windows).  I believe there are products that can make the Command appear as Alt if you want that, but you can't bind separately from Alt.  I've marked this as an enhancement request but I'm not sure of what would be done here since you'd quickly get into collisions with system keys like Cmd+C/Cmd+V/Cmd+Tab and so on.

**Comment by gselsidi** [comment]
Well we can turn off cmd+c/cmd+v as I don't see many people copying and pasting in Dota, and if you had a urgent  need you can always use your mouse or the right ctrl key if need be. 

I would leave only left ctrl + tab unbindable. then the rest of the system commands can be executed with the right ctrl key if there is a need.

Just put an option in advanced settings to either turn this functionality on or off, it doesn't have to be an all or nothing for everyone.

**Comment by Vuccappella** [comment]
This has always been the case in dota on mac, you can't bind cmd+something as it's not a modifier. You still have alt on your keyboard and could use that. You've probably recently switched from windows but it's just how the mac keyboard is layed out. You could swap the behaviour of alt and cmd on mac if you're interested but I haven't found a way to do that only in dota, it's going to be global. Personally I got used to using alt+bind although it's a bit less intuitive. I'm just happy I can bind CMD to something (from advanced settings) since I didn't know about this option prior to reading this thread, that's how it worked on source one and I'm glad there's an option to be able to bind that key now.

**Comment by NekR** [comment]
I have had the same problem and solved it with Karabiner software for the OS X (please do not treat it as an Ad).

It has a lot of predefined bindings, but also allow to define your own. So it becomes super easy to fake Command as a Alt (Option).

Here is my config for Macbook (**please do not copy past it unless you know how it works**):

``` xml
<?xml version="1.0"?>
<root>
  <appdef>
    <appname>DOTA</appname>
    <equal>com.dota2</equal>
  </appdef>

  <item>
    <name>Dota 2</name>

    <item>
      <name>Command to Option (Alt)</name>
      <identifier>private.dota2_alt</identifier>
      <only>DOTA</only>
      <autogen>__KeyToKey__ KeyCode::COMMAND_L, KeyCode::OPTION_L</autogen>
    </item>

    <item>
      <name>Function to Control</name>
      <identifier>private.dota2_control</identifier>
      <only>DOTA</only>
      <autogen>__KeyToKey__ KeyCode::FN, KeyCode::CONTROL_L</autogen>
    </item>
  </item>
</root>
```

Works perfectly for me, but I user Exclusive Fullscreen and do not need system shortcuts since they do not work anyway. Might not work for other modes as expected though.

Also here is a relevant thread: https://github.com/tekezo/Karabiner/issues/355

**Comment by gselsidi** [comment]
@NekR 

And the program above applies these settings only in DOTA not system wide correct?

Thanks

**Comment by NekR** [comment]
Not program directly, but program has ability to do it. My config applied those settings only for Dota 2 because I use `<only>DOTA</only>` and `DOTA` constant is defined a bit above:

``` xml
<appdef>
    <appname>DOTA</appname>
    <equal>com.dota2</equal>
  </appdef>
```

How to:
1. Install Karabiner and launch
2. Finder -> Go to -> "~/Library/Application Support/Karabiner/"
3. Open `private.xml` in any editor and paste there config from https://github.com/ValveSoftware/Dota-2/issues/616#issuecomment-155938214. Then save file changes.
4. Open Karabiner, find button "Reload XML". User it.
5. Go to tab "Change key" and fine "Dota 2" list section. It should be first.
6. Check required items in "Dota 2" section or one if you do not want both.

Now it will map keys **only** in Dota 2 app. But be aware that it completely maps `Command` to `Option` and `Fn` to `Ctrl` and does not do reverse, e.g. `Ctrl` is still `Ctrl` **This means that `Fn` and `Command` will be unavailable while you are playing Dota 2**.

How to undo:
1. Go to Karabiner and uncheck selected items for Dota 2.

**Comment by gselsidi** [comment]
@NekR Got it thanks for the help, can finally enjoy dota again haha, would hurt my finger playng with Option as a binding haha.

**Comment by gselsidi** [comment]
@NekR Also once i set do i need to keep karabiner open to keep the keys mapped in dota? Or can I quit after I check the keys? 

Thanks

**Comment by NekR** [comment]
You can close the window, but app still will be active in background
(square icon in top bar). Keys mapping works only when app is active. To
completely quit Karabiner, click on that icon and then "Quit Karabiner".

It's fine to have it active all the time since mapping is enabled only for
Dota 2.

**Comment by PizzaPino** [comment]
Can't we have this working in-game? There's even an option to enable the CMD button, which doesn't work.

**Comment by gdrewb-valve** [comment]
Dota is still limited in what modifiers you can use, this isn't a Mac issue.  You can't use shift or control for bindings on any platform.  You can't use the Windows key on Windows.  The larger team has been doing some key binding updates and might be considering this but I have no idea if or when that'll happen.

**Comment by gdrewb-valve** [comment]
Assuming that you have NOT chosen to allow the Command key to bind itself as of May 16 you should now be able to bind Command+Key combinations.  Give it a try.

**Comment by gdrewb-valve** [comment]
Note also that the binding will show up properly in the settings but in the actual in-game UI it will say "Alt" instead of "Command".  That's something the larger team will fix later.

**Comment by gselsidi** [comment]
Confirmed Working. You have to make sure in Advanced options the option to allow "Windows Key/Command key to be bound is not selected" then you can bind CMD+ whatever, also confirmed that is shows up incorrectly as ALT. Closing Issue
