### ISSUE TITLE
The newly added netgraph option

### ISSUE THREAD

**Issue by budimanjojo** [ValveSoftware/Dota-2#641]
According to the latest update news, there's a new netgraph option. So I tried:
1. Added -vconsole to the launch options.
2. Typed in "consoletool netgraph 1" in the console
3. Nothing happens, no error no nothing.

**Comment by gdrewb-valve** [comment]
The netgraph will appear in vconsole2, which is a separate executable.  It's Windows-only, so you'd need to run vconsole2 on a Windows machine and connect to your Linux machine running the console server.

**Comment by budimanjojo** [comment]
Is it gonna come to Linux?

**Comment by gdrewb-valve** [comment]
vconsole2 isn't going to come to Linux any time soon.  I'll ask the larger team about whether they can keep the old option for Linux.

**Comment by budimanjojo** [comment]
Ok, at least we can get the old netgraph back

**Comment by gdrewb-valve** [comment]
Exactly what information would you like to see?  The larger team feels that the existing HUD element shows the most common data.  They'd prefer to add more simple info there if that satisfies the need.

**Comment by budimanjojo** [comment]
The think I miss about the old netgraph is that I can change the location to wherever I want. Maybe they can provide that? Maybe a smaller and transparancy options will be nice. Because the new one is too big and when I'm playing 10vs10 map the rightmost player icons are blocked.

**Comment by justSQL** [comment]
I think what you'd mostly want the netgraph for is the more advanced data it provides, as stated by fletcher here http://dev.dota2.com/showthread.php?t=184807

"Finally, there is the full netgraph tool, accessible through the Source2 vconsole tool. This tool previously displayed the command latency only, the same as the in-game HUD. Now, it breaks down the sources of latency into "peer" "net", and "local". The "peer" number accounts for items 5--8, "net" is the ping time, and "local" measures for items 10 and 11. If you add peer latency, net latency, and local latency together, you get the command latency. If you feel a spike of sluggishness in game, but the ping time doesn't change, this probably means that there isn't a network issue, but instead something is causing the frame rate on the server or client to spike. The local and peer latency numbers (and your FPS readout) can help narrow it down."

Otherwise i don't see a real use for it.

**Comment by gdrewb-valve** [comment]
I've passed this on to the larger team.

**Comment by gdrewb-valve** [comment]
The larger team is going to look at having the HUD element fit better into the HUD overall but that'll probably be part of a long-term HUD overhaul.  They weren't as keen on adding more information to the HUD element since it's supposed to be simple and provide just the most useful information so I'm not sure that's going to change.  If you really need the new info for now you'll have to have a Windows machine.
