### ISSUE TITLE
Dota game client always gets bundled with Steam by Unity

### ISSUE THREAD

**Issue by vadi2** [ValveSoftware/Dota-2#655]
Dota never opens in its own window, and instead masquerades as a Steam window. This makes it harder to alt-tab around than it needs to be.

![selection_257](https://cloud.githubusercontent.com/assets/110988/11322253/d8191278-912e-11e5-8c0b-96f7ea9da504.png)

**Comment by gdrewb-valve** [comment]
Not the behavior I see on Ubuntu 12.04.  SDL is the code actually creating the window so Reborn isn't directly in charge of window properties but we can check a bit more.

**Comment by fumazu** [comment]
I can confirm this for Ubuntu 15.10. Dota 2 and CS:GO get bundled with the Steam client while the third party game _The Binding of Isaac: Rebirth_ spawns a new icon.

From Screenshot with _Dota 2_ and _The Binding of Isaac: Rebirth_ open in the background:
![steam](https://cloud.githubusercontent.com/assets/12823243/11408723/51b11430-93bb-11e5-878d-dd19eb072407.png)

Edit: Just want to add that I don't really mind this. There are plenty of options to quickly switch between windows (SUPER + W or Right click on group -> select window)

**Comment by vadi2** [comment]
I'm running 14.04 LTS and I've had this issue for as long as I can remember - it happened in the pre-Reborn client as well.

**Comment by u00101010** [comment]
I'm running 15.10, but I haven't had this issue before with 14.04 either. To me, DOTA 2 has its own icon. (though it does not technically have an icon)
![screenshot from 2015-11-27 19-13-19](https://cloud.githubusercontent.com/assets/7419656/11446725/560c15f8-953b-11e5-9205-b807109f4959.png)

**Comment by gdrewb-valve** [comment]
We'll have to try and find exactly why this happens.

**Comment by p-lr** [comment]
+1000 to this one. I am on ubuntu 14.04 and i always had this issue.

**Comment by p-lr** [comment]
Are there at least workarounds to use before this issue is fixed?

**Comment by gdrewb-valve** [comment]
We don't know what the problem is so it's hard to say what might work around it.  It doesn't occur here at Valve, plus as I mentioned previously Reborn isn't doing any of its own window management (that's SDL) so we've been waiting to see what the SDL devs might say.

**Comment by p-lr** [comment]
I found a workaround, and i can tell you more about the issue. The problem seems to appear when the game is launched from steam (click on the "play" button).

Workaround :
1- In the steam client, right click on "dota 2" > properties. In the "general" tab, i clicked on the button "create a shortcut on desktop". 
2- Close steam and dota2.
3- Launch dota2 from the shortcut on the desktop. I got this :

![image](https://cloud.githubusercontent.com/assets/15638794/12179926/f5e9628e-b579-11e5-9d13-6005358fff52.png)

Notice that dota2 finally has its own window and then we can alt-tab as we want. I even tested to launch steam after that, close dota2 and launch it from steam.. and dota2 gets its own window!! The problem however reappears when i close dota2 AND steam, and i launch dota2 from steam.

Hope this helps.

**Comment by gdrewb-valve** [comment]
Interesting, thanks for the information.

**Comment by vadi2** [comment]
I can't confirm the workaround atm but I can confirm that I've always launched Dota from Steam.

**Comment by fumazu** [comment]
I can confirm the workaround. And I don't know if it's obvious by now, but it also works for other games such as _Civilization 5_.

**Comment by gdrewb-valve** [comment]
This has been confirmed as a problem with bamf and is not related to Reborn, closing.  The bamf people are going to work on a fix.

**Comment by vadi2** [comment]
Thanks for engaging in collaboration to find the source of the problem!

**Comment by Tele42** [comment]
For reference, this is bamf: https://launchpad.net/bamf, a subcomponent of the unity desktop environment.
