### ISSUE TITLE
In Game FPS performance

### ISSUE THREAD

**Issue by omartan** [ValveSoftware/Dota-2#817]
Hi,

I wonder, do Dota 2 makes use of dual GPU? As I'm running on a nMP and maxing out all the graphical setting will result in 50fps, dropping the shadow quality to high and game screen render to 90% will give me back that 60fps.

Though upon checking my GPU usage, it seems the 2nd GPU isn't used?

Thanks

**Comment by Tele42** [comment]
What is a nMP? What OS are you running?

**Comment by omartan** [comment]
nMP stands for new Mac Pro which is the cylindrical black one which comes with dual GPU

OSX El Capitan
Mac Pro (Late 2013)
3.7 GHz Quad-Core Xeon E5
12GB 1866 MHz DDR3 ECC
Dual 2048MB FirePro D300

**Comment by danginsburg** [comment]
Currently, we do not do anything to explicitly enable multi-GPU on OS X.

**Comment by AdmiralACE** [comment]
I am facing random fps drop while playing/watching dota2 matches from last few days. And because of that i am unable to play. Today i tried to play CS:GO and the same issue emerged. The frame drop remains for some time then i get normal frame rate again the frame rate drop occurs at random intervals. Unable to play..Please Help.
 
  Model Name:	Mac mini
  Model Identifier:	Macmini6,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	16 GB

**Comment by nascob** [comment]
Same situation here. I noticed that when running the game one of the GPUs sits idle without any memory or computation load. It would be awesome if we could get some basic sort for this.

**Comment by gdrewb-valve** [comment]
Closing this because it's not a Mac/Linux issue.  It's a valid request but this forum is only for porting bugs.  The general Dota forum is dev.dota2.com
