### ISSUE TITLE
[Linux] Starting game with non-English keymap makes binds unworking

### ISSUE THREAD

**Issue by B9707C6887CD8B31AB6F62718091A968** [ValveSoftware/Dota-2#859]
I'm using two keyboard layouts. US and RU one. So when I'm running game while it's US layout keybinds work correctly. But if I start game while Russian layout is ON, all binds stop working. I can text but can' not use any abilities from keyboard. Changing keymap while in game is useless. Only solution to reload game with English keymap.
Hope you fix it. :D

**Comment by gdrewb-valve** [comment]
This is probably expected.  If you go into the advanced section of the binding settings and select positional bindings does that do more of what you want to do?

**Comment by NekR** [comment]
@gdrewb-valve not sure about original bug, but I know other bug: If you start game with other lang selected, it displays key-binding-hints on items for that language, even if "positional bindings". e.g., for button "B" it displays Russian "И", while I expect it to still be "B" since "positional bindings" is selected.

P.S. I am on OS X.

**Comment by gdrewb-valve** [comment]
That's correct behavior, positional bindings means that the key position on the keyboard is remembered, not the character on the key.  If you switch keyboard maps a positional binding won't change but the character on the keycap can change.  If you want bindings based on characters then turn off positional bindings, in which case when you change keyboard maps the key you need to press can change.

**Comment by NekR** [comment]
What I want is this:

1) be able to use binding with key I set no matter which language is selected (positional binding on, right?)
2) Key hints displayed on items/abilities be always displayed on English.

This is that I used to have on Windows.

Plus, those displayed hints do not change, e.g. if I start with Russian lang selected, hints are always displayed in Russian, no matter how much times I change it to English and back during the game. So this seems to be sort of inconsistent behavior.

**Comment by NekR** [comment]
Hmm.. "want" is incorrect here I think. More like "expect" because I had that behavior on Windows and in most other games, e.g. no one game displays binding hints in "current language". Not sure, maybe this is usable for Asian langs/keyboards or something like that, but for other people it must be kind of weird.

**Comment by gdrewb-valve** [comment]
For 1 you do want positional bindings.  There's no existing way that I know of to accomplish 2, key names will always be displayed in whatever language the system reports key names to SDL.  You could open an always-English feature request at the SDL Bugzilla and a Dota request at dev.dota2.com.  However the desired behavior in the game is to show the character for the key based on the current keymap so I'm not sure there'd be much desire to create a special "force English" mode.

**Comment by gdrewb-valve** [comment]
I'm going to close this out as there doesn't appear to be a Mac-specific problem here (your feature requests would affect all platforms and should be posted at dev.dota2.com).
