### ISSUE TITLE
[Linux] Poor performance from last month (few latest update broke my FPS) Catalyst

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/Dota-2#900]
Hi.

In Dota 2 I recently played seriously month ago, because currently I not have time. Then dota 2 runs very well.

Today I came back. But the game works much worse. Performance is worse in the game than before (few latest update broke my FPS). So I don;t know that update broke. But I know that one of the last month.

Previously, I had about 70 FPS, now 20-60 of them during the fighting 20-30 FPS.
In addition, there are often micro trimmed to 1-3 seconds, when FPS shows 1 FPS.

From that time on my computer, there were no changes to the hardware or drivers, only updated the kernel Linux 4.4.0 to 4.4.11, besides, nothing.

Quick info:
AMD Radeon HD 5850 1GB with AMD Catalyst 15.9
AMD Phenom II X6 3GHz
4 GB of RAM to 1600MHz
Mageia Linux 5 X64 KDE.

Steam system info: https://gist.github.com/xpris/40a171182843bbbd6782e593f9bd8881

**Comment by gdrewb-valve** [comment]
FPS issues are being reported on all platforms and as this is a general issue the larger team is taking a look.

**Comment by phoerious** [comment]
Are these FPS issues only reported for the in-game experience or also for the main menu and stuff? Because yesterday I opened Dota2 again for the first time in a month and the whole main menu was pretty laggy. I don't know what FPS it is, but it's really noticable: transitions aren't smooth and everything's sluggish.
The in-game performance is pretty bad as well, as reported already: in hero demo mode I still get 60 FPS but when watching real games, it's down to 30 FPS.

**Comment by gdrewb-valve** [comment]
They've been reported for everything.

**Comment by phoerious** [comment]
Yeah, I just tried a game and I was playing with 15-20 FPS. Normally I play with a steady 60 FPS (vsync) with highest settings at 2560x1440px.

**Comment by gdrewb-valve** [comment]
7.00 has changed performance significantly so we are closing out old perf issues in favor of #1101. Anybody on this issue is welcome to post their current 7.00 performance experience here (not 1101) even after this is closed so that we can get updated information.
