### ISSUE TITLE
High CPU usage after last weeks update[Linux]

### ISSUE THREAD

**Issue by AshishBhattarai** [ValveSoftware/Dota-2#905]
After last week update i get 80%+ cpu usage at UI.
https://i.imgur.com/fCHxvPO.png

OS: Arch Linux x86_64
Kernal: 4.4.13-1-lts
WM : Openbox
Processor Type: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
Nvidia Drivers : 364.19
OpenGL Version: 4.5.0

**Comment by gdrewb-valve** [comment]
I'm not sure there's anything wrong as there is no attempt to minimize CPU usage in the UI, but I'll take a quick look.

**Comment by AshishBhattarai** [comment]
Its same during gameplay too. The game was killing my CPU so i used cpulimit to limit the cpu usage to 60%. Works fine with cpulimit.

**Comment by gdrewb-valve** [comment]
It's definitely expected that during the game two or even three cores will be kept busy.

**Comment by AshishBhattarai** [comment]
I never got 80% (cpu0) usage before. I think thats too much. 
My cpu was always 50%-60% (cpu0) ingame and 25%-35% (cpu0) in UI.

**Comment by Tele42** [comment]
For what it's worth, any computer that can't handle the cpu running at 100% for an extended period and fails has a bad cooling solution or an undersized power supply. It does not matter what it is running. Most modern processors have a critical temperature shutoff which prevents damage from high heat.

**Comment by AshishBhattarai** [comment]
Yea but missuse of resources is not good + it makes a huge noise.

**Comment by gdrewb-valve** [comment]
I did some quick checks and the Linux and Windows versions appear to use roughly the same amount of CPU (Windows is even higher in my testing).  CPU usage is not low but over time the main menu has gotten more complicated and I don't believe it's going to switch to something more plain to conserve CPU.  You can post a request at dev.dota2.com but there's no Linux/Mac specific issue here so I'm closing this.

**Comment by 420git** [comment]
I've been having the same problem since the same period.Something in Dota is bugged to require such highload of the CPU talking from an i5 3rd gen, while my core 2 duo on win xp is working without issues.
After bumping my head trying to resolve this I found a workaround that is helping me for the time being I disabled the intel_pstate driver which recognizes my cpu highest frequency 3.2ghz and uses it by default for the highload dota,and instead using the default acpi which limits my frequency to 2.6ghz.
This helps my cpu staying cooler to aout 80 C instead of reaching 100C and shuting down,
