### ISSUE TITLE
Game causes computer crash (full freeze, no TTY)

### ISSUE THREAD

**Issue by lewisdiamond** [ValveSoftware/Dota-2#909]
After update to 6.88 and upgrade nvidia drivers from 364.19-1 to 367.27-1, game crashes multiple times per game (fully crashes the PC).

On a side note, I've had issues with voice comm, not being transmitted (it's picked up by the game, testing the microphone in the options works fine, but people can't hear me).

**Comment by Tele42** [comment]
Your description of the issue sounds like a video driver issue, I would revert to the known good driver version and retest.

**Comment by lewisdiamond** [comment]
Could be a driver issue, could be a Dota issue. Unfortunately, System Information doesn't provide any crash reports...

**Comment by Tele42** [comment]
If you're getting a kernel panic due to something going wrong in the nvidia kernel module, then anything in the userspace would not have a chance to write to a log. If this was one of my systems, I'd get netconsole setup so that the kernel has a chance of sending a kernel panic to another system on the network, and the only time I've seen that fail is if a thermal safety trips and the system hard-stops.

**Comment by gdrewb-valve** [comment]
Dota can't cause the system to crash so this is definitely outside of the scope of this forum.  I'd go ahead and open a separate issue for the voice problem.
