### ISSUE TITLE
[MacBook, OS X 10.11] Show Fps option missing + low gameplay performance

### ISSUE THREAD

**Issue by kunalex** [ValveSoftware/Dota-2#953]
Hello,

First of all, could someone redirect me to the optimal performance settings.
My display card is AMD Radeon R9 M370x 2048 MB with 2.5GHZ Intel Core i7, 16 RAM. I am on a MacBook Pro 15.

My gamplay performance is poor. 30 fps maximum, on the lowest video settings and biggest and ugliest rezolution. 

Also, I cannot find the show fps option in the dota2 menu. Is it removed in the Dota for Mac version?

Thank you,
I hope I posted in the right section.

Have a lovely day,

**Comment by gdrewb-valve** [comment]
There are a number of Mac perf problems open here already, you might want to look through those.  As you are unable to get the performance you want even at the lowest settings I'm not sure there's much extra advice about turning things on since that would just reduce your frame rate even more.  Unfortunately getting engagement from Apple on performance and stability of OpenGL has been difficult so progress is extremely slow.

Can you point out which FPS option you mean in the current Windows version of Dota?

**Comment by Tele42** [comment]
@kunalex, you can turn on the on-screen fps counter with `cl_showfps 1` in the console. There also is `dota_hud_netgraph 1` and `stats_display 1`. I read the opening post as there is no option in the settings to toggle one of these.

**Comment by gdrewb-valve** [comment]
@kunalex asked about it being removed for the Mac version so I thought he was referring to something that existed for the Windows version.  I don't believe there is such a UI setting on any verison but I wanted to confirm what kunalex was thinking of.

**Comment by gdrewb-valve** [comment]
Closing for now.  There are already Mac perf issues open and until we hear if there's something Mac-specific about the FPS counter I don't think there's an extra issue here.
