### ISSUE TITLE
[Linux] Dota2 cant display traditional chinese character in HUD.

### ISSUE THREAD

**Issue by Dota2player1** [ValveSoftware/Dota-2#963]
All the characters which cant displayed in game are Traditional chinese characters.
This issue occurs because 
1. Valve is using some GB2312 chinese fonts (for simplified chinese characters only) like SimKai in HUD.
    The way to fix is change the font to some Unicode chinese fonts like DFKai-SB(KaiU).
2. Valve added words in HUD with GB2312 encoding.
    unicode encoding please.
![d2-1](https://cloud.githubusercontent.com/assets/20713785/17233802/af3f9d7a-54f8-11e6-9f60-ebc6ad602382.png)
![d2-2](https://cloud.githubusercontent.com/assets/20713785/17233803/af416d1c-54f8-11e6-8a8c-34f3a49b058a.png)
![d2-3](https://cloud.githubusercontent.com/assets/20713785/17233804/af424f8e-54f8-11e6-83a8-efa9269ed845.png)
![d2-4](https://cloud.githubusercontent.com/assets/20713785/17233801/af3f3c2c-54f8-11e6-82ce-b5abcef90291.png)

OS: Fedora 24 (x86_64)
Kernel: 4.6.4-301.fc24.x86_64
DE: Gnome 3.20.2
Graphic Card: GeForce GTX 780
nvidia-installer:  version 367.35
System Language: Traditional Chinese (Chinese(Taiwan))
Dota2 language: Traditional Chinese

**Comment by gdrewb-valve** [comment]
Dota doesn't provide full CJK fonts so your system fonts are used for at least some characters.  You may be able to affect which fonts get used by tweaking your fontconfig settings.

Dota does all of its string processing in either UTF-8 or wchar_t.

**Comment by Dota2player1** [comment]
The problem is which font is dota using there and how can I tweak that

**Comment by gdrewb-valve** [comment]
Dota uses a variety of fonts and those fonts are changing as pages change.  However I'm not sure that matters as Dota uses pango, freetype and fontconfig and those all provide font fallbacks based on Unicode character coverage.  If a particular font Dota is using doesn't have some characters it should fall into system fonts according to fontconfig setup.

As for fontconfig, https://www.freedesktop.org/software/fontconfig/fontconfig-user.html is probably a decent place to start.

**Comment by Dota2player1** [comment]
I just cant find the font which dota2 using there.....
FC_DEBUG=1 log file:
https://gist.github.com/Dota2player1/5189b2cbccdd38ef359206b408179eea/raw/d87ecd129f9220d602bc4b2fd8e6d34e85d13a41/FC_DEBUG=1

**Comment by Tele42** [comment]
Hello @Dota2player1,

Are you able to determine if the font debug is spewed into the log at during startup of the game or when new glyphs are being rendered (or failing to render)? If the debug information is spewed as you're typing new characters, you should be able limit the amount of information you need to analyze by starting the game, going to the screen just before the characters of interest are rendered, then alt-tab out of the game, open a terminal and run `tail -f /path/to/logfile` in order to get the terminal to effectively listen to new things in the logfile. Then return to the game, get it to render the text of interest. If you're lucky, then the terminal should have a relatively short amount of information to deal with.

I hope this actually helps.

NOTE: tail -f will keep on showing additions to the log until you stop it.

**Comment by Dota2player1** [comment]
Hello @Tele42 
that font is only used for heros' name, abilities' name, items'' name, match mode name, radiant and dire **in game**
even the description of items and abitilies are using different fonts. also different font for chat.
I cant determine it so I just recorded all information since steam client startup and still failt

**Comment by gdrewb-valve** [comment]
Is this still happening after the 7.00 HUD changes?

**Comment by gdrewb-valve** [comment]
Closing as this doesn't appear active anymore.
