### ISSUE TITLE
[Ubuntu/Linux] Quickcast mouse-bindings only not immediately casting

### ISSUE THREAD

**Issue by kaiserprogrammer** [ValveSoftware/Dota-2#974]
quickcast is working for keybindings, but not for mouse-bindings. Cast is normally selected and requires another left-click to activate it. 
e.g blink-dagger: supposedly bound with quickcast enabled to mouse4, pressing mouse4 selects blink-ability and requires an additional left-click to determine location. Moving blink-dagger to another inventory slot with keybinding set to "u". Pressing "u" immediately casts blink on current mouse location without requiring an additional left-lick.

**Comment by gdrewb-valve** [comment]
I don't think this is a Linux-specific issue, checking with the larger team.

**Comment by kaiserprogrammer** [comment]
It works fine in windows.

**Comment by gdrewb-valve** [comment]
I'll pass that on, thanks.

**Comment by gdrewb-valve** [comment]
The larger team doesn't have any leads and I don't see this behavior on my Linux box (I used mouse3 as I didn't have a mouse with a working mouse4 to try right away).  If you reset your binds to the default and then redo the quickcast does it work?  Does it work if you use mouse3 instead of mouse4?  Is the bind recognized as mouse4?

**Comment by kaiserprogrammer** [comment]
It recognized the mouse buttons correctly and the problem persisted further with the middle mouse button mouse3.
However disabling and enabling quickcast in the sub-entry for item bindings fixed this problem.

**Comment by gdrewb-valve** [comment]
OK, I'll tell the larger team about that possible bug.
